Repository MetaMorphic-Digital/draw-steel, pull requests merged in 2025-09, with the labels that each got.

#989 Moved Power Roll Effects to top-level key to match Advancements
  CHANGELOG.md
  lang/en.json
  src/module/config.mjs
  src/module/constants.mjs
  src/module/data/pseudo-documents/power-roll-effects/applied-effect.mjs
  src/module/data/pseudo-documents/power-roll-effects/base-power-roll-effect.mjs
  src/module/data/pseudo-documents/power-roll-effects/damage-effect.mjs
  src/module/data/pseudo-documents/power-roll-effects/forced-movement-effect.mjs
  src/module/data/pseudo-documents/power-roll-effects/other-effect.mjs
  templates/sheets/pseudo-documents/power-roll-effect-sheet/details-tiers.hbs
Labels: UI/UX

#1031 [#996] Fix level up button not showing unless XP is more than next level XP
  CHANGELOG.md
  src/module/data/actor/hero.mjs
Labels: data model

#1033 Fix Bugbear Channeler's Catcher action type (#1027)
  src/packs/monsters/Bugbears_IOJX0Gbij4nZLkvh/npc_Bugbear_Channeler_ZaENuomw1aFn4Ffw.json
Labels: compendium

#1055 [#961] Add perks and ancestry traits to item grant allowed types
  CHANGELOG.md
  src/module/data/pseudo-documents/advancements/item-grant-advancement.mjs
Labels: data model

#1003 Kobolds for Monster Compendium
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Kobold_Malice_xuS3HDBwVVF8JHHi/ability_Maniple_Tactics_KOsnxnQvSid3ZahG.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Kobold_Malice_xuS3HDBwVVF8JHHi/ability_Set_the_Initiative_fyuPK3F17a7SWmWO.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Kobold_Malice_xuS3HDBwVVF8JHHi/ability_Shield_Wall_FTBTYYIqhMaTU882.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/folders_Kobold_Malice_xuS3HDBwVVF8JHHi.json
  src/packs/monsters/Kobolds_SWbDTDwNDPa3JlDQ/npc_Kobold_Adeptus_Li9JlvgHDfRJod3p.json
  src/packs/monsters/Kobolds_SWbDTDwNDPa3JlDQ/npc_Kobold_Artifex_FHZkr0qisqJxByYK.json
  src/packs/monsters/Kobolds_SWbDTDwNDPa3JlDQ/npc_Kobold_Centurion_sQnPdTwdehktLvxo.json
  src/packs/monsters/Kobolds_SWbDTDwNDPa3JlDQ/npc_Kobold_Legionary_1rcyL6J5vNBSuPV0.json
  src/packs/monsters/Kobolds_SWbDTDwNDPa3JlDQ/npc_Kobold_Princeps_gWjAaDWAa6dtxBNa.json
  src/packs/monsters/Kobolds_SWbDTDwNDPa3JlDQ/npc_Kobold_Sagittarion_A2IJElaA0cJlTTsX.json
  src/packs/monsters/Kobolds_SWbDTDwNDPa3JlDQ/npc_Kobold_Signifer_wjt5ZFcacSsShHMc.json
  src/packs/monsters/Kobolds_SWbDTDwNDPa3JlDQ/npc_Kobold_Tiro_7l9gYevMavIPZfkw.json
  src/packs/monsters/Kobolds_SWbDTDwNDPa3JlDQ/npc_Kobold_Veles_jCFtKlDWA1VRIanb.json
  src/packs/monsters/Kobolds_SWbDTDwNDPa3JlDQ/npc_Kobold_Venator_50RUglwzyIkqqnOV.json
  src/packs/monsters/Kobolds_SWbDTDwNDPa3JlDQ/npc_Shieldscale_Drangolin__Size_2__hcefTkFaqh8e8eXf.json
  src/packs/monsters/Kobolds_SWbDTDwNDPa3JlDQ/npc_Shieldscale_Drangolin__Size_3__hYJnlT4BiFTtYYvL.json
  src/packs/monsters/Kobolds_SWbDTDwNDPa3JlDQ/npc_Trained_Gummy_Brick_pSo8ZnNvMIPuwfbb.json
  src/packs/monsters/folders_Kobolds_SWbDTDwNDPa3JlDQ.json
Labels: compendium

#1016 Gnoll Monster Compendium
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Gnoll_Malice_aDi1dYz0yHDdrvpt/ability_Bloodpool_38qnomOvMFz9ES4D.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Gnoll_Malice_aDi1dYz0yHDdrvpt/ability_Echoes_of_Laughter_wvrInGnyn0e0mj0n.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Gnoll_Malice_aDi1dYz0yHDdrvpt/ability_Iron_Jaws_9bdZ4N6vu3nGUvPk.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/folders_Gnoll_Malice_aDi1dYz0yHDdrvpt.json
  src/packs/monsters/Gnoll_6ZOnXQw3kIUDhVuS/npc_Abyssal_Hyena_5oS4rixqbIcsziNm.json
  src/packs/monsters/Gnoll_6ZOnXQw3kIUDhVuS/npc_Gnoll_Abyssal_Archer_O6zR2JbaxoIkHbDV.json
  src/packs/monsters/Gnoll_6ZOnXQw3kIUDhVuS/npc_Gnoll_Abyssal_Summoner_mNtGL8Wbj8mqpCzy.json
  src/packs/monsters/Gnoll_6ZOnXQw3kIUDhVuS/npc_Gnoll_Bonesplitter_6OtKjm4juYqustqw.json
  src/packs/monsters/Gnoll_6ZOnXQw3kIUDhVuS/npc_Gnoll_Cackler_GtHSux5DwCQ0sx2O.json
  src/packs/monsters/Gnoll_6ZOnXQw3kIUDhVuS/npc_Gnoll_Carnage_zbLiA7cPHhdpkhYx.json
  src/packs/monsters/Gnoll_6ZOnXQw3kIUDhVuS/npc_Gnoll_Chainflail_Woh5sK0JwN1uuG0E.json
  src/packs/monsters/Gnoll_6ZOnXQw3kIUDhVuS/npc_Gnoll_Mage_Mauler_y7up2vlFSplqKGN4.json
  src/packs/monsters/Gnoll_6ZOnXQw3kIUDhVuS/npc_Gnoll_Marauder_NWOCoxzsguUP85Bk.json
  src/packs/monsters/Gnoll_6ZOnXQw3kIUDhVuS/npc_Gnoll_Wildling_Kc2sZy0gSk44lX4N.json
  src/packs/monsters/Gnoll_6ZOnXQw3kIUDhVuS/npc_Tusker_Demon_MRvZrfVxA5VuDAIF.json
  src/packs/monsters/folders_Gnoll_6ZOnXQw3kIUDhVuS.json
Labels: compendium

#1021 Chimera Monster and Malice Features
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Chimera_Malice_nei486z2dWBGSLAG/ability_Ashen_Clouds_Y7eAtEZGOYntkMPj.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Chimera_Malice_nei486z2dWBGSLAG/ability_Defensive_Snapping_jhy5xQpdYGPY6XGW.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Chimera_Malice_nei486z2dWBGSLAG/ability_Solo_Action_nCvk3rGMu3QeORfy.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Chimera_Malice_nei486z2dWBGSLAG/ability_Unstable_Terrain_p5r68km6xWRy05C6.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/folders_Chimera_Malice_nei486z2dWBGSLAG.json
  src/packs/monsters/Chimera_kgEKDnLbyyQ3RtLK/npc_Chimera_yMkWRu1AYXU4ukn1.json
  src/packs/monsters/folders_Chimera_kgEKDnLbyyQ3RtLK.json
Labels: compendium

#1025 High Elves monsters and malice features
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Elves__High_Malice_OxTqWEvFfbywX7Mb/ability_Chaincast_QOHebOCHFr6tglBw.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Elves__High_Malice_OxTqWEvFfbywX7Mb/ability_Gift_From_an_Accursed_Tome_vvjYHjxFdP4qKoFR.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Elves__High_Malice_OxTqWEvFfbywX7Mb/ability_In_Defiance_of_Time_oILvREyZahTmzq10.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/folders_Elves__High_Malice_OxTqWEvFfbywX7Mb.json
  src/packs/monsters/Elves__High_Dj36vXEyn9vry4NO/npc_Brambleguard_27zPkjxDlEJYgfDi.json
  src/packs/monsters/Elves__High_Dj36vXEyn9vry4NO/npc_Ceramic_Horse_yfV2i9ze6UxOhIeu.json
  src/packs/monsters/Elves__High_Dj36vXEyn9vry4NO/npc_Elemental_Mote_yYTmi4JwOnyA0w1s.json
  src/packs/monsters/Elves__High_Dj36vXEyn9vry4NO/npc_High_Elf_Bloodletter_SOI6moopt7T3E9m3.json
  src/packs/monsters/Elves__High_Dj36vXEyn9vry4NO/npc_High_Elf_Dawn_Mage_bwvpJYeEjwKRG0kx.json
  src/packs/monsters/Elves__High_Dj36vXEyn9vry4NO/npc_High_Elf_Deathtouch_eyTHq6aYy6kKRuwr.json
  src/packs/monsters/Elves__High_Dj36vXEyn9vry4NO/npc_High_Elf_Orbweaver_b2rJVHgioMG34egl.json
  src/packs/monsters/Elves__High_Dj36vXEyn9vry4NO/npc_High_Elf_Ordinator_GMlN5QMe8ETbrF7p.json
  src/packs/monsters/Elves__High_Dj36vXEyn9vry4NO/npc_High_Elf_Palinode_UxoLvIdRzgdLOAY0.json
  src/packs/monsters/Elves__High_Dj36vXEyn9vry4NO/npc_High_Elf_Quiver_Wwp3YDZcu2BFkqSl.json
  src/packs/monsters/Elves__High_Dj36vXEyn9vry4NO/npc_High_Elf_Wyrd_rjQGZMW9Bif2TbbL.json
  src/packs/monsters/Elves__High_Dj36vXEyn9vry4NO/npc_High_Elf_Zephyr_bA6Nv7tqSLXReEZi.json
  src/packs/monsters/Elves__High_Dj36vXEyn9vry4NO/npc_Soot_Crow_a44HNNYHX0iwwarq.json
  src/packs/monsters/folders_Elves__High_Dj36vXEyn9vry4NO.json
Labels: compendium

#1085 [#1078] Correct Wodewalker benefit AE key
  src/packs/character-options/Complications_luKqW8QDTBJo5AM4/complication_Wodewalker_krC6L1GE2x0iZEJo.json
Labels: compendium

#1084 Fix Beggar career granting all interpersonal skills
  CHANGELOG.md
  src/packs/origins/Backgrounds_g8icN9n7dCBGOsej/Careers_DNgMG9rHu4ULguZr/career_Beggar_r3b55XTVHZI9dqTB.json
Labels: compendium

#1041 Lightbender Monsters and Malice Features
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Lightbender_Malice_1GwPdwwEnwK1qHBK/ability_Duplicate_AlsDN23DClpcInbD.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Lightbender_Malice_1GwPdwwEnwK1qHBK/ability_Everything_the_Light_Touches_k45wmUB9jfgYtiX0.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Lightbender_Malice_1GwPdwwEnwK1qHBK/ability_Silent_Prow_SVIMi6MPKsgt966w.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/folders_Lightbender_Malice_1GwPdwwEnwK1qHBK.json
  src/packs/monsters/Lightbender_nnQsDoBty46nEVFU/npc_Lightbender_Pouncer_nbbnCsLdqvFr4NIr.json
  src/packs/monsters/Lightbender_nnQsDoBty46nEVFU/npc_Lightbender_XucGqdcsBppnBCLq.json
  src/packs/monsters/folders_Lightbender_nnQsDoBty46nEVFU.json
Labels: compendium

#1044 Time Raiders Monsters and Malice Features
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Time_Raider_Malice_LoZnNuHgZjaAO7Gt/ability_Gravity_Well_DWLBSTbhAO4dJSvg.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Time_Raider_Malice_LoZnNuHgZjaAO7Gt/ability_Psi_Cage_ELtwiIpyMZafdAEM.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Time_Raider_Malice_LoZnNuHgZjaAO7Gt/ability_Recall_Module_2rKjwi2thIVeeFZf.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/folders_Time_Raider_Malice_LoZnNuHgZjaAO7Gt.json
  src/packs/monsters/Time_Raider_9g4m05r5B3CZpEms/npc_Time_Raider_Archon_77lNsdTkalkPbwlS.json
  src/packs/monsters/Time_Raider_9g4m05r5B3CZpEms/npc_Time_Raider_Armiger_a9jPmlDEtQV3Ilof.json
  src/packs/monsters/Time_Raider_9g4m05r5B3CZpEms/npc_Time_Raider_Cannonfall_QK220xei6VbKwMdS.json
  src/packs/monsters/Time_Raider_9g4m05r5B3CZpEms/npc_Time_Raider_Helix_krjUOITR6uvFfyVz.json
  src/packs/monsters/Time_Raider_9g4m05r5B3CZpEms/npc_Time_Raider_Hijack_HTTWLDPRm5hcquM5.json
  src/packs/monsters/Time_Raider_9g4m05r5B3CZpEms/npc_Time_Raider_Mind_Punk_VoI6hS00REXALNBw.json
  src/packs/monsters/Time_Raider_9g4m05r5B3CZpEms/npc_Time_Raider_Myriad_pU91Jsq2kqf4Dino.json
  src/packs/monsters/Time_Raider_9g4m05r5B3CZpEms/npc_Time_Raider_Nemesis_mw33S1pehccuDhxF.json
  src/packs/monsters/Time_Raider_9g4m05r5B3CZpEms/npc_Time_Raider_Tyrannis_mTkZYmsNyoV0ihlR.json
  src/packs/monsters/Time_Raider_9g4m05r5B3CZpEms/npc_Time_Raider_Vertex_1oOzxD3GIL79fY8l.json
  src/packs/monsters/folders_Time_Raider_9g4m05r5B3CZpEms.json
Labels: compendium

#1046 War Dogs 1st Echelon monsters and malice features
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/War_Dogs_Malice_o4Uo3fAWM49tvXdA/Level_1__zKtLcYoIeEal58CU/ability_Fire_for_Effect_qcpbsqefhcNsWcZd.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/War_Dogs_Malice_o4Uo3fAWM49tvXdA/Level_1__zKtLcYoIeEal58CU/ability_Fodder_Run_I47ueLHjVHGTY83Y.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/War_Dogs_Malice_o4Uo3fAWM49tvXdA/Level_1__zKtLcYoIeEal58CU/ability_Reconstitute_ihKkMlptBoQemUBc.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/War_Dogs_Malice_o4Uo3fAWM49tvXdA/folders_Level_1__zKtLcYoIeEal58CU.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/folders_War_Dogs_Malice_o4Uo3fAWM49tvXdA.json
  src/packs/monsters/War_Dogs_RKA1vCuIIGKGpRsZ/War_Dogs___1st_Echelon_DYl6Qljp14rd7e7s/npc_War_Dog_Amalgamite_pGCtSYaNWIm3Y34L.json
  src/packs/monsters/War_Dogs_RKA1vCuIIGKGpRsZ/War_Dogs___1st_Echelon_DYl6Qljp14rd7e7s/npc_War_Dog_Commando_9MiuXFcZ5VQYbqKz.json
  src/packs/monsters/War_Dogs_RKA1vCuIIGKGpRsZ/War_Dogs___1st_Echelon_DYl6Qljp14rd7e7s/npc_War_Dog_Conscript_vbinl6G2ypCaRjSh.json
  src/packs/monsters/War_Dogs_RKA1vCuIIGKGpRsZ/War_Dogs___1st_Echelon_DYl6Qljp14rd7e7s/npc_War_Dog_Crucibite_Ea3lpqgtaFP3vqny.json
  src/packs/monsters/War_Dogs_RKA1vCuIIGKGpRsZ/War_Dogs___1st_Echelon_DYl6Qljp14rd7e7s/npc_War_Dog_Eviscerite_nBEAm8zwmdl21L7x.json
  src/packs/monsters/War_Dogs_RKA1vCuIIGKGpRsZ/War_Dogs___1st_Echelon_DYl6Qljp14rd7e7s/npc_War_Dog_Ground_Commander_Y2m150vDEZJprWgF.json
  src/packs/monsters/War_Dogs_RKA1vCuIIGKGpRsZ/War_Dogs___1st_Echelon_DYl6Qljp14rd7e7s/npc_War_Dog_Neuronite_mxmtKA1s4exOuZbS.json
  src/packs/monsters/War_Dogs_RKA1vCuIIGKGpRsZ/War_Dogs___1st_Echelon_DYl6Qljp14rd7e7s/npc_War_Dog_Pestilite_MP2Ev6fcBPIStnEL.json
  src/packs/monsters/War_Dogs_RKA1vCuIIGKGpRsZ/War_Dogs___1st_Echelon_DYl6Qljp14rd7e7s/npc_War_Dog_Phosphorite_kZiETCGT2OHBcd5a.json
  src/packs/monsters/War_Dogs_RKA1vCuIIGKGpRsZ/War_Dogs___1st_Echelon_DYl6Qljp14rd7e7s/npc_War_Dog_Sharpshooter_HrovSrIU6dYZaTYS.json
  src/packs/monsters/War_Dogs_RKA1vCuIIGKGpRsZ/War_Dogs___1st_Echelon_DYl6Qljp14rd7e7s/npc_War_Dog_Subcommander_VkQVkyhM4k3WoLKh.json
  src/packs/monsters/War_Dogs_RKA1vCuIIGKGpRsZ/War_Dogs___1st_Echelon_DYl6Qljp14rd7e7s/npc_War_Dog_Teletalite_PcJcUvof9jZgqyIJ.json
  src/packs/monsters/War_Dogs_RKA1vCuIIGKGpRsZ/War_Dogs___1st_Echelon_DYl6Qljp14rd7e7s/npc_War_Dog_Tetherite_1UwUQqkYXpUhxwK5.json
  src/packs/monsters/War_Dogs_RKA1vCuIIGKGpRsZ/folders_War_Dogs___1st_Echelon_DYl6Qljp14rd7e7s.json
  src/packs/monsters/folders_War_Dogs_RKA1vCuIIGKGpRsZ.json
Labels: compendium

#1074 Animals Compendium and Features
  src/packs/monster-features/Animal_Traits_QDpGXDDyQUqaWzoW/Defensive_Traits_lV3iHQnRnRYfKaQW/ability_Fearsome_jaVl2pgbyE7qkrPg.json
  src/packs/monster-features/Animal_Traits_QDpGXDDyQUqaWzoW/Defensive_Traits_lV3iHQnRnRYfKaQW/ability_Withdraw_C61xMoriwBhBQome.json
  src/packs/monster-features/Animal_Traits_QDpGXDDyQUqaWzoW/Defensive_Traits_lV3iHQnRnRYfKaQW/feature_Camouflage_t0n0WXlh3WSuov3Y.json
  src/packs/monster-features/Animal_Traits_QDpGXDDyQUqaWzoW/Defensive_Traits_lV3iHQnRnRYfKaQW/feature_Pack_xyq4Ye9i4FoW29Iu.json
  src/packs/monster-features/Animal_Traits_QDpGXDDyQUqaWzoW/Defensive_Traits_lV3iHQnRnRYfKaQW/feature_Plated_nlHIhzlInEfWY3TD.json
  src/packs/monster-features/Animal_Traits_QDpGXDDyQUqaWzoW/Defensive_Traits_lV3iHQnRnRYfKaQW/feature_Spiny_RGUjtCpgyJ8HddqW.json
  src/packs/monster-features/Animal_Traits_QDpGXDDyQUqaWzoW/Defensive_Traits_lV3iHQnRnRYfKaQW/feature_Stench_r8nTOGcJoRq6rIHw.json
  src/packs/monster-features/Animal_Traits_QDpGXDDyQUqaWzoW/Defensive_Traits_lV3iHQnRnRYfKaQW/feature_Thick_Hide_37eK5BpXxfpN68dO.json
  src/packs/monster-features/Animal_Traits_QDpGXDDyQUqaWzoW/Defensive_Traits_lV3iHQnRnRYfKaQW/feature_Unrelenting_vwjklGksaMLW4gtG.json
  src/packs/monster-features/Animal_Traits_QDpGXDDyQUqaWzoW/Defensive_Traits_lV3iHQnRnRYfKaQW/feature_Wiggly_SsAlncbSEAFsg75Y.json
  src/packs/monster-features/Animal_Traits_QDpGXDDyQUqaWzoW/Mobility_Traits_8C9HKuMhqdHsaUPC/feature_Burrowing_dBW9ohPXopEAukat.json
  src/packs/monster-features/Animal_Traits_QDpGXDDyQUqaWzoW/Mobility_Traits_8C9HKuMhqdHsaUPC/feature_Climbing_DfDAXBRa0gKd2sVp.json
  src/packs/monster-features/Animal_Traits_QDpGXDDyQUqaWzoW/Mobility_Traits_8C9HKuMhqdHsaUPC/feature_Flight_BdaNlVPdU2oAAG0a.json
  src/packs/monster-features/Animal_Traits_QDpGXDDyQUqaWzoW/Mobility_Traits_8C9HKuMhqdHsaUPC/feature_Leaping_I2LLFD1gSj7bn7mL.json
  src/packs/monster-features/Animal_Traits_QDpGXDDyQUqaWzoW/Mobility_Traits_8C9HKuMhqdHsaUPC/feature_Slinking_p6OwzD3uLLmPnDwl.json
  src/packs/monster-features/Animal_Traits_QDpGXDDyQUqaWzoW/Mobility_Traits_8C9HKuMhqdHsaUPC/feature_Swiftness_nyfJHxbxpRJ18ALn.json
  src/packs/monster-features/Animal_Traits_QDpGXDDyQUqaWzoW/Mobility_Traits_8C9HKuMhqdHsaUPC/feature_Swimming_2cXHhv7m2clXruVt.json
  src/packs/monster-features/Animal_Traits_QDpGXDDyQUqaWzoW/Offensive_Traits_K75UICHTkqXPjfGw/ability_Pouncer_97h1az6jQddkUv1g.json
  src/packs/monster-features/Animal_Traits_QDpGXDDyQUqaWzoW/Offensive_Traits_K75UICHTkqXPjfGw/ability_Web_Rpgn7MLEkiKdFRRw.json
  src/packs/monster-features/Animal_Traits_QDpGXDDyQUqaWzoW/Offensive_Traits_K75UICHTkqXPjfGw/feature_Charger_VacxyAzDw9KOuNzm.json
  src/packs/monster-features/Animal_Traits_QDpGXDDyQUqaWzoW/Offensive_Traits_K75UICHTkqXPjfGw/feature_Frenzy_VxUn2bJkF762o6Pd.json
  src/packs/monster-features/Animal_Traits_QDpGXDDyQUqaWzoW/Offensive_Traits_K75UICHTkqXPjfGw/feature_Grappler_zACgstLX8HRiUK4M.json
  src/packs/monster-features/Animal_Traits_QDpGXDDyQUqaWzoW/Offensive_Traits_K75UICHTkqXPjfGw/feature_Hunter_0FL1xI3C1ZISjDNZ.json
  src/packs/monster-features/Animal_Traits_QDpGXDDyQUqaWzoW/Offensive_Traits_K75UICHTkqXPjfGw/feature_Multilimb_uTzQP4VYpWLNi5nu.json
  src/packs/monster-features/Animal_Traits_QDpGXDDyQUqaWzoW/Offensive_Traits_K75UICHTkqXPjfGw/feature_Power_V3N0X3AnpFZVnJxG.json
  src/packs/monster-features/Animal_Traits_QDpGXDDyQUqaWzoW/Offensive_Traits_K75UICHTkqXPjfGw/feature_Projectile_frwNYQEs4mg8vHgS.json
  src/packs/monster-features/Animal_Traits_QDpGXDDyQUqaWzoW/Offensive_Traits_K75UICHTkqXPjfGw/feature_Reach_ogA5U4AnO2D3076K.json
  src/packs/monster-features/Animal_Traits_QDpGXDDyQUqaWzoW/Offensive_Traits_K75UICHTkqXPjfGw/feature_Venom_Pg9ocoQ65x9GE2W9.json
  src/packs/monster-features/Animal_Traits_QDpGXDDyQUqaWzoW/Supernatural_Traits_y82tzOi2Jyl31NrN/feature_Death_Fumes_vQt9QdycRwgljttZ.json
  src/packs/monster-features/Animal_Traits_QDpGXDDyQUqaWzoW/Supernatural_Traits_y82tzOi2Jyl31NrN/feature_Elemental_V5tof4jroyEA7rED.json
  src/packs/monster-features/Animal_Traits_QDpGXDDyQUqaWzoW/Supernatural_Traits_y82tzOi2Jyl31NrN/feature_Gelatinous_gyEPxtLvnwIbpGPG.json
  src/packs/monster-features/Animal_Traits_QDpGXDDyQUqaWzoW/Supernatural_Traits_y82tzOi2Jyl31NrN/feature_Hypnosis_OadGwSzckuBddktO.json
  src/packs/monster-features/Animal_Traits_QDpGXDDyQUqaWzoW/Supernatural_Traits_y82tzOi2Jyl31NrN/feature_Imposer_8YqnoTDMkNGHoRdL.json
  src/packs/monster-features/Animal_Traits_QDpGXDDyQUqaWzoW/Supernatural_Traits_y82tzOi2Jyl31NrN/feature_Pass_Through_avjsABIs9QWNR1GF.json
  src/packs/monster-features/Animal_Traits_QDpGXDDyQUqaWzoW/Supernatural_Traits_y82tzOi2Jyl31NrN/feature_Translation_JjB5VvXFs0nrfb0S.json
  src/packs/monster-features/Animal_Traits_QDpGXDDyQUqaWzoW/folders_Defensive_Traits_lV3iHQnRnRYfKaQW.json
  src/packs/monster-features/Animal_Traits_QDpGXDDyQUqaWzoW/folders_Mobility_Traits_8C9HKuMhqdHsaUPC.json
  src/packs/monster-features/Animal_Traits_QDpGXDDyQUqaWzoW/folders_Offensive_Traits_K75UICHTkqXPjfGw.json
  src/packs/monster-features/Animal_Traits_QDpGXDDyQUqaWzoW/folders_Supernatural_Traits_y82tzOi2Jyl31NrN.json
  src/packs/monster-features/folders_Animal_Traits_QDpGXDDyQUqaWzoW.json
  src/packs/monsters/Animal_OygqHojAVhOF59fl/npc_Animal_G3wVCAmEi7MwsOW3.json
  src/packs/monsters/Animal_OygqHojAVhOF59fl/npc_Animal_Swarm_8hyc2xbJy825dRTZ.json
  src/packs/monsters/Animal_OygqHojAVhOF59fl/npc_Big_Animal_A_UBTaAFYnIGKvvAOj.json
  src/packs/monsters/Animal_OygqHojAVhOF59fl/npc_Big_Animal_B_OkRrwcUUPTtqBF25.json
  src/packs/monsters/Animal_OygqHojAVhOF59fl/npc_Predator_A_XXEwAvRCXvey9KVr.json
  src/packs/monsters/Animal_OygqHojAVhOF59fl/npc_Predator_B_Y2AAe1rDENo3rDzo.json
Labels: compendium

#1090 #780 - Quick Fixes for two E1 Titles
  src/packs/rewards/Titles_NPrextZBfLXyWrwH/1st_Echelon_M0xNtYu0IzR83TAL/Grants_boCFMPsgL0Py8wzo/feature_Deep_Sea_Diver_pBygpYvbzBFDs263.json
  src/packs/rewards/Titles_NPrextZBfLXyWrwH/1st_Echelon_M0xNtYu0IzR83TAL/title_Doomed_5k9wFhlhSZ8UsAs2.json
Labels: compendium

#1091 [#1087] Remove invalid roles from leader and solo monsters and harden template against missing roles/organizations
  CHANGELOG.md
  src/packs/monsters/Ashen_Hoarder_GXX2DnZcth3KWFfL/npc_Ashen_Hoarder_EwN0CLt7UmEzQA0J.json
  src/packs/monsters/Bredbeddle_O7zizfGvMA07rRKX/npc_Bredbeddle_wzvNh7FYggjoU6Hv.json
  src/packs/monsters/Bredbeddle_O7zizfGvMA07rRKX/npc_Phantom_Bredbeddle_gYUnLS5eDPZZtcGA.json
  src/packs/monsters/Chimera_kgEKDnLbyyQ3RtLK/npc_Chimera_yMkWRu1AYXU4ukn1.json
  src/packs/monsters/Demons_PimL3ExIxSjDqzsY/Demons___1st_Echelon_6DKl8v5ROTdmTFsZ/npc_Chorogaunt_GqufFfTfLOy6sHxx.json
  src/packs/monsters/Dragons_1xAB7dzxBYqdc7qX/npc_Thorn_Dragon_s8Dvj26hssemdUrw.json
  src/packs/monsters/Dwarves_aym4mi5JvyLiP0uV/npc_Dwarf_Marauder_STHK2rkTd1XJ0og0.json
  src/packs/monsters/Elves__Wode_Ji95GDWQ7qRIum3n/npc_Wode_Elf_Warleader_yPvu9Qwb9zl29eFZ.json
  src/packs/monsters/Fossil_Cryptic_1HvjuVmZEBELv9LR/npc_Fossil_Cryptic_GrwkywAeRHqyGAiu.json
  src/packs/monsters/Gloom_Dragon_gsy78qjGN57mu5so/npc_Gloom_Dragon_awNlSowdCYs0igx0.json
  src/packs/monsters/Gnoll_6ZOnXQw3kIUDhVuS/npc_Gnoll_Carnage_zbLiA7cPHhdpkhYx.json
  src/packs/monsters/Hag_Xlv2aLypC87MCZAS/npc_Wode_Hag_FTLYZPKo0ZIJ0n5q.json
  src/packs/monsters/Lizardfolk_SUuKqERiLGfeX4ZI/npc_Lizardfolk_Deathrex_Shedded_Skin_zkHAnfXdQmEJ7sXQ.json
  src/packs/monsters/Lizardfolk_SUuKqERiLGfeX4ZI/npc_Lizardfolk_Deathrex_cmB79a1nLuwimt3P.json
  src/packs/monsters/Manticore_GjGhUOD7nBaOg0ca/npc_Manticore_8DT1J2OmO380DsYt.json
  src/packs/monsters/Time_Raider_9g4m05r5B3CZpEms/npc_Time_Raider_Tyrannis_mTkZYmsNyoV0ihlR.json
  src/packs/monsters/War_Dogs_RKA1vCuIIGKGpRsZ/War_Dogs___1st_Echelon_DYl6Qljp14rd7e7s/npc_War_Dog_Ground_Commander_Y2m150vDEZJprWgF.json
  templates/sheets/actor/npc/header.hbs
Labels: compendium, UI/UX

#1094 [#1081] Blank tier display improvements
  CHANGELOG.md
  src/module/data/item/ability.mjs
  src/module/data/message/ability-use.mjs
  src/module/data/pseudo-documents/power-roll-effects/damage-effect.mjs
Labels: UI/UX

#1097 #761 - Dwarf Ancestry Update
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Dwarf_Dc3tgD6gCZDA5Ysd/Features_dMTmeM8PrGfzX0Ur/ancestryTrait_Grounded_SRXimbhqaB29laQU.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Dwarf_Dc3tgD6gCZDA5Ysd/Features_dMTmeM8PrGfzX0Ur/ancestryTrait_Spark_Off_Your_Skin_cUb18dpzvSq6VCyL.json
Labels: compendium

#1096 #771 Sacrificial Offer Effect
  src/packs/abilities/Conduit_5y6vuu4yT5kdzSLd/Level_1_Xal7kAbgEk4Qp8Kr/Signature_tv6gR5r1UgtqsrGO/ability_Sacrificial_Offer_BRkOBjM04NYOikPL.json
Labels: compendium

#1102 #771 Ray of Wrath Damage fix
  CHANGELOG.md
  src/packs/abilities/Conduit_5y6vuu4yT5kdzSLd/Core_JJpf8PudWJzeuRVe/ability_Ray_of_Wrath_4r6uYuaEgmiGsdCf.json
Labels: compendium

#1118 Simple docs update
  README.md
  src/docs/Frequently-Asked-Questions.md
  src/docs/Home.md
Labels: documentation

#1072 Overhauled equipment keywords
  CHANGELOG.md
  lang/en.json
  src/module/config.mjs
  src/module/data/item/treasure.mjs
Labels: config

#1109 Implemented docs on updating CONFIG.DRAW_STEEL
  CHANGELOG.md
  src/docs/CONFIG-Modifications.md
  src/docs/Home.md
  src/module/applications/sheets/actor-sheet.mjs
  src/module/applications/sheets/hero-sheet.mjs
  src/module/applications/sheets/pseudo-documents/advancement-sheet.mjs
  templates/sheets/actor/hero-sheet/stats.hbs
Labels: documentation

#965 [#841] Source Datalists
  CHANGELOG.md
  draw-steel.mjs
  lang/en.json
  src/module/applications/apps/document-source-input.mjs
  src/module/config.mjs
  src/module/data/actor/npc.mjs
  src/module/data/item/base.mjs
  src/module/data/models/_types.d.ts
  src/module/data/models/source.mjs
  templates/apps/document-input/document-source-input.hbs
Labels: apps, config

#1116 [#626] Refactor embed toggling
  CHANGELOG.md
  src/module/applications/api/document-sheet-mixin.mjs
  src/module/applications/sheets/actor-sheet.mjs
  src/module/applications/sheets/item-sheet.mjs
  src/styles/system/applications/components/effects.css
  src/styles/system/applications/components/items.css
  templates/sheets/actor/hero-sheet/equipment.hbs
  templates/sheets/actor/hero-sheet/features.hbs
  templates/sheets/actor/hero-sheet/header.hbs
  templates/sheets/actor/hero-sheet/projects.hbs
  templates/sheets/actor/shared/abilities.hbs
  templates/sheets/actor/shared/effects.hbs
  templates/sheets/actor/shared/partials/features/features.hbs
  templates/sheets/item/effects.hbs
Labels: apps, UI/UX

#1139 Implement custom effect for "WarpPerceptions" rider. (#1104)
  CHANGELOG.md
  src/packs/monsters/Demons_PimL3ExIxSjDqzsY/Demons___1st_Echelon_6DKl8v5ROTdmTFsZ/npc_Bendrak_E3cI02r1zBQaBr1i.json
Labels: compendium

#1143 Correct Talent's Choke ability missing potency characteristic for the slowed/restrained effect.
  CHANGELOG.md
  src/packs/abilities/Talent_W4G9rOoBWQqffx2T/Level_1_OwLGXyW6518i4S2O/3_Clarity_DDQszc7f2JZLgbRD/ability_Choke_5B3qFN4oAdjGzMFs.json
Labels: compendium

#1152 Fix typo in "Acolyte of Fire" effect
  CHANGELOG.md
  src/packs/classes/Elementalist_SVgKuVoWB0FrXkal/Features_JwIyKm3943QCjSQQ/Fire_gWcqrI8cFJGHNpit/feature_Acolyte_of_Fire_M6BXDQml9cHpYFgP.json
Labels: compendium

#1154 [#1147] Add move action type and default move actions
  lang/en.json
  src/module/config.mjs
  src/packs/abilities/Basic_Abilities_YKzQ5cCX8knW8fAc/ability_Advance_ucR2C7lMvXrKIMZ7.json
  src/packs/abilities/Basic_Abilities_YKzQ5cCX8knW8fAc/ability_Disengage_vBlTvHRZ5JBXWYt6.json
  src/packs/abilities/Basic_Abilities_YKzQ5cCX8knW8fAc/ability_Ride_QXOkflcYF6DITJE3.json
Labels: config

#1148 Followup HTML Cleanup
  src/module/applications/api/document-sheet-mixin.mjs
  src/module/applications/sheets/actor-sheet.mjs
  templates/sheets/actor/hero-sheet/equipment.hbs
  templates/sheets/actor/hero-sheet/features.hbs
  templates/sheets/actor/hero-sheet/header.hbs
  templates/sheets/actor/hero-sheet/projects.hbs
  templates/sheets/actor/shared/abilities.hbs
  templates/sheets/actor/shared/effects.hbs
  templates/sheets/actor/shared/partials/features/features.hbs
  templates/sheets/item/effects.hbs
Labels: apps

#1176 Implemented updates to issue templates
  .github/ISSUE_TEMPLATE/1-compendium-data.yml
  .github/ISSUE_TEMPLATE/2-bug-report.yml
  .github/ISSUE_TEMPLATE/3-feature-request.yml
Labels: tech debt

#1178 [#1173] Corrected roles for Grulqin, Orliq, and Wobalas
  CHANGELOG.md
  src/packs/monsters/Demons_PimL3ExIxSjDqzsY/Demons___2nd_Echelon_fgQNWiICJVzfSdZ8/npc_Grulqin_WwVzCeCSmWxzavYt.json
  src/packs/monsters/Demons_PimL3ExIxSjDqzsY/Demons___2nd_Echelon_fgQNWiICJVzfSdZ8/npc_Lumbering_Egress_PgfTJjJwE66nvFkA.json
  src/packs/monsters/Demons_PimL3ExIxSjDqzsY/Demons___2nd_Echelon_fgQNWiICJVzfSdZ8/npc_Orliq_tE6gzFGlFDdSV0nT.json
  src/packs/monsters/Demons_PimL3ExIxSjDqzsY/Demons___2nd_Echelon_fgQNWiICJVzfSdZ8/npc_Wobalas_FlhenZoGvBLM5GOu.json
  src/packs/monsters/Elves__High_Dj36vXEyn9vry4NO/npc_High_Elf_Ordinator_GMlN5QMe8ETbrF7p.json
Labels: compendium

#1180 Correction for #1178
  src/packs/monsters/Demons_PimL3ExIxSjDqzsY/Demons___2nd_Echelon_fgQNWiICJVzfSdZ8/npc_Orliq_tE6gzFGlFDdSV0nT.json
  src/packs/monsters/Demons_PimL3ExIxSjDqzsY/Demons___2nd_Echelon_fgQNWiICJVzfSdZ8/npc_Wobalas_FlhenZoGvBLM5GOu.json
Labels: compendium

#1185 Tactician Fixes for 1st Echelon
  CHANGELOG.md
  src/packs/abilities/Tactician_If39E6GsmUaOGSIx/Level_1_X6NCcq2MeD0PO9m7/5_Focus_qqy4D1GA6B5jsNJH/ability_Hammer_And_Anvil_lNJCFKdUV1fjYmhC.json
  src/packs/abilities/Tactician_If39E6GsmUaOGSIx/Level_1_X6NCcq2MeD0PO9m7/5_Focus_qqy4D1GA6B5jsNJH/ability_Now__tpi0fKQDK1dEDwWw.json
  src/packs/abilities/Tactician_If39E6GsmUaOGSIx/Level_1_X6NCcq2MeD0PO9m7/5_Focus_qqy4D1GA6B5jsNJH/ability_The_Mind_Game_qHiPuCKH4WNHCYgO.json
  src/packs/abilities/Tactician_If39E6GsmUaOGSIx/Level_2_V8sovzcihb87srSY/Mastermind_Xyfx7wKsdZmJloDI/ability_Targets_of_Opportunity_zLKvoysqHElI2q54.json
  src/packs/abilities/Tactician_If39E6GsmUaOGSIx/Level_2_V8sovzcihb87srSY/Vanguard_cFVtfkYEyx9FXpdn/ability_No_Dying_On_My_Watch_ZtMBjvDFJQYVkdmt.json
  src/packs/abilities/Tactician_If39E6GsmUaOGSIx/Level_2_V8sovzcihb87srSY/Vanguard_cFVtfkYEyx9FXpdn/ability_Squad__On_Me__kT1PdUuDnWdd8E5j.json
  src/packs/abilities/Tactician_If39E6GsmUaOGSIx/Triggered_GyUC1qQdNz5Ia8zm/Insurgent_G3UBn4UI2HQ6Kdom/ability_Advanced_Tactics_Ww4AaolCBsUJMeDA.json
  src/packs/abilities/Tactician_If39E6GsmUaOGSIx/Triggered_GyUC1qQdNz5Ia8zm/Vanguard_VhYOjPek7vcYHAgA/ability_Parry_NSOHEMtSDSy8qwIh.json
Labels: compendium

#1181 Goblin and Undead fixes
  CHANGELOG.md
  src/packs/monsters/Goblins_iEPVvWezLlidfEbg/npc_Goblin_Monarch_Vxxc0EcLHPPnpSbK.json
  src/packs/monsters/Goblins_iEPVvWezLlidfEbg/npc_Goblin_Runner_Xw0gZCS09gdMjaw8.json
  src/packs/monsters/Goblins_iEPVvWezLlidfEbg/npc_Goblin_Sniper_E637uEMv0INA5LPW.json
  src/packs/monsters/Goblins_iEPVvWezLlidfEbg/npc_Goblin_Spinecleaver_Mdk2jvvw26BaR1HL.json
  src/packs/monsters/Goblins_iEPVvWezLlidfEbg/npc_Goblin_Stinker_CWcc0FNUfUaiYyH7.json
  src/packs/monsters/Goblins_iEPVvWezLlidfEbg/npc_Goblin_Underboss_RTBXFv1dj9NBfVRU.json
  src/packs/monsters/Goblins_iEPVvWezLlidfEbg/npc_Skitterling_CtnlwvEcJb9YdZQ3.json
  src/packs/monsters/Undead_Awroz7YqtpURNlF5/1st_Echelon_qZ8RbdImvXjWh2yn/npc_Crawling_Claw_V8CFcw8SAUNkcm7P.json
  src/packs/monsters/Undead_Awroz7YqtpURNlF5/1st_Echelon_qZ8RbdImvXjWh2yn/npc_Decrepit_Skeleton_HTNu9LRNpFYtB5G6.json
  src/packs/monsters/Undead_Awroz7YqtpURNlF5/1st_Echelon_qZ8RbdImvXjWh2yn/npc_Ghost_hCxrYde7uzidWWWp.json
  src/packs/monsters/Undead_Awroz7YqtpURNlF5/1st_Echelon_qZ8RbdImvXjWh2yn/npc_Rotting_Zombie_2KiVCGcov7SmCkWU.json
  src/packs/monsters/Undead_Awroz7YqtpURNlF5/1st_Echelon_qZ8RbdImvXjWh2yn/npc_Shade_6HlLZCuKCPy73OCb.json
  src/packs/monsters/Undead_Awroz7YqtpURNlF5/1st_Echelon_qZ8RbdImvXjWh2yn/npc_Skeleton_2h6PhbOuGeraFQZm.json
  src/packs/monsters/Undead_Awroz7YqtpURNlF5/1st_Echelon_qZ8RbdImvXjWh2yn/npc_Umbral_Stalker_vAz4ctYuex5Fk7W8.json
  src/packs/monsters/Undead_Awroz7YqtpURNlF5/1st_Echelon_qZ8RbdImvXjWh2yn/npc_Zombie_G7bFOGyqq0Z4xJ7F.json
  src/packs/monsters/folders_Goblins_iEPVvWezLlidfEbg.json
  src/packs/monsters/folders_Undead_Awroz7YqtpURNlF5.json
Labels: compendium

#1111 Demons 4th echelon monsters and malice features
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Demon_Malice_kPf6Qkt8yIAyQls0/Level_10__Malice_Features_nF331WOpAjOEwAp4/ability_Prior_Malice_Features_NVpvDaIfPAbl2K9h.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Demon_Malice_kPf6Qkt8yIAyQls0/Level_10__Malice_Features_nF331WOpAjOEwAp4/ability_Soul_Flense_4cNFyCxzxVSM7rml.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Demon_Malice_kPf6Qkt8yIAyQls0/folders_Level_10__Malice_Features_nF331WOpAjOEwAp4.json
  src/packs/monsters/Demons_PimL3ExIxSjDqzsY/Demons___3rd_Echelon_5gRevvAzCanqkRiw/npc_Blight_Phage_Qp5KnRoiAhrKqVgW.json
  src/packs/monsters/Demons_PimL3ExIxSjDqzsY/Demons___3rd_Echelon_5gRevvAzCanqkRiw/npc_Chimeron_f71DR96HvSWgIVcL.json
  src/packs/monsters/Demons_PimL3ExIxSjDqzsY/Demons___3rd_Echelon_5gRevvAzCanqkRiw/npc_Soulraker_Handmaiden_fm0xXQMgYtq7x7w3.json
  src/packs/monsters/Demons_PimL3ExIxSjDqzsY/Demons___3rd_Echelon_5gRevvAzCanqkRiw/npc_Soulraker_Hivequeen_edFfStb7ZgG1bBLW.json
  src/packs/monsters/Demons_PimL3ExIxSjDqzsY/Demons___3rd_Echelon_5gRevvAzCanqkRiw/npc_Soulraker_Praetorian_eP9lhXI3aPN1xrXD.json
  src/packs/monsters/Demons_PimL3ExIxSjDqzsY/Demons___3rd_Echelon_5gRevvAzCanqkRiw/npc_Soulraker_Scout_9q84XKVnHQ7xs4c8.json
  src/packs/monsters/Demons_PimL3ExIxSjDqzsY/Demons___3rd_Echelon_5gRevvAzCanqkRiw/npc_Soulraker_Soldier_aw2Grj27aslTlO5f.json
  src/packs/monsters/Demons_PimL3ExIxSjDqzsY/Demons___3rd_Echelon_5gRevvAzCanqkRiw/npc_Soulraker_Stinger_2RBxd4qewHIvQ37X.json
  src/packs/monsters/Demons_PimL3ExIxSjDqzsY/Demons___3rd_Echelon_5gRevvAzCanqkRiw/npc_Styrich_D4X2LnvtF3qN4tUR.json
  src/packs/monsters/Demons_PimL3ExIxSjDqzsY/Demons___4th_Echelon_YVkbVbuTCdEc4h7w/npc_Aurumvas_uUW2ZDtajs3eP9tX.json
  src/packs/monsters/Demons_PimL3ExIxSjDqzsY/Demons___4th_Echelon_YVkbVbuTCdEc4h7w/npc_Izyak_ZlldlcAUDqx39d5O.json
  src/packs/monsters/Demons_PimL3ExIxSjDqzsY/Demons___4th_Echelon_YVkbVbuTCdEc4h7w/npc_Optacus_robfmNuhaVjRoZDP.json
  src/packs/monsters/Demons_PimL3ExIxSjDqzsY/Demons___4th_Echelon_YVkbVbuTCdEc4h7w/npc_Tyburaki_fSHdcO4q12wV8qHx.json
  src/packs/monsters/Demons_PimL3ExIxSjDqzsY/Demons___4th_Echelon_YVkbVbuTCdEc4h7w/npc_Unguloid_i6Qy72aRK3ACgeht.json
  src/packs/monsters/Demons_PimL3ExIxSjDqzsY/Demons___4th_Echelon_YVkbVbuTCdEc4h7w/npc_Vicisitator_pEYRlKhRpOLCdklz.json
  src/packs/monsters/Demons_PimL3ExIxSjDqzsY/folders_Demons___3rd_Echelon_5gRevvAzCanqkRiw.json
  src/packs/monsters/Demons_PimL3ExIxSjDqzsY/folders_Demons___4th_Echelon_YVkbVbuTCdEc4h7w.json
Labels: compendium

#1115 Rivals 2nd, 3rd, and 4th Echelon
  CHANGELOG.md
  src/packs/monsters/Rivals_JYYzmjl4NO5qaYjj/Rivals___1st_Echelon_SFuvViqB8j9ZtHt6/npc_Rival_Conduit_EhnU9L0Aew7nM5aT.json
  src/packs/monsters/Rivals_JYYzmjl4NO5qaYjj/Rivals___1st_Echelon_SFuvViqB8j9ZtHt6/npc_Rival_Elementalist_hTF6vMqyzn5lkLDl.json
  src/packs/monsters/Rivals_JYYzmjl4NO5qaYjj/Rivals___1st_Echelon_SFuvViqB8j9ZtHt6/npc_Rival_Fury_ztua9qq0M4CRGTEb.json
  src/packs/monsters/Rivals_JYYzmjl4NO5qaYjj/Rivals___1st_Echelon_SFuvViqB8j9ZtHt6/npc_Rival_Null_aoWQpSc0poFyHs60.json
  src/packs/monsters/Rivals_JYYzmjl4NO5qaYjj/Rivals___1st_Echelon_SFuvViqB8j9ZtHt6/npc_Rival_Shadow_q7fB8aErCmLG2Lhc.json
  src/packs/monsters/Rivals_JYYzmjl4NO5qaYjj/Rivals___1st_Echelon_SFuvViqB8j9ZtHt6/npc_Rival_Tactician_6ipD4f10bXqtf0jn.json
  src/packs/monsters/Rivals_JYYzmjl4NO5qaYjj/Rivals___1st_Echelon_SFuvViqB8j9ZtHt6/npc_Rival_Talent_NNKEcoB39e1P5Rrq.json
  src/packs/monsters/Rivals_JYYzmjl4NO5qaYjj/Rivals___2nd_Echelon_lXKorAomovYFhg1y/npc_Rival_Conduit_IApL75Qnnb9j5Ais.json
  src/packs/monsters/Rivals_JYYzmjl4NO5qaYjj/Rivals___2nd_Echelon_lXKorAomovYFhg1y/npc_Rival_Elementalist_gLxHe0tvrgo8Jkrz.json
  src/packs/monsters/Rivals_JYYzmjl4NO5qaYjj/Rivals___2nd_Echelon_lXKorAomovYFhg1y/npc_Rival_Fury_deAwGmhoyUGutnAB.json
  src/packs/monsters/Rivals_JYYzmjl4NO5qaYjj/Rivals___2nd_Echelon_lXKorAomovYFhg1y/npc_Rival_Null_1FmKDKuNwDL7Rh8f.json
  src/packs/monsters/Rivals_JYYzmjl4NO5qaYjj/Rivals___2nd_Echelon_lXKorAomovYFhg1y/npc_Rival_Shadow_ZYA3u3MgtbR9FIzY.json
  src/packs/monsters/Rivals_JYYzmjl4NO5qaYjj/Rivals___2nd_Echelon_lXKorAomovYFhg1y/npc_Rival_Tactician_8ACMkPWWZoxwqF7N.json
  src/packs/monsters/Rivals_JYYzmjl4NO5qaYjj/Rivals___2nd_Echelon_lXKorAomovYFhg1y/npc_Rival_Talent_KtoxTWMsgRKbsOZt.json
  src/packs/monsters/Rivals_JYYzmjl4NO5qaYjj/Rivals___3rd_Echelon_SdbfdRr0j4jwl4uZ/npc_Rival_Conduit_bA28fo0tA4JKlwFe.json
  src/packs/monsters/Rivals_JYYzmjl4NO5qaYjj/Rivals___3rd_Echelon_SdbfdRr0j4jwl4uZ/npc_Rival_Elementalist_t6M5CBB5AYl3dPCU.json
  src/packs/monsters/Rivals_JYYzmjl4NO5qaYjj/Rivals___3rd_Echelon_SdbfdRr0j4jwl4uZ/npc_Rival_Fury_QcjDwycmeM6lS3sS.json
  src/packs/monsters/Rivals_JYYzmjl4NO5qaYjj/Rivals___3rd_Echelon_SdbfdRr0j4jwl4uZ/npc_Rival_Null_BPQW65AIYXfoV3kH.json
  src/packs/monsters/Rivals_JYYzmjl4NO5qaYjj/Rivals___3rd_Echelon_SdbfdRr0j4jwl4uZ/npc_Rival_Shadow_Ltel3z98gxYmG2oK.json
  src/packs/monsters/Rivals_JYYzmjl4NO5qaYjj/Rivals___3rd_Echelon_SdbfdRr0j4jwl4uZ/npc_Rival_Tactician_UueE6Yq1t8NGBqEM.json
  src/packs/monsters/Rivals_JYYzmjl4NO5qaYjj/Rivals___3rd_Echelon_SdbfdRr0j4jwl4uZ/npc_Rival_Talent_MbtLvdLq4mvvOche.json
  src/packs/monsters/Rivals_JYYzmjl4NO5qaYjj/Rivals___4th_Echelon_QvV3PMJrBzKpQAvG/npc_Rival_Conduit_7eljLMibLQSjJaIf.json
  src/packs/monsters/Rivals_JYYzmjl4NO5qaYjj/Rivals___4th_Echelon_QvV3PMJrBzKpQAvG/npc_Rival_Elementalist_NV6FhFDsQzAv4PGH.json
  src/packs/monsters/Rivals_JYYzmjl4NO5qaYjj/Rivals___4th_Echelon_QvV3PMJrBzKpQAvG/npc_Rival_Fury_6PnAB92xh5Nx2kqq.json
  src/packs/monsters/Rivals_JYYzmjl4NO5qaYjj/Rivals___4th_Echelon_QvV3PMJrBzKpQAvG/npc_Rival_Null_ZhoPS7098XzVQ6eH.json
  src/packs/monsters/Rivals_JYYzmjl4NO5qaYjj/Rivals___4th_Echelon_QvV3PMJrBzKpQAvG/npc_Rival_Shadow_gnbWCMqNZfFVOQK6.json
  src/packs/monsters/Rivals_JYYzmjl4NO5qaYjj/Rivals___4th_Echelon_QvV3PMJrBzKpQAvG/npc_Rival_Tactician_N6rMsl6br626IJ8j.json
  src/packs/monsters/Rivals_JYYzmjl4NO5qaYjj/Rivals___4th_Echelon_QvV3PMJrBzKpQAvG/npc_Rival_Talent_IYX2xdRpl3kxM763.json
  src/packs/monsters/Rivals_JYYzmjl4NO5qaYjj/folders_Rivals___1st_Echelon_SFuvViqB8j9ZtHt6.json
  src/packs/monsters/Rivals_JYYzmjl4NO5qaYjj/folders_Rivals___2nd_Echelon_lXKorAomovYFhg1y.json
  src/packs/monsters/Rivals_JYYzmjl4NO5qaYjj/folders_Rivals___3rd_Echelon_SdbfdRr0j4jwl4uZ.json
  src/packs/monsters/Rivals_JYYzmjl4NO5qaYjj/folders_Rivals___4th_Echelon_QvV3PMJrBzKpQAvG.json
Labels: compendium

#1117 Undead 2nd Echelon Monsters and Malice Features
  CHANGELOG.md
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Undead_Malice_dDubEbmnbWGRYlvn/Level_1__Malice_Features_7WVixhDzkxDEFvUq/ability_Dread_March_EzWvhVW1uXUmKhV5.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Undead_Malice_dDubEbmnbWGRYlvn/Level_1__Malice_Features_7WVixhDzkxDEFvUq/ability_Paranormal_Fling_da4wUZrJsfQ3EMZ3.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Undead_Malice_dDubEbmnbWGRYlvn/Level_1__Malice_Features_7WVixhDzkxDEFvUq/ability_Ravenous_Horde_gSoRE2jY58pVAtXf.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Undead_Malice_dDubEbmnbWGRYlvn/Level_1__Malice_Features_7WVixhDzkxDEFvUq/ability_The_Grasping__the_Hungry_5lQ9od53YUhk2eDw.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Undead_Malice_dDubEbmnbWGRYlvn/Level_4__Malice_Features_YZb6JUipWCfcksYj/ability_Blood_Hunger_g3I8pfaRJv4SU7k0.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Undead_Malice_dDubEbmnbWGRYlvn/Level_4__Malice_Features_YZb6JUipWCfcksYj/ability_Prior_Malice_Features_lql6HakCaCi05z5P.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Undead_Malice_dDubEbmnbWGRYlvn/folders_Level_1__Malice_Features_7WVixhDzkxDEFvUq.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Undead_Malice_dDubEbmnbWGRYlvn/folders_Level_4__Malice_Features_YZb6JUipWCfcksYj.json
  src/packs/monsters/Undead_Awroz7YqtpURNlF5/Undead___1st_Echelon_qZ8RbdImvXjWh2yn/npc_Crawling_Claw_V8CFcw8SAUNkcm7P.json
  src/packs/monsters/Undead_Awroz7YqtpURNlF5/Undead___1st_Echelon_qZ8RbdImvXjWh2yn/npc_Decrepit_Skeleton_HTNu9LRNpFYtB5G6.json
  src/packs/monsters/Undead_Awroz7YqtpURNlF5/Undead___1st_Echelon_qZ8RbdImvXjWh2yn/npc_Ghost_hCxrYde7uzidWWWp.json
  src/packs/monsters/Undead_Awroz7YqtpURNlF5/Undead___1st_Echelon_qZ8RbdImvXjWh2yn/npc_Ghoul_DXM53Md2acyvSVNo.json
  src/packs/monsters/Undead_Awroz7YqtpURNlF5/Undead___1st_Echelon_qZ8RbdImvXjWh2yn/npc_Rotting_Zombie_2KiVCGcov7SmCkWU.json
  src/packs/monsters/Undead_Awroz7YqtpURNlF5/Undead___1st_Echelon_qZ8RbdImvXjWh2yn/npc_Shade_6HlLZCuKCPy73OCb.json
  src/packs/monsters/Undead_Awroz7YqtpURNlF5/Undead___1st_Echelon_qZ8RbdImvXjWh2yn/npc_Skeleton_2h6PhbOuGeraFQZm.json
  src/packs/monsters/Undead_Awroz7YqtpURNlF5/Undead___1st_Echelon_qZ8RbdImvXjWh2yn/npc_Soulwight_NkO0TYxtdVNVRjYB.json
  src/packs/monsters/Undead_Awroz7YqtpURNlF5/Undead___1st_Echelon_qZ8RbdImvXjWh2yn/npc_Specter_4uRj8zIBAqukwmrN.json
  src/packs/monsters/Undead_Awroz7YqtpURNlF5/Undead___1st_Echelon_qZ8RbdImvXjWh2yn/npc_Umbral_Stalker_vAz4ctYuex5Fk7W8.json
  src/packs/monsters/Undead_Awroz7YqtpURNlF5/Undead___1st_Echelon_qZ8RbdImvXjWh2yn/npc_Zombie_G7bFOGyqq0Z4xJ7F.json
  src/packs/monsters/Undead_Awroz7YqtpURNlF5/Undead___2nd_Echelon_bQgGaMhvhgZFC0kO/npc_Flesh_Mournling_B7lTgkUo7Kew8TFy.json
  src/packs/monsters/Undead_Awroz7YqtpURNlF5/Undead___2nd_Echelon_bQgGaMhvhgZFC0kO/npc_Fleshflayed_Shambler_Zombie_JfyGI3TIaslRZWku.json
  src/packs/monsters/Undead_Awroz7YqtpURNlF5/Undead___2nd_Echelon_bQgGaMhvhgZFC0kO/npc_Ghoul_Craver_VosGGEvnrw3zCjdo.json
  src/packs/monsters/Undead_Awroz7YqtpURNlF5/Undead___2nd_Echelon_bQgGaMhvhgZFC0kO/npc_Giant_Zombie_7qbXEbRsrCM62s99.json
  src/packs/monsters/Undead_Awroz7YqtpURNlF5/Undead___2nd_Echelon_bQgGaMhvhgZFC0kO/npc_Hollowbone_Launcher_S1n2gG7RgdjoEdEq.json
  src/packs/monsters/Undead_Awroz7YqtpURNlF5/Undead___2nd_Echelon_bQgGaMhvhgZFC0kO/npc_Mummy_4hY5HEdJNt2CS8ss.json
  src/packs/monsters/Undead_Awroz7YqtpURNlF5/Undead___2nd_Echelon_bQgGaMhvhgZFC0kO/npc_Mummy_Lord_RiO4ptj2KnzQObXl.json
  src/packs/monsters/Undead_Awroz7YqtpURNlF5/Undead___2nd_Echelon_bQgGaMhvhgZFC0kO/npc_Vampire_Spawn_FkXRcf7Y6hDP4hTb.json
  src/packs/monsters/Undead_Awroz7YqtpURNlF5/Undead___2nd_Echelon_bQgGaMhvhgZFC0kO/npc_Wraith_ifk14URrWIthS4oM.json
  src/packs/monsters/Undead_Awroz7YqtpURNlF5/folders_Undead___1st_Echelon_qZ8RbdImvXjWh2yn.json
  src/packs/monsters/Undead_Awroz7YqtpURNlF5/folders_Undead___2nd_Echelon_bQgGaMhvhgZFC0kO.json
  src/packs/monsters/Undead_Awroz7YqtpURNlF5/folders_Undead___3rd_Echelon_JsWXCN3PDasglLHA.json
  src/packs/monsters/Undead_Awroz7YqtpURNlF5/folders_Undead___4th_Echelon_z19jhkNzTzzZC18O.json
Labels: compendium

#1121 Undead 3rd Echelon Monsters and Malice Features
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Undead_Malice_dDubEbmnbWGRYlvn/Level_7__Malice_Features_Kx6gFkGqlrNl3DGg/ability_Necrotic_Rupture_NLIeDdubVVzbOyqX.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Undead_Malice_dDubEbmnbWGRYlvn/Level_7__Malice_Features_Kx6gFkGqlrNl3DGg/ability_Prior_Malice_Features_QrgBWyQsSIgtpGM6.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Undead_Malice_dDubEbmnbWGRYlvn/folders_Level_7__Malice_Features_Kx6gFkGqlrNl3DGg.json
  src/packs/monsters/Undead_Awroz7YqtpURNlF5/Undead___3rd_Echelon_JsWXCN3PDasglLHA/npc_Blood_Starved_Vampire_pNA8H0vk4EDNq4UI.json
  src/packs/monsters/Undead_Awroz7YqtpURNlF5/Undead___3rd_Echelon_JsWXCN3PDasglLHA/npc_Dirt_Mournling_NC6vYdYmoGfRkAIN.json
  src/packs/monsters/Undead_Awroz7YqtpURNlF5/Undead___3rd_Echelon_JsWXCN3PDasglLHA/npc_Faded_Echo_Spirit_FitPOtXzLdBcRHA3.json
  src/packs/monsters/Undead_Awroz7YqtpURNlF5/Undead___3rd_Echelon_JsWXCN3PDasglLHA/npc_Haunt_5gAvkiKBfW3HH9GX.json
  src/packs/monsters/Undead_Awroz7YqtpURNlF5/Undead___3rd_Echelon_JsWXCN3PDasglLHA/npc_Koptourok_5MKj0QVvhJB2n8p9.json
  src/packs/monsters/Undead_Awroz7YqtpURNlF5/Undead___3rd_Echelon_JsWXCN3PDasglLHA/npc_Mummy_Rotwrap_eWQeCWuWYEL6N4QP.json
  src/packs/monsters/Undead_Awroz7YqtpURNlF5/Undead___3rd_Echelon_JsWXCN3PDasglLHA/npc_Vampire_4w2mdhSyQmC6mmBv.json
  src/packs/monsters/Undead_Awroz7YqtpURNlF5/Undead___3rd_Echelon_JsWXCN3PDasglLHA/npc_Vampire_Lord_oGuWdlPZfrxaY0AN.json
  src/packs/monsters/Undead_Awroz7YqtpURNlF5/Undead___3rd_Echelon_JsWXCN3PDasglLHA/npc_Waxen_vrJ6y4aawJXIKOWV.json
Labels: compendium
