Repository MetaMorphic-Digital/draw-steel, pull requests merged in 2025-04, with the labels that each got.

#365 Minion Token HUD improvements
  src/module/canvas/placeables/token.mjs
  src/module/data/actor/base.mjs
  src/module/data/combatant-group/base.mjs
  src/module/data/combatant-group/squad.mjs
  src/module/documents/actor.mjs
  src/module/documents/combatant-group.mjs
  src/module/documents/combatant.mjs
  src/module/documents/token.mjs
Labels: apps

#381 Fix applying damage to minions in `takeDamage`
  src/module/data/actor/base.mjs
Labels: data model

#384 Style adjustments
  src/module/applications/elements/checkbox.mjs
  src/module/applications/sheets/actor-sheet.mjs
  src/module/applications/sheets/item-sheet.mjs
  src/module/data/item/ability.mjs
  src/module/data/item/kit.mjs
  src/module/data/item/project.mjs
  src/module/helpers/handlebars.mjs
  src/module/helpers/hotReload.mjs
  src/styles/elements/slide-toggle.css
  src/styles/system/applications/components/forms.css
  src/styles/system/applications/components/items.css
  src/styles/system/applications/sheets/actor-sheet.css
  src/styles/system/applications/sheets/item-sheet.css
  templates/actor/character/biography.hbs
  templates/actor/character/header.hbs
  templates/actor/character/stats.hbs
  templates/actor/npc/biography.hbs
  templates/actor/npc/header.hbs
  templates/actor/npc/stats.hbs
  templates/actor/shared/partials/stats/immunities-weaknesses.hbs
  templates/item/details.hbs
  templates/item/header.hbs
  templates/item/partials/ability.hbs
  templates/item/partials/kit.hbs
Labels: UI/UX

#386 Improved Ability Display
  lang/en.json
  src/module/applications/sheets/_types.d.ts
  src/module/applications/sheets/item-sheet.mjs
  src/module/data/item/_types.d.ts
  src/module/data/item/ability.mjs
  src/module/data/item/base.mjs
  src/styles/system/applications/sheets/actor-sheet.css
  templates/item/embeds/ability.hbs
Labels: UI/UX

#391 Award victories post combat
  CHANGELOG.md
  lang/en.json
  src/module/documents/combat.mjs
Labels: data model

#394 Improved system documentation workflow
  .github/workflows/publish-wiki.yml
  CONTRIBUTING.md
  package-lock.json
  package.json
  src/docs/Active-Effects.md
  src/docs/Actors.md
  src/docs/Chat-Messages.md
  src/docs/Combat-Encounters.md
  src/docs/Enrichers.md
  src/docs/Frequently-Asked-Questions.md
  src/docs/Home.md
  src/docs/Items.md
  src/docs/Roll-Data.md
  src/packs/journals/combat/journal_Conditions_hDhdILCi65wpBgPZ.json
  src/packs/journals/journal_System_Documentation_2OWtCOMKRpGuBxrI.json
  src/packs/journals/rules/journal_The_Basics_f8eNK5Pte4CSdex0.json
  tools/pullJSONtoLDB.mjs
  tools/pushLDBtoJSON.mjs
Labels: documentation

#405 Token Ruler Fixes
  CHANGELOG.md
  draw-steel.mjs
  lang/en.json
  src/module/applications/_module.mjs
  src/module/applications/hud/_module.mjs
  src/module/applications/hud/token-hud.mjs
  src/module/applications/sheets/actor-sheet.mjs
  src/module/applications/sheets/item-sheet.mjs
  src/module/canvas/_types.d.ts
  src/module/canvas/placeables/token.mjs
  src/module/canvas/placeables/tokens/token-ruler.mjs
  src/module/config.mjs
  src/module/data/item/base.mjs
  src/module/data/item/kit.mjs
  src/module/data/item/project.mjs
  src/module/documents/_types.d.ts
  src/module/documents/token.mjs
  system.json
  templates/hud/waypoint-label.hbs
  templates/hud/waypoint-labels.hbs
  tools/create-symlinks.mjs
Labels: canvas

#407 Various 13.340 fixes
  lang/en.json
  src/module/canvas/placeables/tokens/token-ruler.mjs
  src/module/data/item/ability.mjs
  templates/actor/character/stats.hbs
Labels: data model, apps, canvas, UI/UX

#408 Sheet improvements and fixes
  CHANGELOG.md
  src/module/applications/apps/power-roll-dialog.mjs
  src/module/applications/sheets/actor-sheet.mjs
  src/module/applications/sheets/character.mjs
  src/module/applications/sheets/item-sheet.mjs
  src/module/applications/sheets/npc.mjs
  src/module/applications/sidebar/tabs/combat-tracker.mjs
  src/module/data/item/base.mjs
  src/module/data/item/kit.mjs
  src/module/data/item/project.mjs
  templates/actor/character/header.hbs
  templates/actor/npc/header.hbs
Labels: apps

#422 Adjust max height of system application to 100vh default
  css/draw-steel-system.css
  src/styles/system/applications/_applications.mjs
  src/styles/system/applications/applications.css
Labels: UI/UX

#423 [#419] Add Dialog class and base Application class
  src/module/applications/_module.mjs
  src/module/applications/api/_module.mjs
  src/module/applications/api/application.mjs
  src/module/applications/api/dialog.mjs
Labels: apps

#409 Added combatant group ownership controls
  CHANGELOG.md
  src/module/applications/sidebar/tabs/combat-tracker.mjs
  src/module/data/combatant-group/base.mjs
  src/module/documents/combatant-group.mjs
  src/module/documents/combatant.mjs
Labels: data model, apps

#424 Resolved circular dependencies
  src/module/data/models/source.mjs
  src/module/rolls/power.mjs
Labels: tech debt
