Repository MetaMorphic-Digital/draw-steel, pull requests merged in 2025-08, with the labels that each got.

#753 Resource buttons
  CHANGELOG.md
  src/module/applications/sheets/character.mjs
  src/styles/system/applications/sheets/actor-sheet.css
  templates/sheets/actor/character/stats.hbs
  templates/sheets/actor/npc/stats.hbs
  templates/sheets/actor/shared/partials/stats/immunities-weaknesses.hbs
Labels: UI/UX

#754 Enrich HTML logic fix
  CHANGELOG.md
  src/module/utils/enrich-html.mjs
Labels: apps

#756 Expanded Contributing guidelines to discuss Compendium content
  CONTRIBUTING.md
Labels: documentation, compendium

#783 Content updates
  CHANGELOG.md
  src/module/config.mjs
  src/module/data/item/ability.mjs
  src/packs/abilities/Basic_Abilities_YKzQ5cCX8knW8fAc/ability_Aid_Attack_Xb3S5N1fZyICD58D.json
  src/packs/abilities/Basic_Abilities_YKzQ5cCX8knW8fAc/ability_Catch_Breath_nYPJN8Ce2dX9H09K.json
  src/packs/abilities/Basic_Abilities_YKzQ5cCX8knW8fAc/ability_Charge_wNqJWJbgAbnJBqZf.json
  src/packs/abilities/Basic_Abilities_YKzQ5cCX8knW8fAc/ability_Defend_fjtY7RKBGWx2u5tK.json
  src/packs/abilities/Basic_Abilities_YKzQ5cCX8knW8fAc/ability_Escape_Grab_iD1SlB15GXJFALya.json
  src/packs/abilities/Basic_Abilities_YKzQ5cCX8knW8fAc/ability_Grab_oxaISpgVoCfo6fmt.json
  src/packs/abilities/Basic_Abilities_YKzQ5cCX8knW8fAc/ability_Heal_2qWHDVB7SBS9anLB.json
  src/packs/abilities/Basic_Abilities_YKzQ5cCX8knW8fAc/ability_Hide_JykB1rELpGBeAVe6.json
  src/packs/abilities/Basic_Abilities_YKzQ5cCX8knW8fAc/ability_Knockback_emug9cXuwndDrWzu.json
  src/packs/abilities/Basic_Abilities_YKzQ5cCX8knW8fAc/ability_Melee_Free_Strike_wU69Y06G9lYFrvp6.json
  src/packs/abilities/Basic_Abilities_YKzQ5cCX8knW8fAc/ability_Ranged_Free_Strike_eqUobBcm81mqZVgJ.json
  src/packs/abilities/Basic_Abilities_YKzQ5cCX8knW8fAc/ability_Search_for_Hidden_Creatures_zQ83mlzlRtflpD3w.json
  src/packs/abilities/Basic_Abilities_YKzQ5cCX8knW8fAc/ability_Stand_Up_XeUU0Blvi0fy0b2G.json
Labels: compendium

#784 Implemented showing the compendium source of an item or NPC
  CHANGELOG.md
  lang/en.json
  src/module/applications/_types.d.ts
  src/module/applications/api/_types.d.ts
  src/module/applications/apps/_types.d.ts
  src/module/applications/apps/document-source-input.mjs
  templates/apps/document-input/document-source-input.hbs
Labels: apps

#782 [#537] Epic Resources
  CHANGELOG.md
  lang/en.json
  src/module/data/actor/_types.d.ts
  src/module/data/actor/character.mjs
  src/module/data/item/_types.d.ts
  src/module/data/item/class.mjs
  src/packs/classes/Shadow_ngcpmEclU2UUJbz4/class_Shadow_08pJ0i8AwjMsrKO1.json
  src/packs/classes/Tactician_kCN3c3aC6ziHDp5c/class_Tactician_Y6rtfW6EfHszGqhG.json
  templates/sheets/actor/character/stats.hbs
  templates/sheets/item/partials/class.hbs
Labels: data model

#786 [#259] Added stamina.bonuses.echelon
  CHANGELOG.md
  src/docs/Active-Effects.md
  src/module/data/_types.d.ts
  src/module/data/actor/_types.d.ts
  src/module/data/actor/base.mjs
Labels: data model

#793 Add project and roll table compendiums with 1 item each
  lang/en.json
  src/packs/projects/Crafting_T4atnhMHm4PGlGhs/project_Build_or_Repair_Road_nrGhQfeeUvIHA5u9.json
  src/packs/projects/folders_Crafting_T4atnhMHm4PGlGhs.json
  src/packs/projects/folders_Other_BENe8K7l3sgJhHyY.json
  src/packs/projects/folders_Research_d4ZRwtKptm3Rr4F6.json
  src/packs/tables/Project_Events_Tgb2Z68gf9SJ5VIg/tables_Build_or_Repair_Road_Events_tXtAQLmmJP1vHK6R.json
  src/packs/tables/folders_Project_Events_Tgb2Z68gf9SJ5VIg.json
  system.json
Labels: compendium

#799 [#765] Value adjustments on Kit Signature Abilities
  src/packs/abilities/Kits_9MmUCFDVEUEgDY04/ability_Double_Strike_WObnlBIDDMWoNhVn.json
  src/packs/abilities/Kits_9MmUCFDVEUEgDY04/ability_Exploding_Arrow_efaX6kreuPliD9Fd.json
  src/packs/abilities/Kits_9MmUCFDVEUEgDY04/ability_Fade_ZWx0BbPE3GitPTXJ.json
  src/packs/abilities/Kits_9MmUCFDVEUEgDY04/ability_Protective_Attack_3G70A9bFAJzp7nxD.json
  src/packs/abilities/Kits_9MmUCFDVEUEgDY04/ability_Unmooring_a8GtSVHtRJXKObRj.json
Labels: compendium

#811 [#766] Add crafting perks
  src/packs/character-options/Perks_tb9IiWSEZfQYFh2p/Crafting_tm0Tf8JT8mWlPkZ0/feature_Area_of_Expertise_RR5yz4KnJxNbyisw.json
  src/packs/character-options/Perks_tb9IiWSEZfQYFh2p/Crafting_tm0Tf8JT8mWlPkZ0/feature_Expert_Artisan_15Fd8ksj8Wei4fcJ.json
  src/packs/character-options/Perks_tb9IiWSEZfQYFh2p/Crafting_tm0Tf8JT8mWlPkZ0/feature_Handy_5aL4G6PhWjV4Q8gD.json
  src/packs/character-options/Perks_tb9IiWSEZfQYFh2p/Crafting_tm0Tf8JT8mWlPkZ0/feature_Improvisation_Creation_pZXfPq3qKc7RyTsA.json
  src/packs/character-options/Perks_tb9IiWSEZfQYFh2p/Crafting_tm0Tf8JT8mWlPkZ0/feature_Inspired_Artisan_jZ8I5l70BPVk6Qsx.json
  src/packs/character-options/Perks_tb9IiWSEZfQYFh2p/Crafting_tm0Tf8JT8mWlPkZ0/feature_Travelling_Artisan_Adqm52vXCP31H2dx.json
  src/packs/character-options/Perks_tb9IiWSEZfQYFh2p/folders_Crafting_tm0Tf8JT8mWlPkZ0.json
Labels: compendium

#814 [#766] Add intrigue perks
  src/packs/character-options/Perks_tb9IiWSEZfQYFh2p/Intrigue_TUYdPYR5kSbROwvU/feature_Criminal_Contacts_tw3ZzAxlMjr4fQBU.json
  src/packs/character-options/Perks_tb9IiWSEZfQYFh2p/Intrigue_TUYdPYR5kSbROwvU/feature_Forgettable_Face_SrStm9m3EGmCj4iO.json
  src/packs/character-options/Perks_tb9IiWSEZfQYFh2p/Intrigue_TUYdPYR5kSbROwvU/feature_Gum_Up_the_Works_9D7YX2pdAzGv0tYq.json
  src/packs/character-options/Perks_tb9IiWSEZfQYFh2p/Intrigue_TUYdPYR5kSbROwvU/feature_Lucky_Dog_owJS4O1AoUp3lleu.json
  src/packs/character-options/Perks_tb9IiWSEZfQYFh2p/Intrigue_TUYdPYR5kSbROwvU/feature_Master_of_Disguise_7dEqaC6mVGcUxrby.json
  src/packs/character-options/Perks_tb9IiWSEZfQYFh2p/Intrigue_TUYdPYR5kSbROwvU/feature_Slipped_Lead_QE3zaSEfkYkIOyQm.json
  src/packs/character-options/Perks_tb9IiWSEZfQYFh2p/folders_Intrigue_TUYdPYR5kSbROwvU.json
Labels: compendium

#815 [#766] Add lore perks
  src/packs/character-options/Perks_tb9IiWSEZfQYFh2p/Lore_rdU05mKMnnKBRTnA/feature_But_I_Know_Who_Does_yhVy35nwex2DQZBK.json
  src/packs/character-options/Perks_tb9IiWSEZfQYFh2p/Lore_rdU05mKMnnKBRTnA/feature_Eidetic_Memory_OhV61irKCVuHZaAk.json
  src/packs/character-options/Perks_tb9IiWSEZfQYFh2p/Lore_rdU05mKMnnKBRTnA/feature_Expert_Sage_iEPSLFMz1H5XKNPZ.json
  src/packs/character-options/Perks_tb9IiWSEZfQYFh2p/Lore_rdU05mKMnnKBRTnA/feature_I_ve_Read_About_This_Place_5L8uUJXIaW653rka.json
  src/packs/character-options/Perks_tb9IiWSEZfQYFh2p/Lore_rdU05mKMnnKBRTnA/feature_Linguist_1NBLfs0ERePHwIhF.json
  src/packs/character-options/Perks_tb9IiWSEZfQYFh2p/Lore_rdU05mKMnnKBRTnA/feature_Polymath_ys5MAnDllhpK7VFz.json
  src/packs/character-options/Perks_tb9IiWSEZfQYFh2p/Lore_rdU05mKMnnKBRTnA/feature_Specialist_cG7wwuJTiieHqbmD.json
  src/packs/character-options/Perks_tb9IiWSEZfQYFh2p/Lore_rdU05mKMnnKBRTnA/feature_Travelling_Sage_FBfINe9Q8C2AvVmt.json
  src/packs/character-options/Perks_tb9IiWSEZfQYFh2p/folders_Lore_rdU05mKMnnKBRTnA.json
Labels: compendium

#804 [#761] Devils
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Devil_vI2lXvZhkhwHKLrz/Features_eTVTaGVRRrrni84u/feature_Barbed_Tail_HZ79OavAF7SpzMYt.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Devil_vI2lXvZhkhwHKLrz/Features_eTVTaGVRRrrni84u/feature_Beast_Legs_IWD4Pua2f8rKLLY3.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Devil_vI2lXvZhkhwHKLrz/Features_eTVTaGVRRrrni84u/feature_Glowing_Eyes_npLTlAWa8PqdUN0N.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Devil_vI2lXvZhkhwHKLrz/Features_eTVTaGVRRrrni84u/feature_Hellsight_2UBV1KK9O20000ty.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Devil_vI2lXvZhkhwHKLrz/Features_eTVTaGVRRrrni84u/feature_Impressive_Horns_YK7TDv4d7ZgODY3U.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Devil_vI2lXvZhkhwHKLrz/Features_eTVTaGVRRrrni84u/feature_Prehensile_Tail_nXmsu9ClzQpdQE0e.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Devil_vI2lXvZhkhwHKLrz/Features_eTVTaGVRRrrni84u/feature_Silver_Tongue_Ch6TwaIZ8MxXYzbn.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Devil_vI2lXvZhkhwHKLrz/Features_eTVTaGVRRrrni84u/feature_Wings_J3ctTvIiRbzAEDw1.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Devil_vI2lXvZhkhwHKLrz/ancestry_Devil_VfIna2d0jNXwKNaT.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Devil_vI2lXvZhkhwHKLrz/folders_Features_eTVTaGVRRrrni84u.json
  src/packs/origins/folders_Ancestries_g8kLlrl0nzciXfRF.json
Labels: compendium

#805 Expanded content creation style guide
  CONTRIBUTING.md
Labels: compendium

#801 Level up button
  CHANGELOG.md
  src/module/applications/sheets/character.mjs
  src/module/data/actor/character.mjs
  src/styles/system/applications/sheets/actor-sheet.css
  system.json
  templates/sheets/actor/character/header.hbs
Labels: apps

#818 [#761] Wode Elf, High Elf, Hakaan, Human
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Hakaan_bjdoFvLNiQYWPdg6/Features_DKux4Xs4d5pHOeOQ/feature_All_Is_A_Feather_YvDr83SFMo5VmWJo.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Hakaan_bjdoFvLNiQYWPdg6/Features_DKux4Xs4d5pHOeOQ/feature_Big__Z029RWPeRo8KBXQd.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Hakaan_bjdoFvLNiQYWPdg6/Features_DKux4Xs4d5pHOeOQ/feature_Doomsight_J8VkGc9ikZNDfJb5.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Hakaan_bjdoFvLNiQYWPdg6/Features_DKux4Xs4d5pHOeOQ/feature_Forceful_gaIIzsI313sAC206.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Hakaan_bjdoFvLNiQYWPdg6/Features_DKux4Xs4d5pHOeOQ/feature_Great_Fortitude_9zkEBdYr8jr9nsvj.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Hakaan_bjdoFvLNiQYWPdg6/Features_DKux4Xs4d5pHOeOQ/feature_Stand_Tough_z43Eha9RiPkD9peB.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Hakaan_bjdoFvLNiQYWPdg6/ancestry_Hakaan_7EbtUA93x6UDQHBp.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Hakaan_bjdoFvLNiQYWPdg6/folders_Features_DKux4Xs4d5pHOeOQ.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/High_Elf_hLn2WWmB4ypun9vP/Features_JNMjz4DXxc07vswK/feature_Glamor_of_Terror_uHpwLB8wTL47WJr5.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/High_Elf_hLn2WWmB4ypun9vP/Features_JNMjz4DXxc07vswK/feature_Graceful_Retreat_VF6zaUKLsLN1Im3W.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/High_Elf_hLn2WWmB4ypun9vP/Features_JNMjz4DXxc07vswK/feature_High_Elf_Glamor_Zh8ZNVJqtJgJpW7m.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/High_Elf_hLn2WWmB4ypun9vP/Features_JNMjz4DXxc07vswK/feature_High_Senses_m1tQ43tT1hnixVBn.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/High_Elf_hLn2WWmB4ypun9vP/Features_JNMjz4DXxc07vswK/feature_Otherworldly_Grace_YrnkrcvZSkecn21f.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/High_Elf_hLn2WWmB4ypun9vP/Features_JNMjz4DXxc07vswK/feature_Revisit_Memory_3Y0oPwqk2tDFlaTp.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/High_Elf_hLn2WWmB4ypun9vP/Features_JNMjz4DXxc07vswK/feature_Unstoppable_Mind_cs8jldLJrjpmpRfl.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/High_Elf_hLn2WWmB4ypun9vP/ancestry_High_Elf_hEqZong6lVXUpIwX.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/High_Elf_hLn2WWmB4ypun9vP/folders_Features_JNMjz4DXxc07vswK.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Human_yqtQM6iNMHT1AuCX/Features_RSkrwlIXmLNmD4MB/feature_Can_t_Take_Hold_sApldmo4F6eoArMh.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Human_yqtQM6iNMHT1AuCX/Features_RSkrwlIXmLNmD4MB/feature_Detect_the_Supernatural_X40Vg1cP1ze1FeBL.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Human_yqtQM6iNMHT1AuCX/Features_RSkrwlIXmLNmD4MB/feature_Determination_hcAmOtDXMqCpcyI4.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Human_yqtQM6iNMHT1AuCX/Features_RSkrwlIXmLNmD4MB/feature_Perseverance_5eR1iLU6P8ogobGB.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Human_yqtQM6iNMHT1AuCX/Features_RSkrwlIXmLNmD4MB/feature_Resist_the_Unnatural_FUrxZYvocf8fmdnv.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Human_yqtQM6iNMHT1AuCX/Features_RSkrwlIXmLNmD4MB/feature_Staying_Power_r0zaFM82zkl4tMnC.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Human_yqtQM6iNMHT1AuCX/Granted_Abilities_xaqg4nGWtsBeDMRG/ability_Detect_the_Supernatural_1Pb03O9ddE3uidfQ.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Human_yqtQM6iNMHT1AuCX/Granted_Abilities_xaqg4nGWtsBeDMRG/ability_Determination_vbMOfcUNZEb5dXko.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Human_yqtQM6iNMHT1AuCX/ancestry_Human_qQx6D3WR3vO1Z7uF.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Human_yqtQM6iNMHT1AuCX/folders_Features_RSkrwlIXmLNmD4MB.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Human_yqtQM6iNMHT1AuCX/folders_Granted_Abilities_xaqg4nGWtsBeDMRG.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Wode_Elf_3kt2CaD1XI5F5tws/Features_8LShXtGwfnJ9YFAr/feature_Forest_Walk_PHL5m176Z04OddCZ.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Wode_Elf_3kt2CaD1XI5F5tws/Features_8LShXtGwfnJ9YFAr/feature_Otherwordly_Grace_F2JlPVFs8n7vWJOI.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Wode_Elf_3kt2CaD1XI5F5tws/Features_8LShXtGwfnJ9YFAr/feature_Quick_and_Brutal_HMO2DpVxFvI124KZ.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Wode_Elf_3kt2CaD1XI5F5tws/Features_8LShXtGwfnJ9YFAr/feature_Revisit_Memory_HAPtKnmBEjjWYFBX.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Wode_Elf_3kt2CaD1XI5F5tws/Features_8LShXtGwfnJ9YFAr/feature_Swift_VXwDHExr9y44UrWT.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Wode_Elf_3kt2CaD1XI5F5tws/Features_8LShXtGwfnJ9YFAr/feature_The_Wode_Defends_NeQebjBMtSfCPP1H.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Wode_Elf_3kt2CaD1XI5F5tws/Features_8LShXtGwfnJ9YFAr/feature_Wode_Elf_Glamor_Ixiq7cFNRLjbd1ZX.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Wode_Elf_3kt2CaD1XI5F5tws/Granted_Abilities_ISKOwnr7EpJ2YXDj/ability_The_Wode_Defends_ndfKDhG31IC5D8rq.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Wode_Elf_3kt2CaD1XI5F5tws/ancestry_Wode_Elf_mRtEe0MxgJoDhSlV.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Wode_Elf_3kt2CaD1XI5F5tws/folders_Features_8LShXtGwfnJ9YFAr.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Wode_Elf_3kt2CaD1XI5F5tws/folders_Granted_Abilities_ISKOwnr7EpJ2YXDj.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/folders_Hakaan_bjdoFvLNiQYWPdg6.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/folders_High_Elf_hLn2WWmB4ypun9vP.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/folders_Human_yqtQM6iNMHT1AuCX.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/folders_Wode_Elf_3kt2CaD1XI5F5tws.json
Labels: compendium

#819 [761] Memonek, Orc, Polder, Revenant, Time Raider
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Memonek_VnnpE5RTlUNRBhnw/Features_x6Rfwwat4WIPoUjY/feature_Fall_Lightly_CtMlN4oLTmq7t9Ff.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Memonek_VnnpE5RTlUNRBhnw/Features_x6Rfwwat4WIPoUjY/feature_I_Am_Law_mmBpEU7rkbKmoNJy.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Memonek_VnnpE5RTlUNRBhnw/Features_x6Rfwwat4WIPoUjY/feature_Keeper_of_Order_UvjXi5wXwSbtbzY4.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Memonek_VnnpE5RTlUNRBhnw/Features_x6Rfwwat4WIPoUjY/feature_Lightning_Nimbleness_mjJ4CRUPCfpb2Vuo.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Memonek_VnnpE5RTlUNRBhnw/Features_x6Rfwwat4WIPoUjY/feature_Lightweight_g3Jj190yTU3DuEM0.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Memonek_VnnpE5RTlUNRBhnw/Features_x6Rfwwat4WIPoUjY/feature_Nonstop_zXJteUEoV9C65cMB.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Memonek_VnnpE5RTlUNRBhnw/Features_x6Rfwwat4WIPoUjY/feature_Systematic_Mind_oOYRsaTZCDp9OY6V.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Memonek_VnnpE5RTlUNRBhnw/Features_x6Rfwwat4WIPoUjY/feature_Unphased_MgNqH2CQEvtr4G8g.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Memonek_VnnpE5RTlUNRBhnw/Features_x6Rfwwat4WIPoUjY/feature_Useful_Emotion_p8FB9d7mRSahMwtT.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Memonek_VnnpE5RTlUNRBhnw/ancestry_Memonek_MlXODwIMSUDzHppQ.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Memonek_VnnpE5RTlUNRBhnw/folders_Features_x6Rfwwat4WIPoUjY.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Orc_bfUxX1uyb1Ywa3kh/Features_ZvuKltIHpPATpmQR/feature_Bloodfire_Rush_y1I1Gf3KcQ7WK9TE.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Orc_bfUxX1uyb1Ywa3kh/Features_ZvuKltIHpPATpmQR/feature_Glowing_Recovery_PHzBW0LBXgdi5m09.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Orc_bfUxX1uyb1Ywa3kh/Features_ZvuKltIHpPATpmQR/feature_Grounded_hBUbWGbAShFqARiX.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Orc_bfUxX1uyb1Ywa3kh/Features_ZvuKltIHpPATpmQR/feature_Nonstop_0WfVcJfD3mhne26S.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Orc_bfUxX1uyb1Ywa3kh/Features_ZvuKltIHpPATpmQR/feature_Passionate_Artisan_HKz73mFMk3cwWIyN.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Orc_bfUxX1uyb1Ywa3kh/Features_ZvuKltIHpPATpmQR/feature_Relentless_AL0IjPuMhACpsiks.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Orc_bfUxX1uyb1Ywa3kh/ancestry_Orc_lpjYGgiX3uLRhJQN.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Orc_bfUxX1uyb1Ywa3kh/folders_Features_ZvuKltIHpPATpmQR.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Polder_37E6ga1d3mNuQFQn/Features_5ZNEzHj1srMQquH7/feature_Corruption_Immunity_WFaKeDhxONumCRek.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Polder_37E6ga1d3mNuQFQn/Features_5ZNEzHj1srMQquH7/feature_Fearless_sAzlkp3b67AYwucx.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Polder_37E6ga1d3mNuQFQn/Features_5ZNEzHj1srMQquH7/feature_Graceful_Retreat_Rv80kYretCbPaguq.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Polder_37E6ga1d3mNuQFQn/Features_5ZNEzHj1srMQquH7/feature_Nimblestep_WrLBhTDLbX80T7hN.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Polder_37E6ga1d3mNuQFQn/Features_5ZNEzHj1srMQquH7/feature_Polder_Geist_EsJYMF39KZwneS4F.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Polder_37E6ga1d3mNuQFQn/Features_5ZNEzHj1srMQquH7/feature_Reactive_Tumble_n9J7I0TzxJOYgucN.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Polder_37E6ga1d3mNuQFQn/Features_5ZNEzHj1srMQquH7/feature_Shadowmeld_DbpK06fEyJxin1tA.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Polder_37E6ga1d3mNuQFQn/Features_5ZNEzHj1srMQquH7/feature_Small__Sk03bZTV24MzxYVT.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Polder_37E6ga1d3mNuQFQn/Granted_Abilities_Dxv0cMH5TvEgasZs/ability_Shadowmeld_dm2hlPBUmlnN3Fxd.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Polder_37E6ga1d3mNuQFQn/ancestry_Polder_Xr3d9MkBiXl2236W.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Polder_37E6ga1d3mNuQFQn/folders_Features_5ZNEzHj1srMQquH7.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Polder_37E6ga1d3mNuQFQn/folders_Granted_Abilities_Dxv0cMH5TvEgasZs.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Revenant_X9AtzeQpQ2ZkrkMz/Features_uWYEH9fs5ogusKkP/feature_Bloodless_77tLSEIDpNRpkwnn.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Revenant_X9AtzeQpQ2ZkrkMz/Features_uWYEH9fs5ogusKkP/feature_Former_Life_xXl9h7qyi4z91jYO.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Revenant_X9AtzeQpQ2ZkrkMz/Features_uWYEH9fs5ogusKkP/feature_Previous_Life__1_Point_LhqV95QNJKZ4ItIU.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Revenant_X9AtzeQpQ2ZkrkMz/Features_uWYEH9fs5ogusKkP/feature_Previous_Life__2_Points_M8hcInvmTs5DG902.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Revenant_X9AtzeQpQ2ZkrkMz/Features_uWYEH9fs5ogusKkP/feature_Tough_But_Withered_S2OsBBFHqBoHZYUu.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Revenant_X9AtzeQpQ2ZkrkMz/Features_uWYEH9fs5ogusKkP/feature_Undead_Influence_UWNCLuMl8DljBsrN.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Revenant_X9AtzeQpQ2ZkrkMz/Features_uWYEH9fs5ogusKkP/feature_Vengeance_Mark_4rkruRy4WbjyM7Vx.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Revenant_X9AtzeQpQ2ZkrkMz/Granted_Abilities_p3VxrQSz1mLJMRai/ability_Detonate_Sigil_ZIT7GAWbRXISR5Al.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Revenant_X9AtzeQpQ2ZkrkMz/Granted_Abilities_p3VxrQSz1mLJMRai/ability_Vengeance_Mark_Dcd5Qglnnve99ICX.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Revenant_X9AtzeQpQ2ZkrkMz/ancestry_Revenant_2dUOZ1eYinund6MQ.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Revenant_X9AtzeQpQ2ZkrkMz/folders_Features_uWYEH9fs5ogusKkP.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Revenant_X9AtzeQpQ2ZkrkMz/folders_Granted_Abilities_p3VxrQSz1mLJMRai.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Time_Raider_vR598asS3AjnAuEF/Features_FACFQjxnOrP1RX5o/feature_Beyondsight_IKuZJ4xQursPczZ8.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Time_Raider_vR598asS3AjnAuEF/Features_FACFQjxnOrP1RX5o/feature_Foresight_39xUjIrLf0Dy7P3t.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Time_Raider_vR598asS3AjnAuEF/Features_FACFQjxnOrP1RX5o/feature_Four_Armed_Athletics_4Y4EXGkS244LYmEH.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Time_Raider_vR598asS3AjnAuEF/Features_FACFQjxnOrP1RX5o/feature_Four_Armed_Martial_Arts_uAhU9gIqav2nLXAJ.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Time_Raider_vR598asS3AjnAuEF/Features_FACFQjxnOrP1RX5o/feature_Psionic_Gift_QmQ1bhbT1F6hc8Gt.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Time_Raider_vR598asS3AjnAuEF/Features_FACFQjxnOrP1RX5o/feature_Psychic_Scar_3va7ie8M9HbPtSIe.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Time_Raider_vR598asS3AjnAuEF/Features_FACFQjxnOrP1RX5o/feature_Unstoppable_Mind_6YlNYWUGvqYzNjVI.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Time_Raider_vR598asS3AjnAuEF/Granted_Abilities_cRmntDE2VNDzurg2/ability_Beyondsight_FpZFBiABg77wdOEk.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Time_Raider_vR598asS3AjnAuEF/Granted_Abilities_cRmntDE2VNDzurg2/ability_Concussive_Slam_FRPORMdCeEONySxL.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Time_Raider_vR598asS3AjnAuEF/Granted_Abilities_cRmntDE2VNDzurg2/ability_Minor_Acceleration_sSWcFde8OLkWgksg.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Time_Raider_vR598asS3AjnAuEF/Granted_Abilities_cRmntDE2VNDzurg2/ability_Psionic__Bolt_NtmaR1wzwRtMt5LZ.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Time_Raider_vR598asS3AjnAuEF/ancestry_Time_Raider_qv3UhEke6Er4sPNo.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Time_Raider_vR598asS3AjnAuEF/folders_Features_FACFQjxnOrP1RX5o.json
  src/packs/origins/Ancestries_g8kLlrl0nzciXfRF/Time_Raider_vR598asS3AjnAuEF/folders_Granted_Abilities_cRmntDE2VNDzurg2.json
Labels: compendium

#833 [#770] Add level 1 censor features
  src/packs/abilities/Censor_JY7vFbefcnBYK2ly/Core_MxYBhnKzxJIGiWt8/Exorcist_ocU5l7xWgjDrp9M2/feature_Exorcist_Judgement_Benefit_2PN3V6VneoEO3Zc8.json
  src/packs/abilities/Censor_JY7vFbefcnBYK2ly/Core_MxYBhnKzxJIGiWt8/Oracle_VdpTBXd6U4xtCWkL/feature_Oracle_Judgement_Benefit_dgbwSeDcBDsUOHJW.json
  src/packs/abilities/Censor_JY7vFbefcnBYK2ly/Core_MxYBhnKzxJIGiWt8/Paragon_qlV8MiTmyQ0rIxcZ/feature_Paragon_Judgement_Benefit_OdMVkg9JG3gqBlRu.json
  src/packs/abilities/Censor_JY7vFbefcnBYK2ly/Core_MxYBhnKzxJIGiWt8/ability_Judgement_EhPpL42VZWxqeSEj.json
  src/packs/abilities/Censor_JY7vFbefcnBYK2ly/Core_MxYBhnKzxJIGiWt8/ability_My_Life_for_Yours_0BbgRsExkr0Iq3PS.json
  src/packs/abilities/Censor_JY7vFbefcnBYK2ly/Core_MxYBhnKzxJIGiWt8/folders_Exorcist_ocU5l7xWgjDrp9M2.json
  src/packs/abilities/Censor_JY7vFbefcnBYK2ly/Core_MxYBhnKzxJIGiWt8/folders_Oracle_VdpTBXd6U4xtCWkL.json
  src/packs/abilities/Censor_JY7vFbefcnBYK2ly/Core_MxYBhnKzxJIGiWt8/folders_Paragon_qlV8MiTmyQ0rIxcZ.json
  src/packs/abilities/Censor_JY7vFbefcnBYK2ly/Level_1_FHC1Vh9uhcEZnevR/3_Wrath_1KXwSgGxCTvfrnKn/ability_Behold_a_Shield_of_Fate__kfkkmiaXCPQrF5AJ.json
  src/packs/abilities/Censor_JY7vFbefcnBYK2ly/Level_1_FHC1Vh9uhcEZnevR/3_Wrath_1KXwSgGxCTvfrnKn/ability_Driving_Assault_O1njNmXuEi1xVGYG.json
  src/packs/abilities/Censor_JY7vFbefcnBYK2ly/Level_1_FHC1Vh9uhcEZnevR/3_Wrath_1KXwSgGxCTvfrnKn/ability_Repent__jROTjPu8bYWnB1zM.json
  src/packs/abilities/Censor_JY7vFbefcnBYK2ly/Level_1_FHC1Vh9uhcEZnevR/3_Wrath_1KXwSgGxCTvfrnKn/ability_The_Gods_Punish_and_Defend_yxeUUh0LXFldQJTp.json
  src/packs/abilities/Censor_JY7vFbefcnBYK2ly/Level_1_FHC1Vh9uhcEZnevR/5_Wrath_GOehKV6ApzuE7vxg/ability_Arrest_vCYGSjp1mhNTD30W.json
  src/packs/abilities/Censor_JY7vFbefcnBYK2ly/Level_1_FHC1Vh9uhcEZnevR/5_Wrath_GOehKV6ApzuE7vxg/ability_Behold_the_Face_of_Justice_sFh9wjx5O14mVWgp.json
  src/packs/abilities/Censor_JY7vFbefcnBYK2ly/Level_1_FHC1Vh9uhcEZnevR/5_Wrath_GOehKV6ApzuE7vxg/ability_Censored_W3ZzrWltpxY8CUq4.json
  src/packs/abilities/Censor_JY7vFbefcnBYK2ly/Level_1_FHC1Vh9uhcEZnevR/5_Wrath_GOehKV6ApzuE7vxg/ability_Purifying_Fire_4m5rgK9RH2QXg9S5.json
  src/packs/abilities/Censor_JY7vFbefcnBYK2ly/Level_1_FHC1Vh9uhcEZnevR/Signature_jw6QFUSzLJXxDvsh/ability_Back_Blasphemer__oT9bE6xptFbhVYkY.json
  src/packs/abilities/Censor_JY7vFbefcnBYK2ly/Level_1_FHC1Vh9uhcEZnevR/Signature_jw6QFUSzLJXxDvsh/ability_Every_Step_____Death__DRn0dwWAA4NvG1aY.json
  src/packs/abilities/Censor_JY7vFbefcnBYK2ly/Level_1_FHC1Vh9uhcEZnevR/Signature_jw6QFUSzLJXxDvsh/ability_Halt_Miscreant__ufMtQ8Vjk69ZaB6E.json
  src/packs/abilities/Censor_JY7vFbefcnBYK2ly/Level_1_FHC1Vh9uhcEZnevR/Signature_jw6QFUSzLJXxDvsh/ability_Your_Allies_Cannot_Save_You__zMsvZ08yT9oEdp8h.json
  src/packs/abilities/Censor_JY7vFbefcnBYK2ly/Level_1_FHC1Vh9uhcEZnevR/folders_3_Wrath_1KXwSgGxCTvfrnKn.json
  src/packs/abilities/Censor_JY7vFbefcnBYK2ly/Level_1_FHC1Vh9uhcEZnevR/folders_5_Wrath_GOehKV6ApzuE7vxg.json
  src/packs/abilities/Censor_JY7vFbefcnBYK2ly/Level_1_FHC1Vh9uhcEZnevR/folders_Signature_jw6QFUSzLJXxDvsh.json
  src/packs/abilities/Censor_JY7vFbefcnBYK2ly/folders_Core_MxYBhnKzxJIGiWt8.json
  src/packs/abilities/Censor_JY7vFbefcnBYK2ly/folders_Level_1_FHC1Vh9uhcEZnevR.json
  src/packs/abilities/folders_Censor_JY7vFbefcnBYK2ly.json
  src/packs/classes/Censor_ScAs0Dx7zp2fbcYH/Features_ZaQazDd1CJFiw3wK/Domain_Features_USQKTXhqgTnvUILn/ability_Faithful_Friend_ZhqgI08tIbGC3XbN.json
  src/packs/classes/Censor_ScAs0Dx7zp2fbcYH/Features_ZaQazDd1CJFiw3wK/Domain_Features_USQKTXhqgTnvUILn/ability_Grave_Speech_K9FppXA3WwSOTau2.json
  src/packs/classes/Censor_ScAs0Dx7zp2fbcYH/Features_ZaQazDd1CJFiw3wK/Domain_Features_USQKTXhqgTnvUILn/ability_Hands_of_the_Maker_0ngqc4N46lNiPFmj.json
  src/packs/classes/Censor_ScAs0Dx7zp2fbcYH/Features_ZaQazDd1CJFiw3wK/Domain_Features_USQKTXhqgTnvUILn/feature_Blessing_of_Compassion_xBPRPx0rCRzJyuHW.json
  src/packs/classes/Censor_ScAs0Dx7zp2fbcYH/Features_ZaQazDd1CJFiw3wK/Domain_Features_USQKTXhqgTnvUILn/feature_Blessing_of_Comprehension_j4JVO5suar1GAG3H.json
  src/packs/classes/Censor_ScAs0Dx7zp2fbcYH/Features_ZaQazDd1CJFiw3wK/Domain_Features_USQKTXhqgTnvUILn/feature_Blessing_of_Fortunate_Weather_nJCMi89lqNz37SfQ.json
  src/packs/classes/Censor_ScAs0Dx7zp2fbcYH/Features_ZaQazDd1CJFiw3wK/Domain_Features_USQKTXhqgTnvUILn/feature_Inner_Light_LJ2tJSML9R829mPJ.json
  src/packs/classes/Censor_ScAs0Dx7zp2fbcYH/Features_ZaQazDd1CJFiw3wK/Domain_Features_USQKTXhqgTnvUILn/feature_Inspired_Deception_WvN7AfRhk6seVTyD.json
  src/packs/classes/Censor_ScAs0Dx7zp2fbcYH/Features_ZaQazDd1CJFiw3wK/Domain_Features_USQKTXhqgTnvUILn/feature_Oracular_Visions_JJ3UA747cTXkAwe4.json
  src/packs/classes/Censor_ScAs0Dx7zp2fbcYH/Features_ZaQazDd1CJFiw3wK/Domain_Features_USQKTXhqgTnvUILn/feature_Protective_Circle_jNa2imlBtbOzX5tC.json
  src/packs/classes/Censor_ScAs0Dx7zp2fbcYH/Features_ZaQazDd1CJFiw3wK/Domain_Features_USQKTXhqgTnvUILn/feature_Revitalizing_Ritual_z0B62LJOs3hnnzdo.json
  src/packs/classes/Censor_ScAs0Dx7zp2fbcYH/Features_ZaQazDd1CJFiw3wK/Domain_Features_USQKTXhqgTnvUILn/feature_Sancitifed_Weapon_QPBQMs2Sw77FH6oa.json
  src/packs/classes/Censor_ScAs0Dx7zp2fbcYH/Features_ZaQazDd1CJFiw3wK/Domains_gmzgDHl6YgJhDov1/feature_Creation_nHGVsBWuztLS4ksk.json
  src/packs/classes/Censor_ScAs0Dx7zp2fbcYH/Features_ZaQazDd1CJFiw3wK/Domains_gmzgDHl6YgJhDov1/feature_Death_jPBOFh69UKek4qHy.json
  src/packs/classes/Censor_ScAs0Dx7zp2fbcYH/Features_ZaQazDd1CJFiw3wK/Domains_gmzgDHl6YgJhDov1/feature_Fate_C8JSoc62isJYfb2h.json
  src/packs/classes/Censor_ScAs0Dx7zp2fbcYH/Features_ZaQazDd1CJFiw3wK/Domains_gmzgDHl6YgJhDov1/feature_Knowledge_6K0vobfNvsxbJtVy.json
  src/packs/classes/Censor_ScAs0Dx7zp2fbcYH/Features_ZaQazDd1CJFiw3wK/Domains_gmzgDHl6YgJhDov1/feature_Life_oqtPhdQpDx50BnTZ.json
  src/packs/classes/Censor_ScAs0Dx7zp2fbcYH/Features_ZaQazDd1CJFiw3wK/Domains_gmzgDHl6YgJhDov1/feature_Love_6kvPB4bHw1d7662s.json
  src/packs/classes/Censor_ScAs0Dx7zp2fbcYH/Features_ZaQazDd1CJFiw3wK/Domains_gmzgDHl6YgJhDov1/feature_Nature_yqQWciGcjSpaaivx.json
  src/packs/classes/Censor_ScAs0Dx7zp2fbcYH/Features_ZaQazDd1CJFiw3wK/Domains_gmzgDHl6YgJhDov1/feature_Protection_Sllc2VCEUufjTxbD.json
  src/packs/classes/Censor_ScAs0Dx7zp2fbcYH/Features_ZaQazDd1CJFiw3wK/Domains_gmzgDHl6YgJhDov1/feature_Storm_YMK6ij4CWVveomYh.json
  src/packs/classes/Censor_ScAs0Dx7zp2fbcYH/Features_ZaQazDd1CJFiw3wK/Domains_gmzgDHl6YgJhDov1/feature_Sun_lNq4fju8te2nCEQ5.json
  src/packs/classes/Censor_ScAs0Dx7zp2fbcYH/Features_ZaQazDd1CJFiw3wK/Domains_gmzgDHl6YgJhDov1/feature_Trickery_2TrHhExE5Xzqjt4I.json
  src/packs/classes/Censor_ScAs0Dx7zp2fbcYH/Features_ZaQazDd1CJFiw3wK/Domains_gmzgDHl6YgJhDov1/feature_War_lViMQSujuvawRP0P.json
  src/packs/classes/Censor_ScAs0Dx7zp2fbcYH/Features_ZaQazDd1CJFiw3wK/feature_Deity_and_Domains_vwqIB4UTc6ow6mXt.json
  src/packs/classes/Censor_ScAs0Dx7zp2fbcYH/Features_ZaQazDd1CJFiw3wK/feature_Wrath_qkj3iQg7Ga2OzXXY.json
  src/packs/classes/Censor_ScAs0Dx7zp2fbcYH/Features_ZaQazDd1CJFiw3wK/folders_Domain_Features_USQKTXhqgTnvUILn.json
  src/packs/classes/Censor_ScAs0Dx7zp2fbcYH/Features_ZaQazDd1CJFiw3wK/folders_Domains_gmzgDHl6YgJhDov1.json
  src/packs/classes/Censor_ScAs0Dx7zp2fbcYH/Subclasses_NLxB1ruArthWoUkL/subclass_Exorcist_4sIzvWJt4GkrIceK.json
  src/packs/classes/Censor_ScAs0Dx7zp2fbcYH/Subclasses_NLxB1ruArthWoUkL/subclass_Oracle_xOrDR2a0Kf7B4BcV.json
  src/packs/classes/Censor_ScAs0Dx7zp2fbcYH/Subclasses_NLxB1ruArthWoUkL/subclass_Paragon_G7CW919PYBzeVnH9.json
  src/packs/classes/Censor_ScAs0Dx7zp2fbcYH/class_Censor_YuuUbBMSvzN5IPLv.json
  src/packs/classes/Censor_ScAs0Dx7zp2fbcYH/folders_Features_ZaQazDd1CJFiw3wK.json
  src/packs/classes/Censor_ScAs0Dx7zp2fbcYH/folders_Subclasses_NLxB1ruArthWoUkL.json
Labels: compendium

#856 Typo fix: "Vaslorian" EN label
  lang/en.json
Labels: config, UI/UX

#789 [#713] Ability Modifier AE subtype
  CHANGELOG.md
  draw-steel.mjs
  lang/en.json
  src/docs/Active-Effects.md
  src/docs/Roll-Data.md
  src/module/applications/sheets/_types.d.ts
  src/module/applications/sheets/active-effect-config.mjs
  src/module/applications/sheets/actor-sheet.mjs
  src/module/applications/sheets/item-sheet.mjs
  src/module/data/_types.d.ts
  src/module/data/actor/_types.d.ts
  src/module/data/actor/base.mjs
  src/module/data/actor/character.mjs
  src/module/data/effect/_module.mjs
  src/module/data/effect/_types.d.ts
  src/module/data/effect/ability-bonus.mjs
  src/module/data/effect/base.mjs
  src/module/data/item/_types.d.ts
  src/module/data/item/ability.mjs
  src/module/documents/_types.d.ts
  src/module/documents/active-effect.mjs
  system.json
  templates/sheets/active-effect/details.hbs
  templates/sheets/actor/shared/effects.hbs
  templates/sheets/actor/shared/partials/stats/combat.hbs
  templates/sheets/item/effects.hbs
Labels: data model

#857 Type migrations
  draw-steel.mjs
  lang/en.json
  src/module/applications/apps/advancement/chain-configuration-dialog.mjs
  src/module/applications/sheets/_module.mjs
  src/module/applications/sheets/_types.d.ts
  src/module/applications/sheets/actor-sheet.mjs
  src/module/applications/sheets/hero-sheet.mjs
  src/module/canvas/placeables/token.mjs
  src/module/config.mjs
  src/module/data/actor/_module.mjs
  src/module/data/actor/_types.d.ts
  src/module/data/actor/base.mjs
  src/module/data/actor/hero.mjs
  src/module/data/item/_module.mjs
  src/module/data/item/_types.d.ts
  src/module/data/item/ability.mjs
  src/module/data/item/advancement.mjs
  src/module/data/item/career.mjs
  src/module/data/item/class.mjs
  src/module/data/item/project.mjs
  src/module/data/item/treasure.mjs
  src/module/data/message/saving-throw.mjs
  src/module/data/migrations.mjs
  src/module/data/pseudo-documents/advancements/item-grant-advancement.mjs
  src/module/data/settings/malice.mjs
  src/module/documents/actor.mjs
  src/module/documents/combat.mjs
  src/module/documents/item.mjs
  system.json
  templates/apps/document-input/actor-combat-stats-input.hbs
  templates/apps/power-roll-dialog.hbs
  templates/sheets/actor/hero-sheet/biography.hbs
  templates/sheets/actor/hero-sheet/equipment.hbs
  templates/sheets/actor/hero-sheet/features.hbs
  templates/sheets/actor/hero-sheet/header.hbs
  templates/sheets/actor/hero-sheet/projects.hbs
  templates/sheets/actor/hero-sheet/stats.hbs
  templates/sheets/item/partials/treasure.hbs
Labels: tech debt, data model

#875 861 - Troubadour skills
  src/packs/classes/Troubadour_AG8qTUvc61bqZ8Z8/class_Troubadour_JQxwKATOirc2weje.json
Labels: compendium

#877 861 - Elementalist Skill update
  src/packs/classes/Elementalist_SVgKuVoWB0FrXkal/class_Elementalist_QPAG5e362mFgQ1XW.json
Labels: compendium

#879 861 - Censor - Skills update
  src/packs/classes/Censor_ScAs0Dx7zp2fbcYH/class_Censor_YuuUbBMSvzN5IPLv.json
Labels: compendium

#885 861 - Censor Feature update for Domain
  src/packs/classes/Censor_ScAs0Dx7zp2fbcYH/class_Censor_YuuUbBMSvzN5IPLv.json
Labels: compendium

#883 Fury compendium Level 1 Update
  src/packs/abilities/Fury_NsE50OrdFsIk4ND2/Core_roGg2qsPifapFQEN/ability_Furious_Charge_DVAuB3PvTz4Q5Jmq.json
  src/packs/abilities/Fury_NsE50OrdFsIk4ND2/Core_roGg2qsPifapFQEN/ability_Lines_of_Force_6JirKNIULN4f4Ii0.json
  src/packs/abilities/Fury_NsE50OrdFsIk4ND2/Core_roGg2qsPifapFQEN/ability_Unearthly_Reflexes_CsIpGSv52h9optwM.json
  src/packs/abilities/Fury_NsE50OrdFsIk4ND2/Level_1_9cPQyQCXUIXRme9R/3_Ferocity_LezUXC0TBZaiXyoz/ability_Back__h8HLdTWTOgXRT7j7.json
  src/packs/abilities/Fury_NsE50OrdFsIk4ND2/Level_1_9cPQyQCXUIXRme9R/3_Ferocity_LezUXC0TBZaiXyoz/ability_Out_of_the_Way__2rom1WjJv9sw41Gn.json
  src/packs/abilities/Fury_NsE50OrdFsIk4ND2/Level_1_9cPQyQCXUIXRme9R/3_Ferocity_LezUXC0TBZaiXyoz/ability_Tide_of_Death_HrNe7XilXFUlWP1O.json
  src/packs/abilities/Fury_NsE50OrdFsIk4ND2/Level_1_9cPQyQCXUIXRme9R/3_Ferocity_LezUXC0TBZaiXyoz/ability_Your_Entrails_Are_Your_Extrails__1C3skjTgPyL1haOZ.json
  src/packs/abilities/Fury_NsE50OrdFsIk4ND2/Level_1_9cPQyQCXUIXRme9R/5_Ferocity_9iT8OXz2ZLsuyduZ/ability_Blood_for_Blood__CD27c6U0GUSIJPDT.json
  src/packs/abilities/Fury_NsE50OrdFsIk4ND2/Level_1_9cPQyQCXUIXRme9R/5_Ferocity_9iT8OXz2ZLsuyduZ/ability_Make_Peace_With_Your_God__b18zgjUQHcy1NaJ2.json
  src/packs/abilities/Fury_NsE50OrdFsIk4ND2/Level_1_9cPQyQCXUIXRme9R/5_Ferocity_9iT8OXz2ZLsuyduZ/ability_Thunder_Roar_FDhoFbrlPEEjPFAf.json
  src/packs/abilities/Fury_NsE50OrdFsIk4ND2/Level_1_9cPQyQCXUIXRme9R/5_Ferocity_9iT8OXz2ZLsuyduZ/ability_To_the_Uttermost_End_54IP1nIQiFvWmqYw.json
  src/packs/abilities/Fury_NsE50OrdFsIk4ND2/Level_1_9cPQyQCXUIXRme9R/Signature_Ability_rUcCzdXGsg5sJ0qQ/ability_Brutal_Slam_nHYS3JAp9m264mQO.json
  src/packs/abilities/Fury_NsE50OrdFsIk4ND2/Level_1_9cPQyQCXUIXRme9R/Signature_Ability_rUcCzdXGsg5sJ0qQ/ability_Hit_and_Run_0C5AhHHBvFVKSvzj.json
  src/packs/abilities/Fury_NsE50OrdFsIk4ND2/Level_1_9cPQyQCXUIXRme9R/Signature_Ability_rUcCzdXGsg5sJ0qQ/ability_Impaled__UsRhRq1x10cnyuWk.json
  src/packs/abilities/Fury_NsE50OrdFsIk4ND2/Level_1_9cPQyQCXUIXRme9R/Signature_Ability_rUcCzdXGsg5sJ0qQ/ability_To_the_Death__i3mzybXIZtT5F3GN.json
  src/packs/abilities/Fury_NsE50OrdFsIk4ND2/Level_1_9cPQyQCXUIXRme9R/folders_3_Ferocity_LezUXC0TBZaiXyoz.json
  src/packs/abilities/Fury_NsE50OrdFsIk4ND2/Level_1_9cPQyQCXUIXRme9R/folders_5_Ferocity_9iT8OXz2ZLsuyduZ.json
  src/packs/abilities/Fury_NsE50OrdFsIk4ND2/Level_1_9cPQyQCXUIXRme9R/folders_Signature_Ability_rUcCzdXGsg5sJ0qQ.json
  src/packs/abilities/Fury_NsE50OrdFsIk4ND2/folders_Core_roGg2qsPifapFQEN.json
  src/packs/abilities/Fury_NsE50OrdFsIk4ND2/folders_Level_1_9cPQyQCXUIXRme9R.json
  src/packs/abilities/folders_Fury_NsE50OrdFsIk4ND2.json
  src/packs/classes/Fury_xzykLzoRMsmgsRc8/Features_APQZ5fHFsMZFYLtD/feature_Beast_Shape_NtgaLC9isHfOmYFS.json
  src/packs/classes/Fury_xzykLzoRMsmgsRc8/Features_APQZ5fHFsMZFYLtD/feature_Ferocity_F8JyT7pwBmV3fYj2.json
  src/packs/classes/Fury_xzykLzoRMsmgsRc8/Features_APQZ5fHFsMZFYLtD/feature_Mighty_Leap_5Q9C9fs5pzztX6zJ.json
  src/packs/classes/Fury_xzykLzoRMsmgsRc8/Features_APQZ5fHFsMZFYLtD/feature_Primordial_Cunning_KUCByYUPKEzXFSW7.json
  src/packs/classes/Fury_xzykLzoRMsmgsRc8/Features_APQZ5fHFsMZFYLtD/feature_Primordial_Strength_JXioZdy4zIxskO72.json
  src/packs/classes/Fury_xzykLzoRMsmgsRc8/Features_APQZ5fHFsMZFYLtD/feature_Relentless_Hunter_nzPvUlVTEr1pXtfl.json
  src/packs/classes/Fury_xzykLzoRMsmgsRc8/Subclasses_rFvXxMH8zlkiyBYj/subclass_Berserker_UkRgXaZPKbt9VVp5.json
  src/packs/classes/Fury_xzykLzoRMsmgsRc8/Subclasses_rFvXxMH8zlkiyBYj/subclass_Reaver_k5tD7sSMemOrgeZl.json
  src/packs/classes/Fury_xzykLzoRMsmgsRc8/Subclasses_rFvXxMH8zlkiyBYj/subclass_Stormwight_OV3nfjXGHEzv4gUQ.json
  src/packs/classes/Fury_xzykLzoRMsmgsRc8/class_Fury_09NImezUFH1COsUX.json
  src/packs/classes/Fury_xzykLzoRMsmgsRc8/folders_Features_APQZ5fHFsMZFYLtD.json
  src/packs/classes/Fury_xzykLzoRMsmgsRc8/folders_Subclasses_rFvXxMH8zlkiyBYj.json
Labels: compendium

#887 Monsters and Monster Features Compendiums
  lang/en.json
  src/packs/classes/Fury_xzykLzoRMsmgsRc8/Subclasses_h4uckNiECaLtnwrO/subclass_Beserker_B3NMV8CrXpHmM8Qq.json
  src/packs/classes/Fury_xzykLzoRMsmgsRc8/Subclasses_h4uckNiECaLtnwrO/subclass_Reaver_j4f9lNPwXsTq59qb.json
  src/packs/classes/Fury_xzykLzoRMsmgsRc8/Subclasses_h4uckNiECaLtnwrO/subclass_Stormwight_h3PCUB9kRX6vtizw.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Dwarf_Malice_zR2leIjgt7VcKr8l/ability_Breaching_Charge_UsBSwuFSEE8zpLvM.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Dwarf_Malice_zR2leIjgt7VcKr8l/ability_Rappelling_Barrage_jeKfV8aI1rqyfkj4.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Dwarf_Malice_zR2leIjgt7VcKr8l/ability_Snaring_Line_iV1xZa3LFqKK1Xgu.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Goblin_Malice_vxOVWECtypuYigNy/ability_Goblin_Mode_4IYmvaux8p8vaWR6.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Goblin_Malice_vxOVWECtypuYigNy/ability_Swamp_Stink_vZMdicLidQzWMkgm.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Goblin_Malice_vxOVWECtypuYigNy/ability_Tiny_Stabs_Oa0MhwS1yeyeJ5qG.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Human_Malice_J4FsuL53D5JLS9q1/ability_Alchemical_Device_lVlwo9eIp8HBjfth.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Human_Malice_J4FsuL53D5JLS9q1/ability_Exploit_Opening_LYYyN9iD2PjepIFo.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Human_Malice_J4FsuL53D5JLS9q1/ability_Staying_Power_vxocmPyA9uKwrgEq.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Undead_Malice_dDubEbmnbWGRYlvn/ability_Dread_March_EzWvhVW1uXUmKhV5.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Undead_Malice_dDubEbmnbWGRYlvn/ability_Paranormal_Fling_da4wUZrJsfQ3EMZ3.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Undead_Malice_dDubEbmnbWGRYlvn/ability_Raevnous_Horde_gSoRE2jY58pVAtXf.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Undead_Malice_dDubEbmnbWGRYlvn/ability_The_Grasping__the_Hungry_5lQ9od53YUhk2eDw.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Werewolf_Malice_fZU2BCqzTRlAQ7SE/ability_Blood_In_Their_Eyes_FuYtAM2ldpDVCZ0X.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Werewolf_Malice_fZU2BCqzTRlAQ7SE/ability_Moonfall_3bU28XoTfPKJ5Rmk.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Werewolf_Malice_fZU2BCqzTRlAQ7SE/ability_Solo_Action_oOtG3UKHDajOXzU1.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/folders_Dwarf_Malice_zR2leIjgt7VcKr8l.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/folders_Goblin_Malice_vxOVWECtypuYigNy.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/folders_Human_Malice_J4FsuL53D5JLS9q1.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/folders_Undead_Malice_dDubEbmnbWGRYlvn.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/folders_Werewolf_Malice_fZU2BCqzTRlAQ7SE.json
  src/packs/monster-features/folders_Malice_Features_lr85fBx5XwieZOfH.json
  src/packs/monsters/Dwarves_aym4mi5JvyLiP0uV/npc_Dwarf_Stone_Whisperer_0wvOWjLAh0BeOvCp.json
  src/packs/monsters/Dwarves_aym4mi5JvyLiP0uV/npc_Dwarf_Trapper_yYKle19pHJYfKMfQ.json
  src/packs/monsters/Dwarves_aym4mi5JvyLiP0uV/npc_Dwarf_Warden_oOrOtSddf3x85DG3.json
  src/packs/monsters/Goblins_iEPVvWezLlidfEbg/npc_Bugbear_Channeler_ZaENuomw1aFn4Ffw.json
  src/packs/monsters/Goblins_iEPVvWezLlidfEbg/npc_Goblin_Assassin_6bpHvy0N4rObJBZq.json
  src/packs/monsters/Goblins_iEPVvWezLlidfEbg/npc_Goblin_Sniper_E637uEMv0INA5LPW.json
  src/packs/monsters/Goblins_iEPVvWezLlidfEbg/npc_Goblin_Spinecleaver_Mdk2jvvw26BaR1HL.json
  src/packs/monsters/Goblins_iEPVvWezLlidfEbg/npc_Goblin_Warrior_6SR8siFeC5lWUzoO.json
  src/packs/monsters/Humans_zBFE173ZFzlEPX1o/npc_Human_Brawler_DSEkUDEnQeS4LsWr.json
  src/packs/monsters/Humans_zBFE173ZFzlEPX1o/npc_Human_Guard_3sZIJ1aJRhMF6iK5.json
  src/packs/monsters/Humans_zBFE173ZFzlEPX1o/npc_Human_Raider_wTq3vb6iy92uivRO.json
  src/packs/monsters/Undead_Awroz7YqtpURNlF5/npc_Ghoul_DXM53Md2acyvSVNo.json
  src/packs/monsters/Undead_Awroz7YqtpURNlF5/npc_Skeleton_2h6PhbOuGeraFQZm.json
  src/packs/monsters/Undead_Awroz7YqtpURNlF5/npc_Zombie_G7bFOGyqq0Z4xJ7F.json
  src/packs/monsters/Werebeast_lOWAfMfJap4eXijF/npc_Werewolf_0gfYrTzOgWNi0QBy.json
  src/packs/monsters/folders_Dwarves_aym4mi5JvyLiP0uV.json
  src/packs/monsters/folders_Goblins_iEPVvWezLlidfEbg.json
  src/packs/monsters/folders_Humans_zBFE173ZFzlEPX1o.json
  src/packs/monsters/folders_Undead_Awroz7YqtpURNlF5.json
  src/packs/monsters/folders_Werebeast_lOWAfMfJap4eXijF.json
  system.json
  tools/pushLDBtoJSON.mjs
Labels: compendium

#897 Fury compendium
  src/packs/abilities/Fury_NsE50OrdFsIk4ND2/Stormwight_Kit_Abilities_1LBQVhBGG8TGV7Nu/ability_Aspect_of_the_Wild_1Syy7WKXEGvFRO2o.json
  src/packs/abilities/Fury_NsE50OrdFsIk4ND2/Stormwight_Kit_Abilities_1LBQVhBGG8TGV7Nu/ability_Bear_Claws_NkmO3IZcwqQUowkY.json
  src/packs/abilities/Fury_NsE50OrdFsIk4ND2/Stormwight_Kit_Abilities_1LBQVhBGG8TGV7Nu/ability_Driving_Pounce_PO5DtFuHI0qWvhIu.json
  src/packs/abilities/Fury_NsE50OrdFsIk4ND2/Stormwight_Kit_Abilities_1LBQVhBGG8TGV7Nu/ability_Unbalancing_Attack_G8AKYqiObZX16VmX.json
  src/packs/abilities/Fury_NsE50OrdFsIk4ND2/Stormwight_Kit_Abilities_1LBQVhBGG8TGV7Nu/ability_Wing_Buffet_9hXHrtWYvWdrbFc7.json
  src/packs/abilities/Fury_NsE50OrdFsIk4ND2/folders_Stormwight_Kit_Abilities_1LBQVhBGG8TGV7Nu.json
  src/packs/classes/Fury_xzykLzoRMsmgsRc8/Stormwight_Kits_foJLji1bQhEXFvKE/kit_Boren_1cUaanjbFmpCqBzr.json
  src/packs/classes/Fury_xzykLzoRMsmgsRc8/Stormwight_Kits_foJLji1bQhEXFvKE/kit_Corven_sdo1ifNShWUMR4bv.json
  src/packs/classes/Fury_xzykLzoRMsmgsRc8/Stormwight_Kits_foJLji1bQhEXFvKE/kit_Raden_0Q0ZH8GovfOpJR9V.json
  src/packs/classes/Fury_xzykLzoRMsmgsRc8/Stormwight_Kits_foJLji1bQhEXFvKE/kit_Vuken_uwkXfnDmiQHgfYqn.json
  src/packs/classes/Fury_xzykLzoRMsmgsRc8/Subclasses_rFvXxMH8zlkiyBYj/subclass_Stormwight_OV3nfjXGHEzv4gUQ.json
  src/packs/classes/Fury_xzykLzoRMsmgsRc8/class_Fury_09NImezUFH1COsUX.json
  src/packs/classes/Fury_xzykLzoRMsmgsRc8/folders_Stormwight_Kits_foJLji1bQhEXFvKE.json
Labels: compendium

#904 Conduit structure update for L1
  src/packs/classes/Conduit_1KqNzItDbgiZLVOP/Features_CQqSbxZtbGl6Oz1I/feature_Conduit_Ward_cTQVqRLw1x6bk9ZD.json
  src/packs/classes/Conduit_1KqNzItDbgiZLVOP/Features_CQqSbxZtbGl6Oz1I/feature_Deity_and_Domains_t71ffENhQrQ8e59X.json
  src/packs/classes/Conduit_1KqNzItDbgiZLVOP/Features_CQqSbxZtbGl6Oz1I/feature_Prayer_vfV23FkmV94GLuBI.json
  src/packs/classes/Conduit_1KqNzItDbgiZLVOP/class_Conduit_acA2B3ecGohNxhnb.json
Labels: compendium

#905 Censor L1 Structure Update
  src/packs/classes/Censor_ScAs0Dx7zp2fbcYH/Features_ZaQazDd1CJFiw3wK/feature_Deity_and_Domains_vwqIB4UTc6ow6mXt.json
  src/packs/classes/Censor_ScAs0Dx7zp2fbcYH/class_Censor_YuuUbBMSvzN5IPLv.json
Labels: compendium

#910 Tactician L1 cleanup update
  src/module/applications/sheets/hero-sheet.mjs
  src/module/applications/sheets/item-sheet.mjs
  src/packs/abilities/Tactician_If39E6GsmUaOGSIx/Level_1_X6NCcq2MeD0PO9m7/3_Focus_rTZbhhWgJJlUsz0q/ability_Battle_Cry_tNLgOK3NPEmKPT8N.json
  src/packs/abilities/Tactician_If39E6GsmUaOGSIx/Level_1_X6NCcq2MeD0PO9m7/3_Focus_rTZbhhWgJJlUsz0q/ability_Concussive_Strike_S3iGPafawIlrjPLQ.json
  src/packs/abilities/Tactician_If39E6GsmUaOGSIx/Level_1_X6NCcq2MeD0PO9m7/3_Focus_rTZbhhWgJJlUsz0q/ability_Inspiring_Strike_yYQqS6yLeI1vSq5F.json
  src/packs/abilities/Tactician_If39E6GsmUaOGSIx/Level_1_X6NCcq2MeD0PO9m7/3_Focus_rTZbhhWgJJlUsz0q/ability_Squad__Forward__KgIMq4mGRFmij4yK.json
  src/packs/abilities/Tactician_If39E6GsmUaOGSIx/Level_1_X6NCcq2MeD0PO9m7/5_Focus_qqy4D1GA6B5jsNJH/ability_Hammer_And_Anvil_lNJCFKdUV1fjYmhC.json
  src/packs/abilities/Tactician_If39E6GsmUaOGSIx/Level_1_X6NCcq2MeD0PO9m7/5_Focus_qqy4D1GA6B5jsNJH/ability_Now__tpi0fKQDK1dEDwWw.json
  src/packs/abilities/Tactician_If39E6GsmUaOGSIx/Level_1_X6NCcq2MeD0PO9m7/5_Focus_qqy4D1GA6B5jsNJH/ability_The_Mind_Game_qHiPuCKH4WNHCYgO.json
  src/packs/abilities/Tactician_If39E6GsmUaOGSIx/Level_1_X6NCcq2MeD0PO9m7/5_Focus_qqy4D1GA6B5jsNJH/ability_This_Is_What_We_Planned_For_eiwrW9TL342wPNea.json
  src/packs/abilities/Tactician_If39E6GsmUaOGSIx/Level_2_V8sovzcihb87srSY/Insurgent_3vTHdH8nZgeuLfMh/ability_Fog_of_War_onCIPNSevgNVx7wF.json
  src/packs/abilities/Tactician_If39E6GsmUaOGSIx/Level_2_V8sovzcihb87srSY/Insurgent_3vTHdH8nZgeuLfMh/ability_Try_Me_Instead_Dtlh3rkTZZ6mNwNu.json
  src/packs/abilities/Tactician_If39E6GsmUaOGSIx/Level_2_V8sovzcihb87srSY/Mastermind_Xyfx7wKsdZmJloDI/ability_I_ve_Got_Your_Back_auSGLJVN4CdVjtOd.json
  src/packs/abilities/Tactician_If39E6GsmUaOGSIx/Level_2_V8sovzcihb87srSY/Mastermind_Xyfx7wKsdZmJloDI/ability_Targets_of_Opportunity_zLKvoysqHElI2q54.json
  src/packs/abilities/Tactician_If39E6GsmUaOGSIx/Level_2_V8sovzcihb87srSY/Vanguard_cFVtfkYEyx9FXpdn/ability_No_Dying_On_My_Watch_ZtMBjvDFJQYVkdmt.json
  src/packs/abilities/Tactician_If39E6GsmUaOGSIx/Level_2_V8sovzcihb87srSY/Vanguard_cFVtfkYEyx9FXpdn/ability_Squad__On_Me__kT1PdUuDnWdd8E5j.json
  src/packs/abilities/Tactician_If39E6GsmUaOGSIx/Level_3_7VdM2hly01Uzll22/7_Focus_l00ZETX9CthoXQ2L/ability_Frontal_Assault_5bp7i0Ohsqjh9V8b.json
  src/packs/abilities/Tactician_If39E6GsmUaOGSIx/Level_3_7VdM2hly01Uzll22/7_Focus_l00ZETX9CthoXQ2L/ability_Hit__Em_Hard__Oa2nhKmYgCO8ko1e.json
  src/packs/abilities/Tactician_If39E6GsmUaOGSIx/Level_3_7VdM2hly01Uzll22/7_Focus_l00ZETX9CthoXQ2L/ability_Rout_7nIlMpcNp099D7qU.json
  src/packs/abilities/Tactician_If39E6GsmUaOGSIx/Level_3_7VdM2hly01Uzll22/7_Focus_l00ZETX9CthoXQ2L/ability_Stay_Strong__and_Focus__LK3bFBBEUL44o7FG.json
  src/packs/abilities/Tactician_If39E6GsmUaOGSIx/Triggered_GyUC1qQdNz5Ia8zm/Insurgent_G3UBn4UI2HQ6Kdom/ability_Advanced_Tactics_Ww4AaolCBsUJMeDA.json
  src/packs/abilities/Tactician_If39E6GsmUaOGSIx/Triggered_GyUC1qQdNz5Ia8zm/Mastermind_Eqy2kIFHvKosaYRA/ability_Overwatch_44Pkw50vZeqyqtiQ.json
  src/packs/abilities/Tactician_If39E6GsmUaOGSIx/Triggered_GyUC1qQdNz5Ia8zm/Vanguard_VhYOjPek7vcYHAgA/ability_Parry_NSOHEMtSDSy8qwIh.json
  src/packs/abilities/Tactician_If39E6GsmUaOGSIx/Triggered_GyUC1qQdNz5Ia8zm/folders_Insurgent_G3UBn4UI2HQ6Kdom.json
  src/packs/abilities/Tactician_If39E6GsmUaOGSIx/Triggered_GyUC1qQdNz5Ia8zm/folders_Mastermind_Eqy2kIFHvKosaYRA.json
  src/packs/abilities/Tactician_If39E6GsmUaOGSIx/Triggered_GyUC1qQdNz5Ia8zm/folders_Vanguard_VhYOjPek7vcYHAgA.json
  src/packs/abilities/Tactician_If39E6GsmUaOGSIx/folders_Triggered_GyUC1qQdNz5Ia8zm.json
  src/packs/classes/Tactician_kCN3c3aC6ziHDp5c/Features_78pbwV8U2xiEUz57/Insurgent_71KLGY8ZFgHTFLl5/feature_Covert_Operations_ajeWFtiJThAAAVQc.json
  src/packs/classes/Tactician_kCN3c3aC6ziHDp5c/Features_78pbwV8U2xiEUz57/Mastermind_0tLAXLNV7O52athN/feature_Studied_Commander_X8RA9Fp6vFF5AeKR.json
  src/packs/classes/Tactician_kCN3c3aC6ziHDp5c/Features_78pbwV8U2xiEUz57/Vanguard_70HZxf7jq2w3W56e/feature_Commanding_Presence_wdOsstaPrLX5WcVa.json
  src/packs/classes/Tactician_kCN3c3aC6ziHDp5c/Features_78pbwV8U2xiEUz57/feature_Field_Arsenal_dNGmfuNuaML5TRQL.json
  src/packs/classes/Tactician_kCN3c3aC6ziHDp5c/Features_78pbwV8U2xiEUz57/feature_Focus_BsbaqvmoNmQLIhkS.json
  src/packs/classes/Tactician_kCN3c3aC6ziHDp5c/Features_78pbwV8U2xiEUz57/folders_Insurgent_71KLGY8ZFgHTFLl5.json
  src/packs/classes/Tactician_kCN3c3aC6ziHDp5c/Features_78pbwV8U2xiEUz57/folders_Mastermind_0tLAXLNV7O52athN.json
  src/packs/classes/Tactician_kCN3c3aC6ziHDp5c/Features_78pbwV8U2xiEUz57/folders_Vanguard_70HZxf7jq2w3W56e.json
  src/packs/classes/Tactician_kCN3c3aC6ziHDp5c/Subclasses_86F9T9t6YK1WafzV/Insurgent_aG0eTj9GqEEeqEoT/subclass_Insurgent_VfwdbL1GG2Dx0zv7.json
  src/packs/classes/Tactician_kCN3c3aC6ziHDp5c/Subclasses_86F9T9t6YK1WafzV/Mastermind_xsehSq9937xK2UPT/subclass_Mastermind_aYjVEZyiYqtdGGPS.json
  src/packs/classes/Tactician_kCN3c3aC6ziHDp5c/Subclasses_86F9T9t6YK1WafzV/Vanguard_PMlcsdUN9j3AmTxe/subclass_Vanguard_OjWhetKz8boQxExU.json
  src/packs/classes/Tactician_kCN3c3aC6ziHDp5c/Subclasses_86F9T9t6YK1WafzV/folders_Insurgent_aG0eTj9GqEEeqEoT.json
  src/packs/classes/Tactician_kCN3c3aC6ziHDp5c/Subclasses_86F9T9t6YK1WafzV/folders_Mastermind_xsehSq9937xK2UPT.json
  src/packs/classes/Tactician_kCN3c3aC6ziHDp5c/Subclasses_86F9T9t6YK1WafzV/folders_Vanguard_PMlcsdUN9j3AmTxe.json
  src/packs/classes/Tactician_kCN3c3aC6ziHDp5c/class_Tactician_Y6rtfW6EfHszGqhG.json
  src/styles/system/applications/sheets/pseudo-documents.css
Labels: compendium

#908 Null First Level Compendium
  src/packs/abilities/Null_3CEvbkuuVzQlvD3a/Core_CZ81nOfb3FIMsshV/ability_Inertial_Shield_5I2gPFF6EydNNqbV.json
  src/packs/abilities/Null_3CEvbkuuVzQlvD3a/Core_CZ81nOfb3FIMsshV/ability_Null_Field_4e6uHozJPeiF4lMy.json
  src/packs/abilities/Null_3CEvbkuuVzQlvD3a/Level_1_qCMWeeDAnmclIfr3/3_Discipline_YprdZFn9QNUmZlNk/ability_Chronal_Spike_6VgiUFDvsHSeH6yD.json
  src/packs/abilities/Null_3CEvbkuuVzQlvD3a/Level_1_qCMWeeDAnmclIfr3/3_Discipline_YprdZFn9QNUmZlNk/ability_Psychic_Pulse_2OEGwX6yQsXXPOLX.json
  src/packs/abilities/Null_3CEvbkuuVzQlvD3a/Level_1_qCMWeeDAnmclIfr3/3_Discipline_YprdZFn9QNUmZlNk/ability_Relentless_Nemesis_cZoHy6IINhi8yoky.json
  src/packs/abilities/Null_3CEvbkuuVzQlvD3a/Level_1_qCMWeeDAnmclIfr3/3_Discipline_YprdZFn9QNUmZlNk/ability_Stunning_Blow_2ub2LyPLApe8ymjv.json
  src/packs/abilities/Null_3CEvbkuuVzQlvD3a/Level_1_qCMWeeDAnmclIfr3/5_Discipline_UZgbx63EYEsGulHG/ability_A_Squad_Unto_Myself_1c96YlKduX6iZmIp.json
  src/packs/abilities/Null_3CEvbkuuVzQlvD3a/Level_1_qCMWeeDAnmclIfr3/5_Discipline_UZgbx63EYEsGulHG/ability_Arcane_Disruptor_zUmoW31KJXC3R1j4.json
  src/packs/abilities/Null_3CEvbkuuVzQlvD3a/Level_1_qCMWeeDAnmclIfr3/5_Discipline_UZgbx63EYEsGulHG/ability_Impart_Force_ddQzesCNaNw06k3J.json
  src/packs/abilities/Null_3CEvbkuuVzQlvD3a/Level_1_qCMWeeDAnmclIfr3/5_Discipline_UZgbx63EYEsGulHG/ability_Phase_Strike_eaR9Hq5FgIZUS2pv.json
  src/packs/abilities/Null_3CEvbkuuVzQlvD3a/Level_1_qCMWeeDAnmclIfr3/Signature_BiLZLDEQFlNmxUnT/ability_Dance_of_Blows_3IrtTlIVtyyid9fS.json
  src/packs/abilities/Null_3CEvbkuuVzQlvD3a/Level_1_qCMWeeDAnmclIfr3/Signature_BiLZLDEQFlNmxUnT/ability_Faster_Than_the_Eye_e43PLaizLsTieayM.json
  src/packs/abilities/Null_3CEvbkuuVzQlvD3a/Level_1_qCMWeeDAnmclIfr3/Signature_BiLZLDEQFlNmxUnT/ability_Inertial_Step_2QIO15DZh2XM3YUI.json
  src/packs/abilities/Null_3CEvbkuuVzQlvD3a/Level_1_qCMWeeDAnmclIfr3/Signature_BiLZLDEQFlNmxUnT/ability_Joint_Lock_kJaluygXdksbgNtA.json
  src/packs/abilities/Null_3CEvbkuuVzQlvD3a/Level_1_qCMWeeDAnmclIfr3/Signature_BiLZLDEQFlNmxUnT/ability_Kinetic_Strike_FqJWr6a2mVB4vXGJ.json
  src/packs/abilities/Null_3CEvbkuuVzQlvD3a/Level_1_qCMWeeDAnmclIfr3/Signature_BiLZLDEQFlNmxUnT/ability_Magnetic_Strike_8ApC33xl0KqVBSsV.json
  src/packs/abilities/Null_3CEvbkuuVzQlvD3a/Level_1_qCMWeeDAnmclIfr3/Signature_BiLZLDEQFlNmxUnT/ability_Phase_Inversion_Strike_3hGD5Y0bdbna4cUt.json
  src/packs/abilities/Null_3CEvbkuuVzQlvD3a/Level_1_qCMWeeDAnmclIfr3/Signature_BiLZLDEQFlNmxUnT/ability_Pressure_Points_PL7BMKE4tcW9GjJF.json
  src/packs/abilities/Null_3CEvbkuuVzQlvD3a/Level_1_qCMWeeDAnmclIfr3/folders_3_Discipline_YprdZFn9QNUmZlNk.json
  src/packs/abilities/Null_3CEvbkuuVzQlvD3a/Level_1_qCMWeeDAnmclIfr3/folders_5_Discipline_UZgbx63EYEsGulHG.json
  src/packs/abilities/Null_3CEvbkuuVzQlvD3a/Level_1_qCMWeeDAnmclIfr3/folders_Signature_BiLZLDEQFlNmxUnT.json
  src/packs/abilities/Null_3CEvbkuuVzQlvD3a/folders_Core_CZ81nOfb3FIMsshV.json
  src/packs/abilities/Null_3CEvbkuuVzQlvD3a/folders_Level_1_qCMWeeDAnmclIfr3.json
  src/packs/abilities/folders_Null_3CEvbkuuVzQlvD3a.json
  src/packs/classes/Null_ZeRU45NGZJpsKjIx/Features_oJjd2rCtL3HYUh8r/feature_Chronokinetic_Mastery_eGTpq8aSbCUvFhEq.json
  src/packs/classes/Null_ZeRU45NGZJpsKjIx/Features_oJjd2rCtL3HYUh8r/feature_Cryokinetic_Mastery_TseUqw7uV5nOcKOZ.json
  src/packs/classes/Null_ZeRU45NGZJpsKjIx/Features_oJjd2rCtL3HYUh8r/feature_Discipline_NkpEnSzYHrXquyNx.json
  src/packs/classes/Null_ZeRU45NGZJpsKjIx/Features_oJjd2rCtL3HYUh8r/feature_Metakinetic_Mastery_FuPWCTJdGWNEOmTe.json
  src/packs/classes/Null_ZeRU45NGZJpsKjIx/Features_oJjd2rCtL3HYUh8r/feature_Null_Speed_45VLimMEElLDILBx.json
  src/packs/classes/Null_ZeRU45NGZJpsKjIx/Features_oJjd2rCtL3HYUh8r/feature_Psionic_Martial_Arts_ah2ffMrhwlX1AtTK.json
  src/packs/classes/Null_ZeRU45NGZJpsKjIx/Psionic_Augmentations_TNk6pcZd6C0ioWM5/feature_Density_Augmentation_6n5LrSg6JPnZEHvV.json
  src/packs/classes/Null_ZeRU45NGZJpsKjIx/Psionic_Augmentations_TNk6pcZd6C0ioWM5/feature_Force_Augmentation_0lOE0o9Fq4SXbBlu.json
  src/packs/classes/Null_ZeRU45NGZJpsKjIx/Psionic_Augmentations_TNk6pcZd6C0ioWM5/feature_Speed_Augmentation_rfV6DXw5jgoa9YCF.json
  src/packs/classes/Null_ZeRU45NGZJpsKjIx/Subclasses_dPBywq1BJXheX3ez/subclass_Chronokinetic_7AYn4Us1eUSVAK57.json
  src/packs/classes/Null_ZeRU45NGZJpsKjIx/Subclasses_dPBywq1BJXheX3ez/subclass_Cryokinetic_qAuOMzb8UDpGspSu.json
  src/packs/classes/Null_ZeRU45NGZJpsKjIx/Subclasses_dPBywq1BJXheX3ez/subclass_Metakinetic_Np5tks1bN3bTWPr8.json
  src/packs/classes/Null_ZeRU45NGZJpsKjIx/class_Null_ovVqD2Zj5csqOjf7.json
  src/packs/classes/Null_ZeRU45NGZJpsKjIx/folders_Features_oJjd2rCtL3HYUh8r.json
  src/packs/classes/Null_ZeRU45NGZJpsKjIx/folders_Psionic_Augmentations_TNk6pcZd6C0ioWM5.json
  src/packs/classes/Null_ZeRU45NGZJpsKjIx/folders_Subclasses_dPBywq1BJXheX3ez.json
Labels: compendium

#912 Supernatural Perks and Abilities
  src/packs/abilities/Perks_inlCRuoVqrlKipgA/ability_Arcane_Trick_8vhOKFQKwAgyjXRr.json
  src/packs/abilities/Perks_inlCRuoVqrlKipgA/ability_Invisible_Force_tbK37ZbePfblneBD.json
  src/packs/abilities/Perks_inlCRuoVqrlKipgA/ability_Psychic_Whisper_0B2OMhIZm2YulfCT.json
  src/packs/abilities/folders_Perks_inlCRuoVqrlKipgA.json
  src/packs/character-options/Perks_tb9IiWSEZfQYFh2p/Supernatural_pVVpFm5ejHsSsv3V/perk_Arcane_Trick_5a7QyGkwVXB90DvS.json
  src/packs/character-options/Perks_tb9IiWSEZfQYFh2p/Supernatural_pVVpFm5ejHsSsv3V/perk_Creature_Sense_9nRguvja2w4qDoCD.json
  src/packs/character-options/Perks_tb9IiWSEZfQYFh2p/Supernatural_pVVpFm5ejHsSsv3V/perk_Familiar_CMUyZy6A1iIp0ThV.json
  src/packs/character-options/Perks_tb9IiWSEZfQYFh2p/Supernatural_pVVpFm5ejHsSsv3V/perk_Invisible_Force_0IUib19ayIH277to.json
  src/packs/character-options/Perks_tb9IiWSEZfQYFh2p/Supernatural_pVVpFm5ejHsSsv3V/perk_Psychic_Whisper_MRqWsGDoz9AC9Gzq.json
  src/packs/character-options/Perks_tb9IiWSEZfQYFh2p/Supernatural_pVVpFm5ejHsSsv3V/perk_Ritualist_MAfuqMLlNFpSDcC3.json
  src/packs/character-options/Perks_tb9IiWSEZfQYFh2p/Supernatural_pVVpFm5ejHsSsv3V/perk_Thingspeaker_E44Fy7YSJyksrbEP.json
  src/packs/character-options/Perks_tb9IiWSEZfQYFh2p/folders_Supernatural_pVVpFm5ejHsSsv3V.json
  src/packs/monsters/Summons_SN3x5ZfzmkqqFmny/npc_Familiar_cBkB3TyhBE1UsNGM.json
  src/packs/monsters/folders_Summons_SN3x5ZfzmkqqFmny.json
Labels: compendium

#911 Talent Compendium 1st part
  src/packs/abilities/Talent_W4G9rOoBWQqffx2T/1st_Level_OwLGXyW6518i4S2O/folders_3_Clarity_DDQszc7f2JZLgbRD.json
  src/packs/abilities/Talent_W4G9rOoBWQqffx2T/1st_Level_OwLGXyW6518i4S2O/folders_5_Clarity_TdWMC0DlWhkMW0jl.json
  src/packs/abilities/Talent_W4G9rOoBWQqffx2T/1st_Level_OwLGXyW6518i4S2O/folders_Signature_Hua1VikI1490yY1R.json
  src/packs/abilities/Talent_W4G9rOoBWQqffx2T/Core_iexBQBs46QdCPaeD/Chronopathy_6FyJBW2D9ZCcMO4l/ability_Accelerate_dmk0jCUh8JaKmQas.json
  src/packs/abilities/Talent_W4G9rOoBWQqffx2T/Core_iexBQBs46QdCPaeD/Chronopathy_6FyJBW2D9ZCcMO4l/ability_Again_zy367OiF8Di2eiQx.json
  src/packs/abilities/Talent_W4G9rOoBWQqffx2T/Core_iexBQBs46QdCPaeD/Telekinesis_d8jdUpNgJPchnQ4N/ability_Minor_Telekinesis_kmefCdTraNKL9GvW.json
  src/packs/abilities/Talent_W4G9rOoBWQqffx2T/Core_iexBQBs46QdCPaeD/Telekinesis_d8jdUpNgJPchnQ4N/ability_Repel_xuXuX9ENl2uwdJVK.json
  src/packs/abilities/Talent_W4G9rOoBWQqffx2T/Core_iexBQBs46QdCPaeD/Telepathy_zXn8C3Qc3SpZTcY9/ability_Feedback_Loop_qFmIJY6Wtp6NNely.json
  src/packs/abilities/Talent_W4G9rOoBWQqffx2T/Core_iexBQBs46QdCPaeD/Telepathy_zXn8C3Qc3SpZTcY9/ability_Remote_Assistance_taV9u9coxHU7ABbK.json
  src/packs/abilities/Talent_W4G9rOoBWQqffx2T/Core_iexBQBs46QdCPaeD/ability_Mind_Spike_2MdIFxCPWqTUE7JT.json
  src/packs/abilities/Talent_W4G9rOoBWQqffx2T/Core_iexBQBs46QdCPaeD/folders_Chronopathy_6FyJBW2D9ZCcMO4l.json
  src/packs/abilities/Talent_W4G9rOoBWQqffx2T/Core_iexBQBs46QdCPaeD/folders_Telekinesis_d8jdUpNgJPchnQ4N.json
  src/packs/abilities/Talent_W4G9rOoBWQqffx2T/Core_iexBQBs46QdCPaeD/folders_Telepathy_zXn8C3Qc3SpZTcY9.json
  src/packs/abilities/Talent_W4G9rOoBWQqffx2T/folders_1st_Level_OwLGXyW6518i4S2O.json
  src/packs/abilities/Talent_W4G9rOoBWQqffx2T/folders_Core_iexBQBs46QdCPaeD.json
  src/packs/abilities/folders_Talent_W4G9rOoBWQqffx2T.json
  src/packs/classes/Censor_ScAs0Dx7zp2fbcYH/class_Censor_YuuUbBMSvzN5IPLv.json
  src/packs/classes/Conduit_1KqNzItDbgiZLVOP/class_Conduit_acA2B3ecGohNxhnb.json
  src/packs/classes/Elementalist_SVgKuVoWB0FrXkal/class_Elementalist_QPAG5e362mFgQ1XW.json
  src/packs/classes/Fury_xzykLzoRMsmgsRc8/class_Fury_09NImezUFH1COsUX.json
  src/packs/classes/Null_ZeRU45NGZJpsKjIx/class_Null_ovVqD2Zj5csqOjf7.json
  src/packs/classes/Shadow_ngcpmEclU2UUJbz4/class_Shadow_08pJ0i8AwjMsrKO1.json
  src/packs/classes/Tactician_kCN3c3aC6ziHDp5c/class_Tactician_Y6rtfW6EfHszGqhG.json
  src/packs/classes/Talent_Q4pvMWEIONrsqHp0/Features_oBlC3EZdWggPWyRn/Psionic_Augmentations_1b95uSyyQlEuFh6G/feature_Battle_Augmentation_EozglrAwvYRQw5s8.json
  src/packs/classes/Talent_Q4pvMWEIONrsqHp0/Features_oBlC3EZdWggPWyRn/Psionic_Augmentations_1b95uSyyQlEuFh6G/feature_Density_Augmentation_jF9Viz80YHQBW2QU.json
  src/packs/classes/Talent_Q4pvMWEIONrsqHp0/Features_oBlC3EZdWggPWyRn/Psionic_Augmentations_1b95uSyyQlEuFh6G/feature_Distance_Augmentation_mwwEAQ5s5j8sBr1s.json
  src/packs/classes/Talent_Q4pvMWEIONrsqHp0/Features_oBlC3EZdWggPWyRn/Psionic_Augmentations_1b95uSyyQlEuFh6G/feature_Force_Augmentation_cnP9ReGko79M4Xex.json
  src/packs/classes/Talent_Q4pvMWEIONrsqHp0/Features_oBlC3EZdWggPWyRn/Psionic_Augmentations_1b95uSyyQlEuFh6G/feature_Speed_Augmentation_xxfGODNK1x9MS65e.json
  src/packs/classes/Talent_Q4pvMWEIONrsqHp0/Features_oBlC3EZdWggPWyRn/Talent_Ward_gcNzjYzqaDJTbC7w/feature_Entropy_Ward_SrNnnIB1IhdIqQv9.json
  src/packs/classes/Talent_Q4pvMWEIONrsqHp0/Features_oBlC3EZdWggPWyRn/Talent_Ward_gcNzjYzqaDJTbC7w/feature_Repulsive_Ward_9UZdFGEYlhAt8eBX.json
  src/packs/classes/Talent_Q4pvMWEIONrsqHp0/Features_oBlC3EZdWggPWyRn/Talent_Ward_gcNzjYzqaDJTbC7w/feature_Steel_Ward_VKW9qDHCunLecjtl.json
  src/packs/classes/Talent_Q4pvMWEIONrsqHp0/Features_oBlC3EZdWggPWyRn/Talent_Ward_gcNzjYzqaDJTbC7w/feature_Vanishing_Ward_H0KjiRC8GNA5WBwe.json
  src/packs/classes/Talent_Q4pvMWEIONrsqHp0/Features_oBlC3EZdWggPWyRn/feature_Clarity_and_Strain_MkF7O4vi1bEV6zJK.json
  src/packs/classes/Talent_Q4pvMWEIONrsqHp0/Features_oBlC3EZdWggPWyRn/feature_Telepathic_Speech_0VZoAfHp9CM0jLUJ.json
  src/packs/classes/Talent_Q4pvMWEIONrsqHp0/Features_oBlC3EZdWggPWyRn/folders_Psionic_Augmentations_1b95uSyyQlEuFh6G.json
  src/packs/classes/Talent_Q4pvMWEIONrsqHp0/Features_oBlC3EZdWggPWyRn/folders_Talent_Ward_gcNzjYzqaDJTbC7w.json
  src/packs/classes/Talent_Q4pvMWEIONrsqHp0/Subclasses_TnmRNfK9uXQYMdQ6/subclass_Chronopathy_1L7ct02Be0Hr9Tpw.json
  src/packs/classes/Talent_Q4pvMWEIONrsqHp0/Subclasses_TnmRNfK9uXQYMdQ6/subclass_Telekinesis_g7kPqIxwJB8bqm78.json
  src/packs/classes/Talent_Q4pvMWEIONrsqHp0/Subclasses_TnmRNfK9uXQYMdQ6/subclass_Telepathy_YvcB53u33Uhpt1wQ.json
  src/packs/classes/Talent_Q4pvMWEIONrsqHp0/class_Talent_iEnFxX8jUWZTthLp.json
  src/packs/classes/Talent_Q4pvMWEIONrsqHp0/folders_Features_oBlC3EZdWggPWyRn.json
  src/packs/classes/Talent_Q4pvMWEIONrsqHp0/folders_Subclasses_TnmRNfK9uXQYMdQ6.json
  src/packs/classes/Troubadour_AG8qTUvc61bqZ8Z8/class_Troubadour_JQxwKATOirc2weje.json
Labels: compendium

#909 Level 2 Compendium items for Troubadour (#778)
  src/module/applications/sheets/item-sheet.mjs
  src/packs/abilities/Troubadour_MbinHVcKZQ9kJlOA/2nd_Level_nEGmdPsFIQHuAySh/Auteur_3BZqiCncwP6AxaqT/ability_Guest_Star_xI7tndxvMyAYyav0.json
  src/packs/abilities/Troubadour_MbinHVcKZQ9kJlOA/2nd_Level_nEGmdPsFIQHuAySh/Auteur_3BZqiCncwP6AxaqT/ability_Twist_at_the_End_XA7t1YMGoOk6Dwxs.json
  src/packs/abilities/Troubadour_MbinHVcKZQ9kJlOA/2nd_Level_nEGmdPsFIQHuAySh/Duelist_mHEoUeiihUz4aLds/ability_Classic_Chandelier_Stunt_kLZMMYiWZiJWlFTt.json
  src/packs/abilities/Troubadour_MbinHVcKZQ9kJlOA/2nd_Level_nEGmdPsFIQHuAySh/Duelist_mHEoUeiihUz4aLds/ability_En_Garde__MyHevRDBuDyivtDh.json
  src/packs/abilities/Troubadour_MbinHVcKZQ9kJlOA/2nd_Level_nEGmdPsFIQHuAySh/Virtuoso_p18OS5xNYXdq6A7b/ability_Encore_GI8mca3sDZnMHG2W.json
  src/packs/abilities/Troubadour_MbinHVcKZQ9kJlOA/2nd_Level_nEGmdPsFIQHuAySh/Virtuoso_p18OS5xNYXdq6A7b/ability_Tough_Crowd_rDvCDejt99L0Du0f.json
  src/packs/abilities/Troubadour_MbinHVcKZQ9kJlOA/2nd_Level_nEGmdPsFIQHuAySh/folders_Auteur_3BZqiCncwP6AxaqT.json
  src/packs/abilities/Troubadour_MbinHVcKZQ9kJlOA/2nd_Level_nEGmdPsFIQHuAySh/folders_Duelist_mHEoUeiihUz4aLds.json
  src/packs/abilities/Troubadour_MbinHVcKZQ9kJlOA/2nd_Level_nEGmdPsFIQHuAySh/folders_Virtuoso_p18OS5xNYXdq6A7b.json
  src/packs/abilities/Troubadour_MbinHVcKZQ9kJlOA/folders_2nd_Level_nEGmdPsFIQHuAySh.json
  src/packs/classes/Null_ZeRU45NGZJpsKjIx/Features_oJjd2rCtL3HYUh8r/feature_Null_Speed_45VLimMEElLDILBx.json
  src/packs/classes/Null_ZeRU45NGZJpsKjIx/Features_oJjd2rCtL3HYUh8r/feature_Psionic_Martial_Arts_ah2ffMrhwlX1AtTK.json
  src/packs/classes/Null_ZeRU45NGZJpsKjIx/Psionic_Augmentations_TNk6pcZd6C0ioWM5/feature_Density_Augmentation_6n5LrSg6JPnZEHvV.json
  src/packs/classes/Null_ZeRU45NGZJpsKjIx/Psionic_Augmentations_TNk6pcZd6C0ioWM5/feature_Force_Augmentation_0lOE0o9Fq4SXbBlu.json
  src/packs/classes/Null_ZeRU45NGZJpsKjIx/Psionic_Augmentations_TNk6pcZd6C0ioWM5/feature_Speed_Augmentation_rfV6DXw5jgoa9YCF.json
  src/packs/classes/Troubadour_AG8qTUvc61bqZ8Z8/Features_iTWybgqqHDo3r9bC/feature_Allow_Me_to_Introduce_Tonight_s_Players_BbRjIdFaxqvpz0Ro.json
  src/packs/classes/Troubadour_AG8qTUvc61bqZ8Z8/Features_iTWybgqqHDo3r9bC/feature_Appeal_to_the_Muses_QyOQyWQTeD80Bs53.json
  src/packs/classes/Troubadour_AG8qTUvc61bqZ8Z8/Features_iTWybgqqHDo3r9bC/feature_Formal_Introductions_UKAWlJW6P2f9HUao.json
  src/packs/classes/Troubadour_AG8qTUvc61bqZ8Z8/Features_iTWybgqqHDo3r9bC/feature_My_Reputation_Precedes_Me_10AvUbXDUxwfdgty.json
  src/packs/classes/Troubadour_AG8qTUvc61bqZ8Z8/Subclasses_RnNrB0juTKpIu7nj/subclass_Auteur_2hctjtw0GxZUW0Mb.json
  src/packs/classes/Troubadour_AG8qTUvc61bqZ8Z8/Subclasses_RnNrB0juTKpIu7nj/subclass_Duelist_cTrcnc9SZQ05yyf8.json
  src/packs/classes/Troubadour_AG8qTUvc61bqZ8Z8/Subclasses_RnNrB0juTKpIu7nj/subclass_Virtuoso_mpeU95QHdpNHrMwD.json
  src/packs/classes/Troubadour_AG8qTUvc61bqZ8Z8/class_Troubadour_JQxwKATOirc2weje.json
Labels: compendium

#896 Fixed chain deletion logic
  src/module/data/pseudo-documents/advancements/item-grant-advancement.mjs
Labels: data model

#917 Adjusted Item metadata
  src/module/data/item/ancestryTrait.mjs
  src/module/data/item/complication.mjs
  src/module/data/item/feature.mjs
  src/module/data/item/perk.mjs
  src/module/data/item/title.mjs
Labels: data model

#913 Talent L1 Signature Abilities
  src/packs/abilities/Talent_W4G9rOoBWQqffx2T/Level_1_OwLGXyW6518i4S2O/Signature_Hua1VikI1490yY1R/ability_Entropic_Bolt_haewa4VaniBE64vR.json
  src/packs/abilities/Talent_W4G9rOoBWQqffx2T/Level_1_OwLGXyW6518i4S2O/Signature_Hua1VikI1490yY1R/ability_Hoarfrost_KEckumFe4KcYqnHI.json
  src/packs/abilities/Talent_W4G9rOoBWQqffx2T/Level_1_OwLGXyW6518i4S2O/Signature_Hua1VikI1490yY1R/ability_Incinerate_sLLVoTJajJMzcr75.json
  src/packs/abilities/Talent_W4G9rOoBWQqffx2T/Level_1_OwLGXyW6518i4S2O/Signature_Hua1VikI1490yY1R/ability_Kinetic_Grip_bqge7XzOD5nhoUWU.json
  src/packs/abilities/Talent_W4G9rOoBWQqffx2T/Level_1_OwLGXyW6518i4S2O/Signature_Hua1VikI1490yY1R/ability_Kinetic_Pulse_dARXmI0O9neKftOj.json
  src/packs/abilities/Talent_W4G9rOoBWQqffx2T/Level_1_OwLGXyW6518i4S2O/Signature_Hua1VikI1490yY1R/ability_Materialize_TN62N2UfrSWzNall.json
  src/packs/abilities/Talent_W4G9rOoBWQqffx2T/Level_1_OwLGXyW6518i4S2O/Signature_Hua1VikI1490yY1R/ability_Optic_Blast_9eXjhpEgsqkgc3Dq.json
  src/packs/abilities/Talent_W4G9rOoBWQqffx2T/Level_1_OwLGXyW6518i4S2O/Signature_Hua1VikI1490yY1R/ability_Spirit_Sword_OK7FFzXmDaKn8nim.json
  src/packs/abilities/Talent_W4G9rOoBWQqffx2T/Level_1_OwLGXyW6518i4S2O/folders_3_Clarity_DDQszc7f2JZLgbRD.json
  src/packs/abilities/Talent_W4G9rOoBWQqffx2T/Level_1_OwLGXyW6518i4S2O/folders_5_Clarity_TdWMC0DlWhkMW0jl.json
  src/packs/abilities/Talent_W4G9rOoBWQqffx2T/Level_1_OwLGXyW6518i4S2O/folders_Signature_Hua1VikI1490yY1R.json
  src/packs/abilities/Talent_W4G9rOoBWQqffx2T/folders_Level_1_OwLGXyW6518i4S2O.json
  src/packs/classes/Talent_Q4pvMWEIONrsqHp0/class_Talent_iEnFxX8jUWZTthLp.json
Labels: compendium

#939 New classes start with null instead of 1
  src/module/data/actor/hero.mjs
  src/module/data/item/class.mjs
  src/module/utils/advancement-chain.mjs
Labels: data model

#942 Fixed AE path
  src/packs/classes/Elementalist_SVgKuVoWB0FrXkal/Features_JwIyKm3943QCjSQQ/Wards_0eCbuKfHkMLIW5pL/feature_Ward_of_Excellent_Protection_mV0Ohqmq4NnqSVqv.json
Labels: compendium

#944 Applied various errata
  lang/en.json
  src/docs/Home.md
  src/module/config.mjs
  src/packs/classes/Talent_Q4pvMWEIONrsqHp0/Features_oBlC3EZdWggPWyRn/feature_Clarity_and_Strain_MkF7O4vi1bEV6zJK.json
  src/packs/classes/Troubadour_AG8qTUvc61bqZ8Z8/class_Troubadour_JQxwKATOirc2weje.json
  src/packs/monster-features/Malice_Features_lr85fBx5XwieZOfH/Radenwight_Malice_03K0sUwNwFfBqFBD/ability_Trouser_Cut_wXnCVvnrDSeah9ks.json
  src/packs/monsters/Radenwights_DQYQ5rpRsohluWYD/npc_Radenwight_Maestro_mkez5eqX6Les2RJ9.json
  src/packs/monsters/Radenwights_DQYQ5rpRsohluWYD/npc_Radenwight_Redeye_KwdPnQj8bc4JlTqB.json
Labels: compendium, config

#931 Added Reset surges at end of combat #924
  CHANGELOG.md
  lang/en.json
  src/module/documents/combat.mjs
  system.json
Labels: apps

#966 [#964] Fixed compendium migration
  CHANGELOG.md
  src/module/data/migrations.mjs
Labels: data model

#974 Fixed order prep issues
  src/docs/Active-Effects.md
  src/module/data/actor/hero.mjs
Labels: data model

#962 [#953] Sort Skill List alphabetically
  src/module/applications/sheets/hero-sheet.mjs
Labels: apps

#978 Bugfix: Talent's Distance Augmentation
  CHANGELOG.md
  src/packs/classes/Talent_Q4pvMWEIONrsqHp0/Features_oBlC3EZdWggPWyRn/Psionic_Augmentations_1b95uSyyQlEuFh6G/feature_Distance_Augmentation_mwwEAQ5s5j8sBr1s.json
Labels: compendium

#947 Minor fixes for monster values
  CHANGELOG.md
  src/packs/monsters/Bugbears_IOJX0Gbij4nZLkvh/npc_Bugbear_Channeler_ZaENuomw1aFn4Ffw.json
  src/packs/monsters/Dwarves_aym4mi5JvyLiP0uV/npc_Dwarf_Warden_oOrOtSddf3x85DG3.json
  src/packs/monsters/Goblins_iEPVvWezLlidfEbg/npc_Goblin_Monarch_Vxxc0EcLHPPnpSbK.json
  src/packs/monsters/Goblins_iEPVvWezLlidfEbg/npc_Goblin_Runner_Xw0gZCS09gdMjaw8.json
  src/packs/monsters/Humans_zBFE173ZFzlEPX1o/npc_Human_Bandit_Chief_uuMc9pmKbvUdWMOz.json
  src/packs/monsters/Humans_zBFE173ZFzlEPX1o/npc_Human_Knave_hgK8SgOIzJ0bcAtf.json
  src/packs/monsters/Humans_zBFE173ZFzlEPX1o/npc_Human_Raider_wTq3vb6iy92uivRO.json
  src/packs/monsters/Radenwights_DQYQ5rpRsohluWYD/npc_Radenwight_Maestro_mkez5eqX6Les2RJ9.json
  src/packs/monsters/Undead_Awroz7YqtpURNlF5/npc_Crawling_Claw_V8CFcw8SAUNkcm7P.json
  src/packs/monsters/Undead_Awroz7YqtpURNlF5/npc_Ghost_hCxrYde7uzidWWWp.json
  src/packs/monsters/Undead_Awroz7YqtpURNlF5/npc_Rotting_Zombie_2KiVCGcov7SmCkWU.json
Labels: compendium

#951 Fury compendium
  CHANGELOG.md
  src/packs/abilities/Fury_NsE50OrdFsIk4ND2/Core_roGg2qsPifapFQEN/Beserker_EGlYHDfO6nZCu5ql/ability_Lines_of_Force_6JirKNIULN4f4Ii0.json
  src/packs/abilities/Fury_NsE50OrdFsIk4ND2/Core_roGg2qsPifapFQEN/Beserker_EGlYHDfO6nZCu5ql/ability_Special_Delivery_G7hQQ6kw8tezQasT.json
  src/packs/abilities/Fury_NsE50OrdFsIk4ND2/Core_roGg2qsPifapFQEN/Beserker_EGlYHDfO6nZCu5ql/ability_Wrecking_Ball_Z6fjVdH1w8Qw7HhO.json
  src/packs/abilities/Fury_NsE50OrdFsIk4ND2/Core_roGg2qsPifapFQEN/Reaver_mrOptVMwR2qMHSc6/ability_Death___Death__ozByaCzDqRAgPwfb.json
  src/packs/abilities/Fury_NsE50OrdFsIk4ND2/Core_roGg2qsPifapFQEN/Reaver_mrOptVMwR2qMHSc6/ability_Phalanx_Breaker_s9BN7D8qzckGdfxs.json
  src/packs/abilities/Fury_NsE50OrdFsIk4ND2/Core_roGg2qsPifapFQEN/Reaver_mrOptVMwR2qMHSc6/ability_Unearthly_Reflexes_CsIpGSv52h9optwM.json
  src/packs/abilities/Fury_NsE50OrdFsIk4ND2/Core_roGg2qsPifapFQEN/Stormwight_es8m9xL1fOPDpcey/ability_Apex_Predator_D4QW0O8gD7KCUDEJ.json
  src/packs/abilities/Fury_NsE50OrdFsIk4ND2/Core_roGg2qsPifapFQEN/Stormwight_es8m9xL1fOPDpcey/ability_Furious_Charge_DVAuB3PvTz4Q5Jmq.json
  src/packs/abilities/Fury_NsE50OrdFsIk4ND2/Core_roGg2qsPifapFQEN/Stormwight_es8m9xL1fOPDpcey/ability_Visceral_Roar_VUEZTcvQQssD9tbe.json
  src/packs/abilities/Fury_NsE50OrdFsIk4ND2/Core_roGg2qsPifapFQEN/folders_Beserker_EGlYHDfO6nZCu5ql.json
  src/packs/abilities/Fury_NsE50OrdFsIk4ND2/Core_roGg2qsPifapFQEN/folders_Reaver_mrOptVMwR2qMHSc6.json
  src/packs/abilities/Fury_NsE50OrdFsIk4ND2/Core_roGg2qsPifapFQEN/folders_Stormwight_es8m9xL1fOPDpcey.json
  src/packs/classes/Fury_xzykLzoRMsmgsRc8/Features_APQZ5fHFsMZFYLtD/Berserker_0Wss47OeUBckZUjf/feature_Primordial_Strength_JXioZdy4zIxskO72.json
  src/packs/classes/Fury_xzykLzoRMsmgsRc8/Features_APQZ5fHFsMZFYLtD/Berserker_0Wss47OeUBckZUjf/feature_Unstoppable_Force_HkHEcSI8Qkl9O9jq.json
  src/packs/classes/Fury_xzykLzoRMsmgsRc8/Features_APQZ5fHFsMZFYLtD/Reaver_cwNv3vTxWMKm7drG/feature_Inescapable_Wrath_TQITgGg6sLvg0kem.json
  src/packs/classes/Fury_xzykLzoRMsmgsRc8/Features_APQZ5fHFsMZFYLtD/Reaver_cwNv3vTxWMKm7drG/feature_Primordial_Cunning_KUCByYUPKEzXFSW7.json
  src/packs/classes/Fury_xzykLzoRMsmgsRc8/Features_APQZ5fHFsMZFYLtD/Stormwight_a0MNvX2SWZN6HiB3/feature_Beast_Shape_NtgaLC9isHfOmYFS.json
  src/packs/classes/Fury_xzykLzoRMsmgsRc8/Features_APQZ5fHFsMZFYLtD/Stormwight_a0MNvX2SWZN6HiB3/feature_Relentless_Hunter_nzPvUlVTEr1pXtfl.json
  src/packs/classes/Fury_xzykLzoRMsmgsRc8/Features_APQZ5fHFsMZFYLtD/Stormwight_a0MNvX2SWZN6HiB3/feature_Tooth_and_Claw_0hhfFop9W3W2jhSf.json
  src/packs/classes/Fury_xzykLzoRMsmgsRc8/Features_APQZ5fHFsMZFYLtD/folders_Berserker_0Wss47OeUBckZUjf.json
  src/packs/classes/Fury_xzykLzoRMsmgsRc8/Features_APQZ5fHFsMZFYLtD/folders_Reaver_cwNv3vTxWMKm7drG.json
  src/packs/classes/Fury_xzykLzoRMsmgsRc8/Features_APQZ5fHFsMZFYLtD/folders_Stormwight_a0MNvX2SWZN6HiB3.json
  src/packs/classes/Fury_xzykLzoRMsmgsRc8/Subclasses_rFvXxMH8zlkiyBYj/subclass_Berserker_UkRgXaZPKbt9VVp5.json
  src/packs/classes/Fury_xzykLzoRMsmgsRc8/Subclasses_rFvXxMH8zlkiyBYj/subclass_Reaver_k5tD7sSMemOrgeZl.json
  src/packs/classes/Fury_xzykLzoRMsmgsRc8/Subclasses_rFvXxMH8zlkiyBYj/subclass_Stormwight_OV3nfjXGHEzv4gUQ.json
  src/packs/classes/Fury_xzykLzoRMsmgsRc8/class_Fury_09NImezUFH1COsUX.json
Labels: compendium

#958 Null compendium
  src/packs/abilities/Null_3CEvbkuuVzQlvD3a/Core_CZ81nOfb3FIMsshV/Chronokinetic_ljJipRGPMOt9c83g/ability_Blur_5sOK6zpsT26siGVv.json
  src/packs/abilities/Null_3CEvbkuuVzQlvD3a/Core_CZ81nOfb3FIMsshV/Chronokinetic_ljJipRGPMOt9c83g/ability_Force_Redirected_rZ7xlB4qr35IKiFV.json
  src/packs/abilities/Null_3CEvbkuuVzQlvD3a/Core_CZ81nOfb3FIMsshV/Cyrokinetic_jRvZ381d8irzNgHX/ability_Entropic_Field_fbM16z6mgrQsUJIh.json
  src/packs/abilities/Null_3CEvbkuuVzQlvD3a/Core_CZ81nOfb3FIMsshV/Cyrokinetic_jRvZ381d8irzNgHX/ability_Heat_Sink_KPmPmv8x7T1BvwQv.json
  src/packs/abilities/Null_3CEvbkuuVzQlvD3a/Core_CZ81nOfb3FIMsshV/Metakinetic_MXimo7qA1zVVQmZB/ability_Gravitic_Strike_GqdQ7oTgAsqlGx0H.json
  src/packs/abilities/Null_3CEvbkuuVzQlvD3a/Core_CZ81nOfb3FIMsshV/Metakinetic_MXimo7qA1zVVQmZB/ability_Kinetic_Shield_AQK60y5FMgiLwPeH.json
  src/packs/abilities/Null_3CEvbkuuVzQlvD3a/Core_CZ81nOfb3FIMsshV/folders_Chronokinetic_ljJipRGPMOt9c83g.json
  src/packs/abilities/Null_3CEvbkuuVzQlvD3a/Core_CZ81nOfb3FIMsshV/folders_Cyrokinetic_jRvZ381d8irzNgHX.json
  src/packs/abilities/Null_3CEvbkuuVzQlvD3a/Core_CZ81nOfb3FIMsshV/folders_Metakinetic_MXimo7qA1zVVQmZB.json
  src/packs/classes/Null_ZeRU45NGZJpsKjIx/Features_oJjd2rCtL3HYUh8r/Chronokinetic_DXFNWeB3LneJYLhd/feature_Chronokinetic_Mastery_eGTpq8aSbCUvFhEq.json
  src/packs/classes/Null_ZeRU45NGZJpsKjIx/Features_oJjd2rCtL3HYUh8r/Chronokinetic_DXFNWeB3LneJYLhd/feature_Rapid_Processing_nVC2ZfFbQlNbFTh2.json
  src/packs/classes/Null_ZeRU45NGZJpsKjIx/Features_oJjd2rCtL3HYUh8r/Cyrokinetic_aq0IteMOnQawX65o/feature_Cryokinetic_Mastery_TseUqw7uV5nOcKOZ.json
  src/packs/classes/Null_ZeRU45NGZJpsKjIx/Features_oJjd2rCtL3HYUh8r/Cyrokinetic_aq0IteMOnQawX65o/feature_Entropic_Adaptability_tv0Rt75IyBTY7kbm.json
  src/packs/classes/Null_ZeRU45NGZJpsKjIx/Features_oJjd2rCtL3HYUh8r/Metakinetic_gToSJeHf6E9UiUfx/feature_Inertial_Sink_koD2LsOZRLbKprrA.json
  src/packs/classes/Null_ZeRU45NGZJpsKjIx/Features_oJjd2rCtL3HYUh8r/Metakinetic_gToSJeHf6E9UiUfx/feature_Metakinetic_Mastery_FuPWCTJdGWNEOmTe.json
  src/packs/classes/Null_ZeRU45NGZJpsKjIx/Features_oJjd2rCtL3HYUh8r/folders_Chronokinetic_DXFNWeB3LneJYLhd.json
  src/packs/classes/Null_ZeRU45NGZJpsKjIx/Features_oJjd2rCtL3HYUh8r/folders_Cyrokinetic_aq0IteMOnQawX65o.json
  src/packs/classes/Null_ZeRU45NGZJpsKjIx/Features_oJjd2rCtL3HYUh8r/folders_Metakinetic_gToSJeHf6E9UiUfx.json
  src/packs/classes/Null_ZeRU45NGZJpsKjIx/Subclasses_dPBywq1BJXheX3ez/subclass_Chronokinetic_7AYn4Us1eUSVAK57.json
  src/packs/classes/Null_ZeRU45NGZJpsKjIx/Subclasses_dPBywq1BJXheX3ez/subclass_Cryokinetic_qAuOMzb8UDpGspSu.json
  src/packs/classes/Null_ZeRU45NGZJpsKjIx/Subclasses_dPBywq1BJXheX3ez/subclass_Metakinetic_Np5tks1bN3bTWPr8.json
  src/packs/classes/Null_ZeRU45NGZJpsKjIx/class_Null_ovVqD2Zj5csqOjf7.json
Labels: compendium

#968 Conduit 2nd Level Features and Abilities
  src/packs/abilities/Conduit_5y6vuu4yT5kdzSLd/Core_JJpf8PudWJzeuRVe/Creation_g3kwOzCV84yVea1J/ability_Statue_of_Power_Nx6KHV96yUc5qlCi.json
  src/packs/abilities/Conduit_5y6vuu4yT5kdzSLd/Core_JJpf8PudWJzeuRVe/Death_Z4fGY0bILcpzVcAP/ability_Reap_OqZbt8MOyCeVkd5z.json
  src/packs/abilities/Conduit_5y6vuu4yT5kdzSLd/Core_JJpf8PudWJzeuRVe/Fate_YKQZEeslZiDt7fBQ/ability_Blessing_of_Fate_and_Destiny_tpEhMJt2yZATNnlo.json
  src/packs/abilities/Conduit_5y6vuu4yT5kdzSLd/Core_JJpf8PudWJzeuRVe/Knowledge_2WJCgYn1Xtjxbmfl/ability_The_Gods_Command_You_Obey_NoFwNxcQOyFBZBIT.json
  src/packs/abilities/Conduit_5y6vuu4yT5kdzSLd/Core_JJpf8PudWJzeuRVe/Life_r3yrn4LrUapLgcAR/ability_Wellspring_of_Grace_zL3k5GHQeyoSxb8j.json
  src/packs/abilities/Conduit_5y6vuu4yT5kdzSLd/Core_JJpf8PudWJzeuRVe/Love_upY2TMTEiXo18bi4/ability_Our_Hearts_Your_Strength_vMq4N7eRlhDxXbaJ.json
  src/packs/abilities/Conduit_5y6vuu4yT5kdzSLd/Core_JJpf8PudWJzeuRVe/Nature_teoylKt113aAB9Mk/ability_Nature_Judges_Thee_izUb8dD36TPQcwmC.json
  src/packs/abilities/Conduit_5y6vuu4yT5kdzSLd/Core_JJpf8PudWJzeuRVe/Protection_dMRN0MF04qxJAXY9/ability_Sacred_Bond_SoSmdyoPB32dhQlz.json
  src/packs/abilities/Conduit_5y6vuu4yT5kdzSLd/Core_JJpf8PudWJzeuRVe/Storm_RQWNxmWmJlR929B2/ability_Saint_s_Tempest_YstGmEeDnNvezcSJ.json
  src/packs/abilities/Conduit_5y6vuu4yT5kdzSLd/Core_JJpf8PudWJzeuRVe/Sun_iNrbi28xOKLjhkhm/ability_Morning_Light_hyVX7vAE7UfchuVv.json
  src/packs/abilities/Conduit_5y6vuu4yT5kdzSLd/Core_JJpf8PudWJzeuRVe/Trickery_CebswWODf1zpbY26/ability_Divine_Comedy_adYj0xjaSgOflVg2.json
  src/packs/abilities/Conduit_5y6vuu4yT5kdzSLd/Core_JJpf8PudWJzeuRVe/War_9zHfunZlQCJKHFjq/ability_Blessing_of_Insight_6EufjD3NoSD6xglV.json
  src/packs/abilities/Conduit_5y6vuu4yT5kdzSLd/Core_JJpf8PudWJzeuRVe/folders_Creation_g3kwOzCV84yVea1J.json
  src/packs/abilities/Conduit_5y6vuu4yT5kdzSLd/Core_JJpf8PudWJzeuRVe/folders_Death_Z4fGY0bILcpzVcAP.json
  src/packs/abilities/Conduit_5y6vuu4yT5kdzSLd/Core_JJpf8PudWJzeuRVe/folders_Fate_YKQZEeslZiDt7fBQ.json
  src/packs/abilities/Conduit_5y6vuu4yT5kdzSLd/Core_JJpf8PudWJzeuRVe/folders_Knowledge_2WJCgYn1Xtjxbmfl.json
  src/packs/abilities/Conduit_5y6vuu4yT5kdzSLd/Core_JJpf8PudWJzeuRVe/folders_Life_r3yrn4LrUapLgcAR.json
  src/packs/abilities/Conduit_5y6vuu4yT5kdzSLd/Core_JJpf8PudWJzeuRVe/folders_Love_upY2TMTEiXo18bi4.json
  src/packs/abilities/Conduit_5y6vuu4yT5kdzSLd/Core_JJpf8PudWJzeuRVe/folders_Nature_teoylKt113aAB9Mk.json
  src/packs/abilities/Conduit_5y6vuu4yT5kdzSLd/Core_JJpf8PudWJzeuRVe/folders_Protection_dMRN0MF04qxJAXY9.json
  src/packs/abilities/Conduit_5y6vuu4yT5kdzSLd/Core_JJpf8PudWJzeuRVe/folders_Storm_RQWNxmWmJlR929B2.json
  src/packs/abilities/Conduit_5y6vuu4yT5kdzSLd/Core_JJpf8PudWJzeuRVe/folders_Sun_iNrbi28xOKLjhkhm.json
  src/packs/abilities/Conduit_5y6vuu4yT5kdzSLd/Core_JJpf8PudWJzeuRVe/folders_Trickery_CebswWODf1zpbY26.json
  src/packs/abilities/Conduit_5y6vuu4yT5kdzSLd/Core_JJpf8PudWJzeuRVe/folders_War_9zHfunZlQCJKHFjq.json
  src/packs/classes/Conduit_1KqNzItDbgiZLVOP/Features_CQqSbxZtbGl6Oz1I/feature_The_Lists_of_Heaven_xRRa0ywFLZYQIKAl.json
  src/packs/classes/Conduit_1KqNzItDbgiZLVOP/Features_CQqSbxZtbGl6Oz1I/folders_Wards_Features_rUvb5qTRoejLGTCG.json
  src/packs/classes/Conduit_1KqNzItDbgiZLVOP/class_Conduit_acA2B3ecGohNxhnb.json
Labels: compendium

#969 Tactician Compendium 2nd Level
  src/packs/abilities/Tactician_If39E6GsmUaOGSIx/Core_namgjInmC0X7jtJb/Insurgent_7Z2cHVVXlT5l3q7i/ability_Fog_of_War_lXBts5HfbqQiG8I5.json
  src/packs/abilities/Tactician_If39E6GsmUaOGSIx/Core_namgjInmC0X7jtJb/Insurgent_7Z2cHVVXlT5l3q7i/ability_Try_Me_Instead_kyP17StswrMKVB1B.json
  src/packs/abilities/Tactician_If39E6GsmUaOGSIx/Core_namgjInmC0X7jtJb/Mastermind_dxYqVYHYSHa9Z6wA/ability_I_ve_Got_Your_Back_jZhSZt9MG8RdkwuP.json
  src/packs/abilities/Tactician_If39E6GsmUaOGSIx/Core_namgjInmC0X7jtJb/Mastermind_dxYqVYHYSHa9Z6wA/ability_Target_Opportunity_sJ94rnHKQ0lXKTn9.json
  src/packs/abilities/Tactician_If39E6GsmUaOGSIx/Core_namgjInmC0X7jtJb/Vanguard_biirsVUobAUKyiKS/ability_No_Dying_on_My_Watch_dmRvrbXgLuHdLdSt.json
  src/packs/abilities/Tactician_If39E6GsmUaOGSIx/Core_namgjInmC0X7jtJb/Vanguard_biirsVUobAUKyiKS/ability_Squad__On_Me__VeIMrwu1dIHsJcwA.json
  src/packs/abilities/Tactician_If39E6GsmUaOGSIx/Core_namgjInmC0X7jtJb/folders_Insurgent_7Z2cHVVXlT5l3q7i.json
  src/packs/abilities/Tactician_If39E6GsmUaOGSIx/Core_namgjInmC0X7jtJb/folders_Mastermind_dxYqVYHYSHa9Z6wA.json
  src/packs/abilities/Tactician_If39E6GsmUaOGSIx/Core_namgjInmC0X7jtJb/folders_Vanguard_biirsVUobAUKyiKS.json
  src/packs/classes/Tactician_kCN3c3aC6ziHDp5c/Features_78pbwV8U2xiEUz57/Insurgent_71KLGY8ZFgHTFLl5/feature_Infiltration_Tactics_h9n9hOvO9ivTHDDl.json
  src/packs/classes/Tactician_kCN3c3aC6ziHDp5c/Features_78pbwV8U2xiEUz57/Mastermind_0tLAXLNV7O52athN/feature_Goaded_4LfPih11ovksHOcR.json
  src/packs/classes/Tactician_kCN3c3aC6ziHDp5c/Features_78pbwV8U2xiEUz57/Vanguard_70HZxf7jq2w3W56e/feature_Melee_Superiority_aFOYtWMepJpHjzp6.json
  src/packs/classes/Tactician_kCN3c3aC6ziHDp5c/Subclasses_86F9T9t6YK1WafzV/subclass_Insurgent_VfwdbL1GG2Dx0zv7.json
  src/packs/classes/Tactician_kCN3c3aC6ziHDp5c/Subclasses_86F9T9t6YK1WafzV/subclass_Mastermind_aYjVEZyiYqtdGGPS.json
  src/packs/classes/Tactician_kCN3c3aC6ziHDp5c/Subclasses_86F9T9t6YK1WafzV/subclass_Vanguard_OjWhetKz8boQxExU.json
  src/packs/classes/Tactician_kCN3c3aC6ziHDp5c/class_Tactician_Y6rtfW6EfHszGqhG.json
Labels: compendium
