Repository MetaMorphic-Digital/draw-steel, pull requests merged in 2025-06, with the labels that each got.

#560 Updated Readme
  README.md
  src/module/applications/api/document-sheet-mixin.mjs
  src/module/canvas/placeables/tokens/token-ruler.mjs
Labels: documentation

#565 Miscellaneous Type Updates
  src/module/applications/sheets/_types.d.ts
  src/module/applications/sheets/actor-sheet.mjs
  src/module/applications/sheets/combatant-group-config.mjs
  src/module/data/item/base.mjs
  src/module/data/subtype-model-mixin.mjs
  src/module/documents/actor.mjs
  src/module/documents/base-document-mixin.mjs
  src/module/documents/item.mjs
Labels: documentation, tech debt

#566 Fixed Free Strike Logic
  draw-steel.d.ts
  lang/en.json
  src/module/applications/sheets/npc.mjs
  src/module/data/actor/npc.mjs
Labels: data model

#570 Document spelling corrections
  src/docs/Combat-Encounters.md
Labels: documentation

#572 Added Spend to embedded display
  src/module/data/item/ability.mjs
  src/styles/system/applications/sheets/actor-sheet.css
  templates/item/embeds/ability.hbs
Labels: apps

#573 Minor styling and type fixes
  CHANGELOG.md
  src/module/data/fields/_types.d.ts
  src/styles/system/applications/sheets/item-sheet.css
Labels: UI/UX

#587 Made DSID read only, added top-level getter
  CHANGELOG.md
  src/docs/Roll-Data.md
  src/module/data/item/ability.mjs
  src/module/data/item/base.mjs
  src/module/documents/item.mjs
Labels: data model

#579 Updated CLI, added basic maneuvers
  CHANGELOG.md
  package-lock.json
  package.json
  src/module/config.mjs
  src/module/data/actor/character.mjs
  src/packs/abilities/Basic_Abilities_YKzQ5cCX8knW8fAc/ability_Aid_Attack_Xb3S5N1fZyICD58D.json
  src/packs/abilities/Basic_Abilities_YKzQ5cCX8knW8fAc/ability_Catch_Breath_nYPJN8Ce2dX9H09K.json
  src/packs/abilities/Basic_Abilities_YKzQ5cCX8knW8fAc/ability_Charge_wNqJWJbgAbnJBqZf.json
  src/packs/abilities/Basic_Abilities_YKzQ5cCX8knW8fAc/ability_Defend_fjtY7RKBGWx2u5tK.json
  src/packs/abilities/Basic_Abilities_YKzQ5cCX8knW8fAc/ability_Escape_Grab_iD1SlB15GXJFALya.json
  src/packs/abilities/Basic_Abilities_YKzQ5cCX8knW8fAc/ability_Grab_oxaISpgVoCfo6fmt.json
  src/packs/abilities/Basic_Abilities_YKzQ5cCX8knW8fAc/ability_Heal_2qWHDVB7SBS9anLB.json
  src/packs/abilities/Basic_Abilities_YKzQ5cCX8knW8fAc/ability_Hide_JykB1rELpGBeAVe6.json
  src/packs/abilities/Basic_Abilities_YKzQ5cCX8knW8fAc/ability_Knockback_emug9cXuwndDrWzu.json
  src/packs/abilities/Basic_Abilities_YKzQ5cCX8knW8fAc/ability_Melee_Free_Strike_wU69Y06G9lYFrvp6.json
  src/packs/abilities/Basic_Abilities_YKzQ5cCX8knW8fAc/ability_Ranged_Free_Strike_eqUobBcm81mqZVgJ.json
  src/packs/abilities/Basic_Abilities_YKzQ5cCX8knW8fAc/ability_Search_for_Hidden_Creatures_zQ83mlzlRtflpD3w.json
  src/packs/abilities/Basic_Abilities_YKzQ5cCX8knW8fAc/ability_Stand_Up_XeUU0Blvi0fy0b2G.json
  src/packs/abilities/folders_Basic_Abilities_YKzQ5cCX8knW8fAc.json
  src/packs/journals/Combat_wnqp2PFeCN9C0VOw/journal_Conditions_hDhdILCi65wpBgPZ.json
  src/packs/journals/Rules_fsCmsFx1Bwyqwgl0/journal_The_Basics_f8eNK5Pte4CSdex0.json
  src/packs/journals/folders_Combat_wnqp2PFeCN9C0VOw.json
  src/packs/journals/folders_Rules_fsCmsFx1Bwyqwgl0.json
  src/packs/journals/journal_System_Documentation_2OWtCOMKRpGuBxrI.json
  system.json
  tools/pullJSONtoLDB.mjs
  tools/pushLDBtoJSON.mjs
Labels: compendium

#594 Documentation fixes
  src/docs/Active-Effects.md
  src/docs/Combat-Encounters.md
  src/docs/Home.md
  src/docs/System-Automation.md
  src/packs/journals/journal_System_Documentation_2OWtCOMKRpGuBxrI.json
Labels: documentation

#600 Add equipment stacking
  lang/en.json
  src/module/applications/sheets/character.mjs
  src/module/data/item/equipment.mjs
  src/module/data/item/project.mjs
  src/module/rolls/project.mjs
  src/styles/system/applications/sheets/actor-sheet.css
  templates/actor/character/equipment.hbs
  templates/item/partials/equipment.hbs
Labels: data model

#598 Updated system.json for 0.7.3
  system.json
Labels: tech debt

#608 Updated actor sheet Ability and Equipment header display
  CHANGELOG.md
  src/module/applications/sheets/_types.d.ts
  src/module/applications/sheets/actor-sheet.mjs
  src/module/applications/sheets/character.mjs
  templates/actor/character/equipment.hbs
  templates/actor/shared/abilities.hbs
Labels: UI/UX

#614 Began work on Roll Enricher
  CHANGELOG.md
  css/draw-steel-system.css
  draw-steel.mjs
  lang/en.json
  src/module/applications/_module.mjs
  src/module/applications/ux/_module.mjs
  src/module/applications/ux/enrichers/_module.mjs
  src/module/applications/ux/enrichers/roll.mjs
  src/module/config.mjs
  src/styles/system/applications/_applications.mjs
  src/styles/system/applications/ux/enrichers.css
Labels: roll

#617 Added healing capabilities, documentation
  CHANGELOG.md
  lang/en.json
  src/docs/Enrichers.md
  src/module/applications/ux/enrichers/roll.mjs
  src/module/rolls/damage.mjs
  src/packs/journals/Combat_wnqp2PFeCN9C0VOw/journal_Conditions_hDhdILCi65wpBgPZ.json
Labels: data model, roll

#619 Adjusted edit vs play mode logic
  CHANGELOG.md
  src/module/applications/api/document-sheet-mixin.mjs
  src/module/applications/sheets/actor-sheet.mjs
  src/module/applications/sheets/item-sheet.mjs
  templates/actor/character/projects.hbs
  templates/actor/shared/features.hbs
Labels: UI/UX

#621 Made better use of core css
  src/styles/system/applications/api/roll-dialog.css
  templates/rolls/roll-dialog-footer.hbs
Labels: UI/UX

#620 Improved display and application of statuses in pane
  CHANGELOG.md
  draw-steel.mjs
  src/module/applications/_module.mjs
  src/module/applications/hud/_module.mjs
  src/module/applications/hud/token-hud.mjs
  src/module/documents/actor.mjs
  src/module/documents/item.mjs
  src/styles/system/applications/canvas/token-hud.css
  templates/hud/effect-palette.hbs
  templates/hud/token-movement.hbs
Labels: apps, UI/UX

#624 Fixed individual sheet theme overrides
  CHANGELOG.md
  src/styles/variables/colors.css
Labels: UI/UX

#625 Overhauled Actor and Item Effects Tab
  CHANGELOG.md
  draw-steel.mjs
  lang/en.json
  src/module/applications/sheets/actor-sheet.mjs
  src/module/applications/sheets/item-sheet.mjs
  src/module/config.mjs
  src/module/constants.mjs
  src/module/data/_types.d.ts
  src/module/data/actor/character.mjs
  src/module/data/actor/npc.mjs
  src/module/documents/active-effect.mjs
  src/styles/system/applications/components/effects.css
  src/styles/system/applications/components/items.css
  src/styles/system/applications/sheets/actor-sheet.css
  templates/actor/character/equipment.hbs
  templates/actor/character/projects.hbs
  templates/actor/shared/abilities.hbs
  templates/actor/shared/effects.hbs
  templates/actor/shared/features.hbs
  templates/item/effects.hbs
Labels: apps

#630 Adjusted data prep order
  CHANGELOG.md
  src/module/data/item/ability.mjs
  src/module/data/settings/hero-tokens.mjs
  src/module/data/settings/malice.mjs
Labels: data model

#631 Fix malice generation double applying first round bonus
  CHANGELOG.md
  src/module/data/settings/malice.mjs
Labels: data model

#633 Added support for negative heroic resources
  CHANGELOG.md
  lang/en.json
  src/module/data/actor/_types.d.ts
  src/module/data/actor/base.mjs
  src/module/data/actor/character.mjs
  src/module/data/actor/npc.mjs
  src/module/data/item/_types.d.ts
  src/module/data/item/ability.mjs
  src/module/data/item/class.mjs
  src/module/documents/actor.mjs
  templates/item/partials/class.hbs
Labels: data model

#644 Updated system minimums
  CHANGELOG.md
  system.json
Labels: tech debt

#663 Removed duplicate function
  src/module/documents/base-document-mixin.mjs
Labels: data model

#666 [#658] Add description to advancement sheets.
  src/module/applications/sheets/pseudo-documents/advancement-sheet.mjs
  src/module/data/pseudo-documents/advancements/base-advancement.mjs
  system.json
  templates/sheets/pseudo-documents/advancement/identity.hbs
Labels: data model

#665 [#659] Render pseudo-document sheet when created.
  src/module/data/pseudo-documents/pseudo-document.mjs
Labels: apps
