Repository MetaMorphic-Digital/draw-steel, pull requests merged in 2025-07, with the labels that each got.

#664 [#214] Refactored AppliedPowerRollEffect model and display
  lang/en.json
  src/module/applications/api/pseudo-document-sheet.mjs
  src/module/applications/sheets/active-effect-config.mjs
  src/module/applications/sheets/pseudo-documents/power-roll-effect-sheet.mjs
  src/module/config.mjs
  src/module/constants.mjs
  src/module/data/effect/base.mjs
  src/module/data/message/_types.d.ts
  src/module/data/message/ability-use.mjs
  src/module/data/message/base.mjs
  src/module/data/pseudo-documents/power-roll-effects/_types.d.ts
  src/module/data/pseudo-documents/power-roll-effects/applied-effect.mjs
  src/module/rolls/damage.mjs
  src/module/utils/_module.mjs
  src/module/utils/construct-html-button.mjs
  src/module/utils/selected-actors.mjs
  src/module/utils/tokens-to-actors.mjs
  src/styles/system/applications/components/forms.css
  templates/active-effect/config-duration.hbs
  templates/sheets/pseudo-documents/power-roll-effect-sheet/details-tiers.hbs
Labels: data model, apps

#672 Added Apply Effect Button
  CHANGELOG.md
  lang/en.json
  src/module/data/item/_types.d.ts
  src/module/data/message/ability-use.mjs
  src/module/data/pseudo-documents/power-roll-effects/applied-effect.mjs
  src/module/data/pseudo-documents/power-roll-effects/base-power-roll-effect.mjs
  src/module/utils/construct-html-button.mjs
  src/styles/system/applications/sidebar/tabs/chat.css
Labels: apps

#675 Added Wealth, Renown, and Appearance info
  CHANGELOG.md
  lang/en.json
  src/module/applications/sheets/character.mjs
  src/module/config.mjs
  src/module/data/actor/_types.d.ts
  src/module/data/actor/character.mjs
  src/module/data/item/career.mjs
  src/styles/system/applications/sheets/actor-sheet.css
  templates/actor/character/biography.hbs
  templates/actor/shared/partials/biography/languages.hbs
  templates/item/partials/career.hbs
Labels: data model

#681 [#651] Implemented Trait Choices
  css/draw-steel-system.css
  draw-steel.mjs
  lang/en.json
  src/module/_types.d.ts
  src/module/applications/sheets/pseudo-documents/advancement-sheet.mjs
  src/module/config.mjs
  src/module/data/pseudo-documents/_module.mjs
  src/module/data/pseudo-documents/_types.d.ts
  src/module/data/pseudo-documents/advancements/_module.mjs
  src/module/data/pseudo-documents/advancements/_types.d.ts
  src/module/data/pseudo-documents/advancements/base-advancement.mjs
  src/module/data/pseudo-documents/advancements/item-grant-advancement.mjs
  src/module/data/pseudo-documents/advancements/language-advancement.mjs
  src/module/data/pseudo-documents/advancements/skill-advancement.mjs
  src/module/data/pseudo-documents/advancements/trait-advancement.mjs
  src/module/data/pseudo-documents/power-roll-effects/_types.d.ts
  src/module/data/pseudo-documents/trait-choices/_module.mjs
  src/module/data/pseudo-documents/trait-choices/base-trait-choice.mjs
  src/module/utils/advancement-chain.mjs
  src/packs/classes/Shadow_ngcpmEclU2UUJbz4/class_Shadow_08pJ0i8AwjMsrKO1.json
  src/packs/classes/folders_Shadow_ngcpmEclU2UUJbz4.json
  src/styles/system/applications/_applications.mjs
  src/styles/system/applications/sheets/pseudo-documents.css
  templates/apps/advancement/chain-configuration-dialog/chains.hbs
  templates/sheets/pseudo-documents/advancement/details.hbs
Labels: data model

#687 Moved recoveries out of `hero`, made max stamina and recoveries derived
  CHANGELOG.md
  lang/en.json
  src/docs/Enrichers.md
  src/docs/Roll-Data.md
  src/module/data/actor/_types.d.ts
  src/module/data/actor/base.mjs
  src/module/data/actor/character.mjs
  src/module/data/helpers.mjs
  src/module/data/item/class.mjs
  templates/actor/character/stats.hbs
Labels: data model

#711 Switched interface use to fix autocomplete for normal documents
  src/module/documents/_types.d.ts
Labels: tech debt

#700 Non class advancements
  lang/en.json
  src/module/applications/apps/advancement/chain-configuration-dialog.mjs
  src/module/applications/sheets/_types.d.ts
  src/module/applications/sheets/character.mjs
  src/module/applications/sheets/item-sheet.mjs
  src/module/data/actor/character.mjs
  src/module/data/item/_types.d.ts
  src/module/data/item/advancement.mjs
  src/module/data/item/ancestry.mjs
  src/module/data/item/career.mjs
  src/module/data/item/class.mjs
  src/module/data/item/culture.mjs
  src/module/data/item/feature.mjs
  src/module/data/item/kit.mjs
  src/module/data/item/project.mjs
  src/packs/abilities/Kits_9MmUCFDVEUEgDY04/ability_Protective_Attack_3G70A9bFAJzp7nxD.json
  src/packs/abilities/folders_Kits_9MmUCFDVEUEgDY04.json
  src/packs/ancestries/Devil_vI2lXvZhkhwHKLrz/Features_eTVTaGVRRrrni84u/feature_Silver_Tongue_Ch6TwaIZ8MxXYzbn.json
  src/packs/ancestries/Devil_vI2lXvZhkhwHKLrz/ancestry_Devil_VfIna2d0jNXwKNaT.json
  src/packs/ancestries/Devil_vI2lXvZhkhwHKLrz/folders_Features_eTVTaGVRRrrni84u.json
  src/packs/ancestries/folders_Devil_vI2lXvZhkhwHKLrz.json
  src/packs/backgrounds/Careers_dfwhC8sAkXlLOMLj/career_Aristocrat_UErgToE9dTiUHkCh.json
  src/packs/backgrounds/Cultures_SNTVv8Z0uNTC8Wab/culture_Devil_Culture_8wbziVKFMsQASWEz.json
  src/packs/backgrounds/folders_Careers_dfwhC8sAkXlLOMLj.json
  src/packs/backgrounds/folders_Cultures_SNTVv8Z0uNTC8Wab.json
  src/packs/kits/kit_Shining_Armor_I6ttpLWPanflkVFP.json
  system.json
  tools/pushLDBtoJSON.mjs
Labels: data model

#717 [#59] Culture Advancements
  CHANGELOG.md
  lang/en.json
  src/module/applications/sheets/item-sheet.mjs
  src/module/config.mjs
  src/module/data/item/culture.mjs
  templates/sheets/item/advancement.hbs
  templates/sheets/item/impact.hbs
  templates/sidebar/tabs/combat/tracker.hbs
Labels: apps

#725 Switched to using spread operator for metadata, other cleanup
  CHANGELOG.md
  src/module/applications/sheets/item-sheet.mjs
  src/module/canvas/placeables/token.mjs
  src/module/data/actor/character.mjs
  src/module/data/actor/npc.mjs
  src/module/data/combat/base.mjs
  src/module/data/combatant-group/base.mjs
  src/module/data/combatant-group/squad.mjs
  src/module/data/combatant/base.mjs
  src/module/data/effect/base.mjs
  src/module/data/item/ability.mjs
  src/module/data/item/advancement.mjs
  src/module/data/item/ancestry.mjs
  src/module/data/item/base.mjs
  src/module/data/item/career.mjs
  src/module/data/item/class.mjs
  src/module/data/item/complication.mjs
  src/module/data/item/culture.mjs
  src/module/data/item/equipment.mjs
  src/module/data/item/feature.mjs
  src/module/data/item/kit.mjs
  src/module/data/item/project.mjs
  src/module/data/message/ability-use.mjs
  src/module/data/message/base.mjs
  src/module/data/message/saving-throw.mjs
  src/module/data/pseudo-documents/advancements/base-advancement.mjs
  src/module/data/pseudo-documents/advancements/language-advancement.mjs
  src/module/data/pseudo-documents/advancements/skill-advancement.mjs
  src/module/data/pseudo-documents/advancements/trait-advancement.mjs
  src/module/documents/actor.mjs
Labels: tech debt

#723 [#718] Added name and img to pseudodocument creation dialog
  CHANGELOG.md
  draw-steel.mjs
  lang/en.json
  src/module/applications/sheets/item-sheet.mjs
  src/module/applications/sheets/pseudo-documents/advancement-sheet.mjs
  src/module/data/pseudo-documents/advancements/base-advancement.mjs
  src/module/data/pseudo-documents/pseudo-document.mjs
  src/module/data/pseudo-documents/typed-pseudo-document.mjs
  templates/sheets/pseudo-documents/create-dialog.hbs
Labels: apps

#727 [#694] Add next respite effect ends option
  CHANGELOG.md
  lang/en.json
  src/module/config.mjs
  src/module/data/actor/character.mjs
Labels: config

#728 Add option to equipment context menu to start crafting project from equipment
  CHANGELOG.md
  lang/en.json
  src/module/applications/sheets/actor-sheet.mjs
  src/module/data/item/equipment.mjs
Labels: apps

#732 [#588] Update gm fields to director
  lang/en.json
  src/docs/Roll-Data.md
  src/module/applications/sheets/actor-sheet.mjs
  src/module/applications/sheets/character.mjs
  src/module/applications/sheets/item-sheet.mjs
  src/module/applications/sheets/npc.mjs
  src/module/data/actor/_types.d.ts
  src/module/data/actor/base.mjs
  src/module/data/item/_types.d.ts
  src/module/data/item/base.mjs
  src/packs/ancestries/Devil_vI2lXvZhkhwHKLrz/Features_eTVTaGVRRrrni84u/feature_Silver_Tongue_Ch6TwaIZ8MxXYzbn.json
  src/packs/ancestries/Devil_vI2lXvZhkhwHKLrz/ancestry_Devil_VfIna2d0jNXwKNaT.json
  src/packs/backgrounds/Careers_dfwhC8sAkXlLOMLj/career_Aristocrat_UErgToE9dTiUHkCh.json
  src/packs/backgrounds/Cultures_SNTVv8Z0uNTC8Wab/culture_Devil_Culture_8wbziVKFMsQASWEz.json
  src/packs/classes/Shadow_ngcpmEclU2UUJbz4/class_Shadow_08pJ0i8AwjMsrKO1.json
  src/packs/classes/Tactician_kCN3c3aC6ziHDp5c/Features_78pbwV8U2xiEUz57/Insurgent_esL2aRheKQFmhZv3/feature_Covert_Operations_ajeWFtiJThAAAVQc.json
  src/packs/classes/Tactician_kCN3c3aC6ziHDp5c/Features_78pbwV8U2xiEUz57/Mastermind_qRX2Nw2GyMjTcT97/feature_Studied_Commander_X8RA9Fp6vFF5AeKR.json
  src/packs/classes/Tactician_kCN3c3aC6ziHDp5c/Features_78pbwV8U2xiEUz57/Vanguard_qJtTXv1bHR7ciN2S/feature_Commanding_Presence_wdOsstaPrLX5WcVa.json
  src/packs/classes/Tactician_kCN3c3aC6ziHDp5c/Features_78pbwV8U2xiEUz57/feature_Field_Arsenal_dNGmfuNuaML5TRQL.json
  src/packs/classes/Tactician_kCN3c3aC6ziHDp5c/Features_78pbwV8U2xiEUz57/feature_Focus_BsbaqvmoNmQLIhkS.json
  src/packs/classes/Tactician_kCN3c3aC6ziHDp5c/Features_78pbwV8U2xiEUz57/feature_Out_of_Position_UMi9OOllnmMinI9h.json
  src/packs/classes/Tactician_kCN3c3aC6ziHDp5c/class_Tactician_Y6rtfW6EfHszGqhG.json
  src/packs/kits/kit_Shining_Armor_I6ttpLWPanflkVFP.json
  system.json
  templates/sheets/actor/character/biography.hbs
  templates/sheets/actor/npc/biography.hbs
  templates/sheets/actor/shared/partials/biography/director-notes.hbs
  templates/sheets/actor/shared/partials/biography/gm-notes.hbs
  templates/sheets/item/description.hbs
Labels: data model

#730 Cleaned up item context options
  lang/en.json
  src/module/applications/sheets/actor-sheet.mjs
Labels: UI/UX

#729 [#185] subclasses
  lang/en.json
  src/module/applications/sheets/character.mjs
  src/module/data/actor/character.mjs
  src/module/data/item/_module.mjs
  src/module/data/item/_types.d.ts
  src/module/data/item/subclass.mjs
  src/packs/classes/Tactician_kCN3c3aC6ziHDp5c/Subclasses_86F9T9t6YK1WafzV/subclass_Insurgent_VfwdbL1GG2Dx0zv7.json
  src/packs/classes/Tactician_kCN3c3aC6ziHDp5c/Subclasses_86F9T9t6YK1WafzV/subclass_Mastermind_aYjVEZyiYqtdGGPS.json
  src/packs/classes/Tactician_kCN3c3aC6ziHDp5c/Subclasses_86F9T9t6YK1WafzV/subclass_Vanguard_OjWhetKz8boQxExU.json
  system.json
  templates/sheets/actor/character/equipment.hbs
  templates/sheets/actor/character/header.hbs
  templates/sheets/actor/shared/features.hbs
  templates/sheets/item/partials/subclass.hbs
Labels: data model

#741 Potentially fix hero stamina bug
  src/module/data/item/class.mjs
Labels: data model

#742 Refactored _onDropFolder handling
  CHANGELOG.md
  lang/en.json
  src/module/applications/sheets/actor-sheet.mjs
  src/module/applications/sheets/character.mjs
  src/module/data/actor/character.mjs
Labels: apps

#721 FAQ Doc update
  assets/docs/HTML-mode-explainer.png
  src/docs/Enrichers.md
  src/docs/Frequently-Asked-Questions.md
Labels: documentation

#749 Adjusted actor sheet context menu
  CHANGELOG.md
  src/module/applications/sheets/actor-sheet.mjs
Labels: apps
